PER: libPeR_base/example/CartesianPolynomial2FisheyeOpenCV/CartesianPolynomial2FisheyeOpenCV.cpp File Reference
CartesianPolynomial2FisheyeOpenCV.cpp File Reference
#include <iostream>
#include <per/prPerspective.h>
#include <per/prCameraModelConvert.h>
#include <per/prPolyCart.h>
#include <visp/vpMatrix.h>
Functions
int main ()
Detailed Description
Example program to convert a PeR camera model to another.
Author
Eva GOICHON
Version
0.1
Date
August 2024
Definition in file CartesianPolynomial2FisheyeOpenCV.cpp.
Function Documentation
main()
main ()
Main function of the sample program to convert a PeR camera model to another.
Main function of the sample program of the PeR io module.
Main function of the sample program to convert a PeR camera model set of distorsion parameters to another.
Example program's main function for converting a set of distortion parameters from a polynomial model to OpenCV's Fisheye model.
Main function of the sample program of the PeR core module.
Output the Fisheye OpenCV camera model computed from an prPolyCart TODO: load/save xml files
Output the omni camera model computed from an equidistant fisheye TODO: load/save xml files
Output the prPolyCart camera model computed from an omni TODO: load/save xml files
Perspective projection of a 3D point in a digital image plane
Output the Fisheye OpenCV camera model TODO: load/save xml files
Output the perspective camera model with distortions computed from another with more distortion parameters TODO: load/save xml files
Saving a stereovision system made of an omni cam and a perspective one to an XML file and load
Definition at line 25 of file CartesianPolynomial2FisheyeOpenCV.cpp.
References prCameraModelConvert::FCVreverseConvert(), prPolyCart::geta0(), prPolyCart::geta1(), prPolyCart::geta2(), prPolyCart::geta3(), prPolyCart::geta4(), prCameraModel::getau(), prCameraModel::getav(), prCameraModel::getk1(), prCameraModel::getk2(), prCameraModel::getk3(), prCameraModel::getk4(), prCameraModel::getName(), prCameraModel::getu0(), prCameraModel::getv0(), and prPolyCart::init().