PER: prEquirectangularXML Class Reference
prEquirectangularXML Class Reference
#include <prEquirectangularXML.h>
Public Member Functions
prEquirectangularXML (std::string fic)
virtual ~prEquirectangularXML () override=default
void operator<< (prEquirectangular &cam)
void operator>> (prEquirectangular &cam)
void operator<< (prCameraModel *cam)
void operator>> (prCameraModel *cam)
void xmlWriteToFile ()
Static Public Member Functions
static xmlNodePtr putModel (prCameraModel *)
static int getModel (xmlDocPtr &doc, xmlNodePtr node, prCameraModel *cam)
static int getModelType (xmlDocPtr &doc, xmlNodePtr node_model)
Protected Member Functions
int readModel (prCameraModel *cam)
void writeModel (prCameraModel *cam)
void xmlOpenToParse ()
void xmlOpenToWrite ()
void xmlEndAccessFile ()
void setPath (std::string nPath)
std::string getPath ()
Static Protected Member Functions
static void xmlReadCharChild (xmlDocPtr &doc, xmlNodePtr &node, char **res)
static void xmlReadDoubleChild (xmlDocPtr &, xmlNodePtr node, double &res)
static void xmlReadIntChild (xmlDocPtr &, xmlNodePtr &node, int &res)
static std::string xmlC2S (const xmlChar *str)
Protected Attributes
xmlNodePtr node
xmlDocPtr doc
std::string file
Detailed Description
Definition at line 20 of file prEquirectangularXML.h.
Constructor & Destructor Documentation
prEquirectangularXML()
prEquirectangularXML::prEquirectangularXML (std::string fic)
Constructor of a prEquirectangularXML object.
Parameters
fic the XML filename string
Definition at line 3 of file prEquirectangularXML.cpp.
~prEquirectangularXML()
virtual prEquirectangularXML::~prEquirectangularXML () override virtual default
Member Function Documentation
getModel()
int prCameraModelXML::getModel (xmlDocPtr & doc, xmlNodePtr node, prCameraModel * cam) static inherited
Gets parameters of the prX camera model cam from the XML tree node.
Parameters
doc the XML document smart pointer
node the XML node at which to read the prX camera model parameters
cam the prX camera model that holds the parameters to save
Returns
0 if runned fine
Definition at line 62 of file prCameraModelXML.cpp.
References prXML::doc, prCameraModel::init(), prIntensity< Ts, Tcam >::prIntensity(), prXML::xmlC2S(), prXML::xmlReadCharChild(), prXML::xmlReadDoubleChild(), and prXML::xmlReadIntChild().
Referenced by prCameraModelXML::readModel(), and prStereoModelXML::readSystem().
getModelType()
int prCameraModelXML::getModelType (xmlDocPtr & doc, xmlNodePtr node_model) static inherited
Gets the camera model type to know which prX camera model to allocate.
Parameters
doc the XML document smart pointer
node the XML node that holds the parameters to read
Returns
-1 if runned bad the camera type enum int otherwise
Definition at line 142 of file prCameraModelXML.cpp.
References prXML::doc, prXML::xmlC2S(), and prXML::xmlReadIntChild().
Referenced by prStereoModelXML::readSystem().
getPath()
std::string prXML::getPath () protected inherited
Gets the XML filename.
Returns
the XML filename string
Definition at line 38 of file prXML.cpp.
References prXML::file.
operator<<() [1/2]
void prCameraModelXML::operator<< (prCameraModel * cam) inherited
<< operator override for writing a prX camera model to a XML file
Parameters
cam the prX camera model to write
Returns
Nothing.
Definition at line 8 of file prCameraModelXML.cpp.
References prCameraModelXML::writeModel(), prXML::xmlEndAccessFile(), prXML::xmlOpenToWrite(), and prXML::xmlWriteToFile().
Referenced by operator<<(), and prPerspectiveXML::operator<<().
operator<<() [2/2]
void prEquirectangularXML::operator<< (prEquirectangular & cam)
<< operator override for writing a prEquirectangular camera model to a XML file
Parameters
cam the prEquirectangular camera model to write
Returns
Nothing.
Definition at line 8 of file prEquirectangularXML.cpp.
References prCameraModelXML::operator<<().
operator>>() [1/2]
void prCameraModelXML::operator>> (prCameraModel * cam) inherited
>> operator override for reading a prX camera model from a XML file
Parameters
cam the prX camera model that will hold the loaded parameters
Returns
Nothing.
Definition at line 16 of file prCameraModelXML.cpp.
References prCameraModelXML::readModel(), prXML::xmlEndAccessFile(), and prXML::xmlOpenToParse().
Referenced by operator>>(), and prPerspectiveXML::operator>>().
operator>>() [2/2]
void prEquirectangularXML::operator>> (prEquirectangular & cam)
>> operator override for reading a prEquirectangular camera model from a XML file
Parameters
cam the prEquirectangular camera model that will hold the loaded parameters
Returns
Nothing.
Definition at line 13 of file prEquirectangularXML.cpp.
References prCameraModelXML::operator>>().
putModel()
xmlNodePtr prCameraModelXML::putModel (prCameraModel * cam) static inherited
Insert the prX camera model parameters in the XML tree.
Parameters
cam the pointer to the prX camera model that holds the parameters to save
Returns
the smart pointer to the created XML node
Definition at line 23 of file prCameraModelXML.cpp.
References prCameraModel::getau(), prCameraModel::getav(), prCameraModel::getName(), prCameraModel::getType(), prCameraModel::getu0(), and prCameraModel::getv0().
Referenced by prOmniXML::putModel(), prStereoModelXML::putSystem(), and prCameraModelXML::writeModel().
readModel()
int prCameraModelXML::readModel (prCameraModel * cam) protected inherited
Reads a camera model from the XML tree and saves parameters in a prX camera model.
Parameters
cam the pointer to the last prX camera model (must be allocated before calling readModel) of the XML tree
Returns
the number of cameras in the XML tree
Definition at line 124 of file prCameraModelXML.cpp.
References prXML::doc, prCameraModelXML::getModel(), prXML::node, and prXML::xmlC2S().
Referenced by prCameraModelXML::operator>>().
setPath()
void prXML::setPath (std::string nPath) protected inherited
Sets the XML filename.
Parameters
nPath the XML filename string
Returns
Nothing
Definition at line 33 of file prXML.cpp.
References prXML::file.
Referenced by prXML::prXML().
writeModel()
void prCameraModelXML::writeModel (prCameraModel * cam) protected inherited
Writes a prX camera model to the XML tree.
Parameters
cam the pointer to the prX camera model to save
Returns
Nothing
Definition at line 119 of file prCameraModelXML.cpp.
References prXML::node, and prCameraModelXML::putModel().
Referenced by prCameraModelXML::operator<<().
xmlC2S()
std::string prXML::xmlC2S (const xmlChar * str) static protected inherited
Converts a characters string from the xmlChar type to the std::sting type.
Parameters
str the xmlChar type characters string
Returns
the converted string
Definition at line 89 of file prXML.cpp.
References prIntensity< Ts, Tcam >::prIntensity().
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), and prStereoModelXML::readSystem().
xmlEndAccessFile()
void prXML::xmlEndAccessFile () protected inherited
Close the XML file.
Returns
Nothing
Definition at line 49 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), prStereoModelXML::operator<<(), prStereoModelXML::operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), prStereoModelXML::operator>>(), and prStereoModelXML::operator>>().
xmlOpenToParse()
void prXML::xmlOpenToParse () protected inherited
Open the XML file for reading.
Returns
Nothing
Definition at line 14 of file prXML.cpp.
References prXML::doc, prXML::file, and prXML::node.
Referenced by prStereoModelXML::operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), prStereoModelXML::operator>>(), and prStereoModelXML::operator>>().
xmlOpenToWrite()
void prXML::xmlOpenToWrite () protected inherited
Open the XML file for writing.
Returns
Nothing
Definition at line 22 of file prXML.cpp.
References prXML::doc, prXML::file, and prXML::node.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and prStereoModelXML::operator<<().
xmlReadCharChild()
void prXML::xmlReadCharChild (xmlDocPtr & doc, xmlNodePtr & node, char ** res) static protected inherited
Reads the next child of a XML tree node of type char.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res a pointer to the array of char that will contain the reading as output
Returns
Nothing
Definition at line 53 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), and prOmniXML::getModel().
xmlReadDoubleChild()
void prXML::xmlReadDoubleChild (xmlDocPtr & doc, xmlNodePtr node, double & res) static protected inherited
Reads the next child of a XML tree node of type double.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the double variable that will contain the reading as output
Returns
Nothing
Definition at line 75 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), and prStereoModelXML::readSystem().
xmlReadIntChild()
void prXML::xmlReadIntChild (xmlDocPtr & doc, xmlNodePtr & node, int & res) static protected inherited
Reads the next child of a XML tree node of type int.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the int variable that will contain the reading as output
Returns
Nothing
Definition at line 61 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prStereoModelXML::readNbCams(), and prStereoModelXML::readSystem().
xmlWriteToFile()
void prXML::xmlWriteToFile () inherited
Effectively write the XML tree to a file.
Returns
the converted string
Definition at line 43 of file prXML.cpp.
References prXML::doc, and prXML::file.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and prStereoModelXML::operator<<().
Member Data Documentation
doc
xmlDocPtr prXML::doc protected inherited
Smart pointer to a XML document
Definition at line 28 of file prXML.h.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), prStereoModelXML::readSystem(), prXML::xmlEndAccessFile(), prXML::xmlOpenToParse(), prXML::xmlOpenToWrite(), prXML::xmlReadCharChild(), prXML::xmlReadDoubleChild(), prXML::xmlReadIntChild(), and prXML::xmlWriteToFile().
file
std::string prXML::file protected inherited
XML filename
Definition at line 29 of file prXML.h.
Referenced by prXML::getPath(), prXML::setPath(), prXML::xmlOpenToParse(), prXML::xmlOpenToWrite(), and prXML::xmlWriteToFile().
node
xmlNodePtr prXML::node protected inherited
Smart pointer to a XML tree node
Definition at line 27 of file prXML.h.
Referenced by prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), prStereoModelXML::readSystem(), prCameraModelXML::writeModel(), prStereoModelXML::writeSystem(), prXML::xmlOpenToParse(), and prXML::xmlOpenToWrite().