PER: prPhotometricGMS< Ts > Class Template Reference
prPhotometricGMS< Ts > Class Template Reference
#include <prPhotometricGMS.h>
Public Member Functions
prPhotometricGMS (float lambda_g=1.f, bool boundedGaussian_=false)
prPhotometricGMS (prPhotometricGMS< Ts > const &Src)
virtual ~prPhotometricGMS () override
void setLambda (float _lambda_g)
float getLambda () const
template<typename T , template< typename TT > class Tacquisition>
int cartesianBuildFrom (Tacquisition< T > &IS_req, Ts &_s_g, bool computePoseDerivatives=false)
template<typename T , template< typename TT > class Tacquisition>
int buildFrom (Tacquisition< T > &IS_req, Ts &_s_g, bool computePoseDerivatives=false, double rho=1., unsigned long sourceIndex=0)
template<typename T , template< typename TT > class Tacquisition>
int updateFrom (Tacquisition< T > &IS_req, bool computeFeatureDerivatives=false, unsigned long sourceIndex=0)
int getPoseJacobian (vpRowVector &Ls)
prPhotometricGMS< Ts > operator- (const prPhotometricGMS< Ts > &f)
prPhotometricGMS< Ts > operator* (const prPhotometricGMS< Ts > &f)
prPhotometricGMS< Ts > operator* (const double w)
prPhotometricGMS< Ts > & operator+= (const prPhotometricGMS< Ts > &f)
prPhotometricGMS< Ts > & operator= (const prPhotometricGMS< Ts > &f)
double getGMS () const
double * toDouble (unsigned int place=0)
Ts getS_g () const
template<typename T , template< typename TT > class Tacquisition>
int buildFromCam (prEquirectangular *equiCam, Tacquisition< T > &IS_req, Ts &_s_g, bool computePoseDerivatives=false, double rho=1., unsigned long sourceIndex=0)
template<typename T , template< typename TT > class Tacquisition>
int buildFromCam (prStereoModel *stereoCam, Tacquisition< T > &IS_req, Ts &_s_g, bool computePoseDerivatives=false, double rho=1., unsigned long sourceIndex=0)
void computePoseDerivative (vpRowVector &derivativeVec, double rho, bool computePoseDerivatives)
template<typename T >
double derivativeFilter (vpImage< T > &fr, int r, int c, int ****N)
prIntensity< Ts, Tcam > operator- (const prIntensity< Ts, Tcam > &f)
prIntensity< Ts, Tcam > operator* (const prIntensity< Ts, Tcam > &f)
prIntensity< Ts, Tcam > & operator+= (const prIntensity< Ts, Tcam > &f)
void setSensor (Tcam *camera_)
Public Attributes
float lambda_g
unsigned int indexU
unsigned int indexV
double IXs
double IYs
double IZs
std::vector< int ***** > neighborVec
Tcam * camera
prNeighborhood neighborhood
Protected Attributes
double * doubleFeature
Detailed Description
template<typename Ts>
class prPhotometricGMS< Ts >
Definition at line 23 of file prPhotometricGMS.h.
Constructor & Destructor Documentation
prPhotometricGMS() [1/2]
template<typename Ts > prPhotometricGMS< Ts >::prPhotometricGMS (float lambda_g = 1.f, bool boundedGaussian_ = false) inline
Definition at line 23 of file prPhotometricGMS.h.
References prIntensity< Ts, Tcam >::getGMS(), and prIntensity< Ts, Tcam >::getS_g().
prPhotometricGMS() [2/2]
template<typename Ts > prPhotometricGMS< Ts >::prPhotometricGMS< Ts > (prPhotometricGMS< Ts > const & Src) inline
Copy contructor of a prPhotometricGMS<Ts> photometric Gaussian mixture sample feature type.
Parameters
Src source object to copy
Definition at line 23 of file prPhotometricGMS.h.
~prPhotometricGMS()
template<typename Ts > prPhotometricGMS< Ts >::~prPhotometricGMS () inline override virtual
Destructor of a prPhotometricGMS photometric Gaussian mixture sample feature object.
Definition at line 51 of file prPhotometricGMS.h.
Member Function Documentation
buildFrom()
template<typename Ts > template<typename T , template< typename TT > class Tacquisition> int prPhotometricGMS< Ts >::buildFrom (Tacquisition< T > & IS_req, Ts & _s_g, bool computePoseDerivatives = false, double rho = 1., unsigned long sourceIndex = 0) inline
Computes the Gaussian mixture sample value from the set of all Gaussians (one for each "pixel") , considering a circle arch distance between samples, since they are lying on a spherical surface, and, optionally (iff computePoseDerivatives == true), computes the photometric Gms drivatives with respect to the 6 DOFs pose TODO: take degrees of freedom into account to save processing time TODO: take the "surface constraint" into account (the fact that, for spherical images, the point set is on a sphere, leads to distances computed on the sphere surface, not straight is space) ; a parameter of the mother class of prRegularlySampledCSImage ?..
Parameters
IS_req the input data from which to compute the Gaussian mixture sample value
_s_g the Gaussian mixture sample parameters (essentially, the location)
computePoseDerivatives boolean to let, if true, the method to compute the derivates with respect to the pose or not, if false
rho the distance of 3D point to the camera (1 by default if no 3D data is used)
Returns
0 if the computation succeeds
Definition at line 171 of file prPhotometricGMS.h.
buildFromCam() [1/2]
template<typename Ts , class Tcam > template<typename T , template< typename TT > class Tacquisition> int prIntensity< Ts, Tcam >::buildFromCam (prEquirectangular * equiCam, Tacquisition< T > & IS_req, Ts & _s_g, bool computePoseDerivatives = false, double rho = 1., unsigned long sourceIndex = 0) inline inherited
Definition at line 78 of file prIntensity.h.
References prIntensity< Ts, Tcam >::prIntensity().
buildFromCam() [2/2]
template<typename Ts , class Tcam > template<typename T , template< typename TT > class Tacquisition> int prIntensity< Ts, Tcam >::buildFromCam (prStereoModel * stereoCam, Tacquisition< T > & IS_req, Ts & _s_g, bool computePoseDerivatives = false, double rho = 1., unsigned long sourceIndex = 0) inline inherited
Definition at line 159 of file prIntensity.h.
cartesianBuildFrom()
template<typename Ts > template<typename T , template< typename TT > class Tacquisition> int prPhotometricGMS< Ts >::cartesianBuildFrom (Tacquisition< T > & IS_req, Ts & _s_g, bool computePoseDerivatives = false) inline
Computes the Gaussian mixture sample value from the set of all Gaussians (one for each "pixel") , considering a Cartesian straight distance between samples, and, optionally (iff computePoseDerivatives == true), computes the photometric Gms drivatives with respect to the 6 DOFs pose TODO: take degrees of freedom into account to save processing time TODO: take the "surface constraint" into account (the fact that, for spherical images, the point set is on a sphere, leads to distances computed on the sphere surface, not straight is space) ; a parameter of the mother class of prRegularlySampledCSImage ?..
Parameters
IS_req the input data from which to compute the Gaussian mixture sample value
_s_g the Gaussian mixture smaple parameters (essentially, the location)
computePoseDerivatives boolean to let, if true, the method to compute the derivates with respect to the pose or not, if false
Returns
0 if the computation succeeds
Definition at line 103 of file prPhotometricGMS.h.
computePoseDerivative()
template<typename Ts , class Tcam > void prIntensity< Ts, Tcam >::computePoseDerivative (vpRowVector & derivativeVec, double rho, bool computePoseDerivatives) inline inherited
Computes the photometric derivatives with respect to the 6 DOFs pose.
Parameters
derivativeVec the computed vector containing the derivatives of the spherical image along each direction
rho the distance of 3D point to the camera (1 by default if no 3D data is used)
computePoseDerivatives boolean to let, if true, the method to compute the derivates with respect to the pose or not, if false
Returns
0 if the computation succeeds
Definition at line 261 of file prIntensity.h.
derivativeFilter()
template<typename Ts , class Tcam > template<typename T > double prIntensity< Ts, Tcam >::derivativeFilter (vpImage< T > & fr, int r, int c, int **** N) inline inherited
Computes the derivative of a sample based on its neighbors \TODO: Take account of the image type, if unsigned char, divide by 255, else, already in the [0,1] interval so do nothing.
Parameters
fr The considered image whose derivative will be computed
r row index where to compute the derivative
c col index where to compute the derivative
N The neighboorhood already computed that gives the indexes of the neighbors used for the derivative computation
Returns
The derivative value of the image at a given index
Definition at line 327 of file prIntensity.h.
getGMS()
template<typename Ts > double prPhotometricGMS< Ts >::getGMS () const inline
Accessor to the Gms value.
Returns
the Gms value
Definition at line 426 of file prPhotometricGMS.h.
getLambda()
template<typename Ts > float prPhotometricGMS< Ts >::getLambda () const inline
Accessor tp the Gaussian spread parameter lambda_g.
Returns
the Gaussian spread parameter (\lambda_g)
Definition at line 87 of file prPhotometricGMS.h.
getPoseJacobian()
template<typename Ts > int prPhotometricGMS< Ts >::getPoseJacobian (vpRowVector & Ls) inline
Accessor to the pose Jacobian of the Gaussian mixture sample.
Parameters
Ls (output) the output row vector that receives the photometric Gms interaction matrix row
Returns
0 if the Jacobian could be get (if it was computed, actually) -1 if the Jacobian was not computed (no cannot be got)
Definition at line 313 of file prPhotometricGMS.h.
getS_g()
template<typename Ts > Ts prPhotometricGMS< Ts >::getS_g () const inline
Accessor to the Gaussian mixture sample location type parameter TODO: move in the mother class?
Returns
the Gms location
Definition at line 452 of file prPhotometricGMS.h.
operator*() [1/3]
template<typename Ts > prPhotometricGMS< Ts > prPhotometricGMS< Ts >::operator* (const double w) inline
operator override to multiply a Gms value with a scalar TODO : check line fOut.s_g = s_g * w;
Parameters
w the scalar to multiply with the Gms
Returns
the prPhotometricGMS<Ts> object resulting from the product with a scalar computation
Definition at line 365 of file prPhotometricGMS.h.
operator*() [2/3]
template<typename Ts , class Tcam > prIntensity< Ts, Tcam > prIntensity< Ts, Tcam >::operator* (const prIntensity< Ts, Tcam > & f) inline inherited
Definition at line 408 of file prIntensity.h.
References prIntensity< Ts, Tcam >::getGMS().
operator*() [3/3]
template<typename Ts > prPhotometricGMS< Ts > prPhotometricGMS< Ts >::operator* (const prPhotometricGMS< Ts > & f) inline
operator override to multiply two photometric Gms values TODO: check line fOut.s_g = s_g * f.s_g; TODO: move in the mother class?
Parameters
f the Gms to multiply with the current
Returns
the prPhotometricGMS<Ts> object resulting from the product computation
Definition at line 348 of file prPhotometricGMS.h.
References prIntensity< Ts, Tcam >::getGMS().
operator+=() [1/2]
template<typename Ts , class Tcam > prIntensity< Ts > & prIntensity< Ts, Tcam >::operator+= (const prIntensity< Ts, Tcam > & f) inline inherited
+= operator override to add two photometric values, updating the current one TODO : check line s_g += f.s_g;
Parameters
f the photometric to add to the current
Returns
the prIntensity<Ts> self reference object
Definition at line 440 of file prIntensity.h.
References prIntensity< Ts, Tcam >::getGMS().
operator+=() [2/2]
template<typename Ts > prPhotometricGMS< Ts > & prPhotometricGMS< Ts >::operator+= (const prPhotometricGMS< Ts > & f) inline
+= operator override to add two Gms values, updating the current one TODO : check line s_g += f.s_g;
Parameters
f the Gms to add to the current
Returns
the prPhotometricGMS<Ts> self reference object
Definition at line 382 of file prPhotometricGMS.h.
References prIntensity< Ts, Tcam >::getGMS().
operator-() [1/2]
template<typename Ts , class Tcam > prIntensity< Ts > prIntensity< Ts, Tcam >::operator- (const prIntensity< Ts, Tcam > & f) inline inherited
operator override to substract two photometric photometric values TODO : check line fOut.s_g = s_g - f.s_g;
Parameters
f the photometric to substract from the current
Returns
the prIntensity<Ts> object resulting from the difference computation
Definition at line 391 of file prIntensity.h.
References prIntensity< Ts, Tcam >::getGMS().
operator-() [2/2]
template<typename Ts > prPhotometricGMS< Ts > prPhotometricGMS< Ts >::operator- (const prPhotometricGMS< Ts > & f) inline
operator override to substract two photometric Gms values TODO : check line fOut.s_g = s_g - f.s_g;
Parameters
f the Gms to substract from the current
Returns
the prPhotometricGMS<Ts> object resulting from the difference computation
Definition at line 330 of file prPhotometricGMS.h.
References prIntensity< Ts, Tcam >::getGMS().
operator=()
template<typename Ts > prPhotometricGMS< Ts > & prPhotometricGMS< Ts >::operator= (const prPhotometricGMS< Ts > & f) inline
= operator override to copy Gms object
Parameters
f the Gms to copy to the current
Returns
the prPhotometricGMS<Ts> self reference object
Definition at line 396 of file prPhotometricGMS.h.
References prFeature::doubleFeature, prIntensity< Ts, Tcam >::getGMS(), and prIntensity< Ts, Tcam >::getS_g().
setLambda()
template<typename Ts > void prPhotometricGMS< Ts >::setLambda (float _lambda_g) inline
Sets the Gaussian spread parameter lambda_g and computes "constants" used from it.
Parameters
_lambda_g the Gaussian spread parameter
Returns
Nothing
Definition at line 62 of file prPhotometricGMS.h.
setSensor()
template<typename Ts , class Tcam > void prIntensity< Ts, Tcam >::setSensor (Tcam * camera_) inline inherited
Definition at line 523 of file prIntensity.h.
toDouble()
template<typename Ts > double * prPhotometricGMS< Ts >::toDouble (unsigned int place = 0) inline virtual
implementation of the toDouble method of the mother class converting the photometric Gms rich feature type to a common double value TODO: move in the mother class?
Parameters
place ?
Returns
the pointer to the double type vlaue of the Gms
Reimplemented from prIntensity< Ts, Tcam >.
Definition at line 435 of file prPhotometricGMS.h.
References prFeature::doubleFeature.
updateFrom()
template<typename Ts > template<typename T , template< typename TT > class Tacquisition> int prPhotometricGMS< Ts >::updateFrom (Tacquisition< T > & IS_req, bool computeFeatureDerivatives = false, unsigned long sourceIndex = 0) inline
Definition at line 294 of file prPhotometricGMS.h.
Member Data Documentation
camera
template<typename Ts , class Tcam > Tcam* prIntensity< Ts, Tcam >::camera inherited
Definition at line 531 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=(), and prIntensity< Ts, Tcam >::prIntensity().
doubleFeature
double* prFeature::doubleFeature protected inherited
Definition at line 43 of file prFeature.h.
Referenced by prIntensity< Ts, Tcam >::operator=(), prPhotometricGMS< Ts >::operator=(), prPhotometricnnGMS< Ts >::operator=(), prIntensity< Ts, Tcam >::toDouble(), prPhotometricGMS< Ts >::toDouble(), prPhotometricnnGMS< Ts >::toDouble(), and prFeature::~prFeature().
indexU
template<typename Ts , class Tcam > unsigned int prIntensity< Ts, Tcam >::indexU inherited
Definition at line 528 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
indexV
template<typename Ts , class Tcam > unsigned int prIntensity< Ts, Tcam >::indexV inherited
Definition at line 528 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
IXs
template<typename Ts , class Tcam > double prIntensity< Ts, Tcam >::IXs inherited
Definition at line 529 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
IYs
template<typename Ts , class Tcam > double prIntensity< Ts, Tcam >::IYs inherited
Definition at line 529 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
IZs
template<typename Ts , class Tcam > double prIntensity< Ts, Tcam >::IZs inherited
Definition at line 529 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
lambda_g
template<typename Ts , class Tcam = prCameraModel> float prGaussianMixtureSample< Ts, Tcam >::lambda_g inherited
Gaussian expansion parameter (\lambda_g)
Definition at line 42 of file prGaussianMixtureSample.h.
neighborhood
template<typename Ts , class Tcam > prNeighborhood prIntensity< Ts, Tcam >::neighborhood inherited
Definition at line 532 of file prIntensity.h.
neighborVec
template<typename Ts , class Tcam > std::vector<int *****> prIntensity< Ts, Tcam >::neighborVec inherited
Definition at line 530 of file prIntensity.h.