PER: prStereoModelXML Class Reference
prStereoModelXML Class Reference
#include <prStereoModelXML.h>
Public Member Functions
prStereoModelXML (std::string fic)
virtual ~prStereoModelXML () override=default
void operator<< (prStereoModel &rig)
void operator>> (std::vector< CameraModelType > &v_sensors)
void operator>> (int &nbSensors)
void operator>> (prStereoModel &rig)
void xmlWriteToFile ()
Protected Member Functions
xmlNodePtr putSystem (prStereoModel &rig)
int getSystem (xmlNodePtr node, prStereoModel &rig)
int readSystem (prStereoModel &rig)
int readNbCams (int &nbSensors)
int readCameraTypes (std::vector< CameraModelType > &v_sensorTypes)
void writeSystem (prStereoModel &rig)
void xmlOpenToParse ()
void xmlOpenToWrite ()
void xmlEndAccessFile ()
void setPath (std::string nPath)
std::string getPath ()
Static Protected Member Functions
static void xmlReadCharChild (xmlDocPtr &doc, xmlNodePtr &node, char **res)
static void xmlReadDoubleChild (xmlDocPtr &, xmlNodePtr node, double &res)
static void xmlReadIntChild (xmlDocPtr &, xmlNodePtr &node, int &res)
static std::string xmlC2S (const xmlChar *str)
Protected Attributes
xmlNodePtr node
xmlDocPtr doc
std::string file
Detailed Description
Definition at line 33 of file prStereoModelXML.h.
Constructor & Destructor Documentation
prStereoModelXML()
prStereoModelXML::prStereoModelXML (std::string fic)
Constructor of a prStereoModelXML object.
Parameters
fic the XML filename string
Definition at line 7 of file prStereoModelXML.cpp.
~prStereoModelXML()
virtual prStereoModelXML::~prStereoModelXML () override virtual default
Member Function Documentation
getPath()
std::string prXML::getPath () protected inherited
Gets the XML filename.
Returns
the XML filename string
Definition at line 38 of file prXML.cpp.
References prXML::file.
getSystem()
int prStereoModelXML::getSystem (xmlNodePtr node, prStereoModel & rig) protected
Definition at line 118 of file prStereoModelXML.cpp.
operator<<()
void prStereoModelXML::operator<< (prStereoModel & rig)
<< operator override for writing a prStereoModel sensors rig to a XML file
Parameters
rig the prStereoModel sensors rig to write
Returns
Nothing.
Definition at line 12 of file prStereoModelXML.cpp.
References writeSystem(), prXML::xmlEndAccessFile(), prXML::xmlOpenToWrite(), and prXML::xmlWriteToFile().
operator>>() [1/3]
void prStereoModelXML::operator>> (int & nbSensors)
>> operator override for reading the number of sensors in the rig described in the XML file
Parameters
nbSensors the number of sensors
Returns
Nothing.
Definition at line 34 of file prStereoModelXML.cpp.
References readNbCams(), prXML::xmlEndAccessFile(), and prXML::xmlOpenToParse().
operator>>() [2/3]
void prStereoModelXML::operator>> (prStereoModel & rig)
>> operator override for reading a prStereoModel sensors rig from a XML file
Parameters
rig the prStereoModel sensors rig that will hold the loaded parameters
Returns
Nothing.
Definition at line 20 of file prStereoModelXML.cpp.
References readSystem(), prXML::xmlEndAccessFile(), and prXML::xmlOpenToParse().
operator>>() [3/3]
void prStereoModelXML::operator>> (std::vector< CameraModelType > & v_sensors)
>> operator override for reading the types of sensors constituting the rig described in the XML file
Parameters
v_sensors the std::vector of sensor types
Returns
Nothing.
Definition at line 27 of file prStereoModelXML.cpp.
References readCameraTypes(), prXML::xmlEndAccessFile(), and prXML::xmlOpenToParse().
putSystem()
xmlNodePtr prStereoModelXML::putSystem (prStereoModel & rig) protected
Insert the prStereoModel sensor rig parameters in the XML tree.
Parameters
rig the prStereoModel sensor rig that holds the parameters to save
Returns
the smart pointer to the created XML node
Definition at line 41 of file prStereoModelXML.cpp.
References prIntensity< Ts, Tcam >::prIntensity(), prCameraModelXML::putModel(), and prOmniXML::putModel().
Referenced by writeSystem().
readCameraTypes()
int prStereoModelXML::readCameraTypes (std::vector< CameraModelType > & v_sensorTypes) protected
Reads the types of sensors in the stereo rig described in the XML file.
Parameters
v_sensorTypes output variable that will contain the types of sensors in the rig
Returns
0 if runned fine -1 if there is not any stereo rig in the XML file -2 if the number of sensors is not defined in the XML file
Definition at line 208 of file prStereoModelXML.cpp.
References prXML::doc, prXML::node, prXML::xmlC2S(), and prXML::xmlReadIntChild().
Referenced by operator>>().
readNbCams()
int prStereoModelXML::readNbCams (int & nbSensors) protected
Reads the number of cameras in the stereo rig described in the XML file.
Parameters
nbSensors output variable that will contain the number of sensors in the rig
Returns
0 if runned fine -1 if there is not any stereo rig in the XML file -2 if the number of sensors is not defined in the XML file
Definition at line 180 of file prStereoModelXML.cpp.
References prXML::doc, prXML::node, prXML::xmlC2S(), and prXML::xmlReadIntChild().
Referenced by operator>>().
readSystem()
int prStereoModelXML::readSystem (prStereoModel & rig) protected
Definition at line 265 of file prStereoModelXML.cpp.
References prIntensity< Ts, Tcam >::buildFrom(), prXML::doc, prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prXML::node, prIntensity< Ts, Tcam >::prIntensity(), prXML::xmlC2S(), prXML::xmlReadDoubleChild(), and prXML::xmlReadIntChild().
Referenced by operator>>().
setPath()
void prXML::setPath (std::string nPath) protected inherited
Sets the XML filename.
Parameters
nPath the XML filename string
Returns
Nothing
Definition at line 33 of file prXML.cpp.
References prXML::file.
Referenced by prXML::prXML().
writeSystem()
void prStereoModelXML::writeSystem (prStereoModel & rig) protected
Writes a prStereoModel sensors rig to the XML tree.
Parameters
rig the prStereoModel sensors rig to save
Returns
Nothing
Definition at line 175 of file prStereoModelXML.cpp.
References prXML::node, and putSystem().
Referenced by operator<<().
xmlC2S()
std::string prXML::xmlC2S (const xmlChar * str) static protected inherited
Converts a characters string from the xmlChar type to the std::sting type.
Parameters
str the xmlChar type characters string
Returns
the converted string
Definition at line 89 of file prXML.cpp.
References prIntensity< Ts, Tcam >::prIntensity().
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), readCameraTypes(), prCameraModelXML::readModel(), readNbCams(), and readSystem().
xmlEndAccessFile()
void prXML::xmlEndAccessFile () protected inherited
Close the XML file.
Returns
Nothing
Definition at line 49 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), operator<<(), operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), operator>>(), and operator>>().
xmlOpenToParse()
void prXML::xmlOpenToParse () protected inherited
Open the XML file for reading.
Returns
Nothing
Definition at line 14 of file prXML.cpp.
References prXML::doc, prXML::file, and prXML::node.
Referenced by operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), operator>>(), and operator>>().
xmlOpenToWrite()
void prXML::xmlOpenToWrite () protected inherited
Open the XML file for writing.
Returns
Nothing
Definition at line 22 of file prXML.cpp.
References prXML::doc, prXML::file, and prXML::node.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and operator<<().
xmlReadCharChild()
void prXML::xmlReadCharChild (xmlDocPtr & doc, xmlNodePtr & node, char ** res) static protected inherited
Reads the next child of a XML tree node of type char.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res a pointer to the array of char that will contain the reading as output
Returns
Nothing
Definition at line 53 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), and prOmniXML::getModel().
xmlReadDoubleChild()
void prXML::xmlReadDoubleChild (xmlDocPtr & doc, xmlNodePtr node, double & res) static protected inherited
Reads the next child of a XML tree node of type double.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the double variable that will contain the reading as output
Returns
Nothing
Definition at line 75 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), and readSystem().
xmlReadIntChild()
void prXML::xmlReadIntChild (xmlDocPtr & doc, xmlNodePtr & node, int & res) static protected inherited
Reads the next child of a XML tree node of type int.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the int variable that will contain the reading as output
Returns
Nothing
Definition at line 61 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), readCameraTypes(), readNbCams(), and readSystem().
xmlWriteToFile()
void prXML::xmlWriteToFile () inherited
Effectively write the XML tree to a file.
Returns
the converted string
Definition at line 43 of file prXML.cpp.
References prXML::doc, and prXML::file.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and operator<<().
Member Data Documentation
doc
xmlDocPtr prXML::doc protected inherited
Smart pointer to a XML document
Definition at line 28 of file prXML.h.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), readCameraTypes(), prCameraModelXML::readModel(), readNbCams(), readSystem(), prXML::xmlEndAccessFile(), prXML::xmlOpenToParse(), prXML::xmlOpenToWrite(), prXML::xmlReadCharChild(), prXML::xmlReadDoubleChild(), prXML::xmlReadIntChild(), and prXML::xmlWriteToFile().
file
std::string prXML::file protected inherited
XML filename
Definition at line 29 of file prXML.h.
Referenced by prXML::getPath(), prXML::setPath(), prXML::xmlOpenToParse(), prXML::xmlOpenToWrite(), and prXML::xmlWriteToFile().
node
xmlNodePtr prXML::node protected inherited
Smart pointer to a XML tree node
Definition at line 27 of file prXML.h.
Referenced by prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), readCameraTypes(), prCameraModelXML::readModel(), readNbCams(), readSystem(), prCameraModelXML::writeModel(), writeSystem(), prXML::xmlOpenToParse(), and prXML::xmlOpenToWrite().