PER: prXML Class Reference
prXML Class Reference
#include <prXML.h>
Public Member Functions
void xmlWriteToFile ()
virtual ~prXML () override=default
Public Member Functions inherited from prIo
virtual ~prIo ()=default
Protected Member Functions
prXML (std::string ficIn)
prXML ()
void xmlOpenToParse ()
void xmlOpenToWrite ()
void xmlEndAccessFile ()
void setPath (std::string nPath)
std::string getPath ()
Static Protected Member Functions
static void xmlReadCharChild (xmlDocPtr &doc, xmlNodePtr &node, char **res)
static void xmlReadDoubleChild (xmlDocPtr &, xmlNodePtr node, double &res)
static void xmlReadIntChild (xmlDocPtr &, xmlNodePtr &node, int &res)
static std::string xmlC2S (const xmlChar *str)
Protected Attributes
xmlNodePtr node
xmlDocPtr doc
std::string file
Detailed Description
Definition at line 25 of file prXML.h.
Constructor & Destructor Documentation
prXML() [1/2]
prXML::prXML (std::string ficIn) protected
Constructor of a prXML object.
Parameters
ficIn the XML filename string
Definition at line 8 of file prXML.cpp.
References setPath().
prXML() [2/2]
prXML::prXML () protected
Default constructor of a prXML object.
Definition at line 3 of file prXML.cpp.
~prXML()
virtual prXML::~prXML () override virtual default
Member Function Documentation
getPath()
std::string prXML::getPath () protected
Gets the XML filename.
Returns
the XML filename string
Definition at line 38 of file prXML.cpp.
References file.
setPath()
void prXML::setPath (std::string nPath) protected
Sets the XML filename.
Parameters
nPath the XML filename string
Returns
Nothing
Definition at line 33 of file prXML.cpp.
References file.
Referenced by prXML().
xmlC2S()
std::string prXML::xmlC2S (const xmlChar * str) static protected
Converts a characters string from the xmlChar type to the std::sting type.
Parameters
str the xmlChar type characters string
Returns
the converted string
Definition at line 89 of file prXML.cpp.
References prIntensity< Ts, Tcam >::prIntensity().
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), and prStereoModelXML::readSystem().
xmlEndAccessFile()
void prXML::xmlEndAccessFile () protected
Close the XML file.
Returns
Nothing
Definition at line 49 of file prXML.cpp.
References doc.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), prStereoModelXML::operator<<(), prStereoModelXML::operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), prStereoModelXML::operator>>(), and prStereoModelXML::operator>>().
xmlOpenToParse()
void prXML::xmlOpenToParse () protected
Open the XML file for reading.
Returns
Nothing
Definition at line 14 of file prXML.cpp.
References doc, file, and node.
Referenced by prStereoModelXML::operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), prStereoModelXML::operator>>(), and prStereoModelXML::operator>>().
xmlOpenToWrite()
void prXML::xmlOpenToWrite () protected
Open the XML file for writing.
Returns
Nothing
Definition at line 22 of file prXML.cpp.
References doc, file, LABEL_XML_ROOT, and node.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and prStereoModelXML::operator<<().
xmlReadCharChild()
void prXML::xmlReadCharChild (xmlDocPtr & doc, xmlNodePtr & node, char ** res) static protected
Reads the next child of a XML tree node of type char.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res a pointer to the array of char that will contain the reading as output
Returns
Nothing
Definition at line 53 of file prXML.cpp.
References doc.
Referenced by prCameraModelXML::getModel(), and prOmniXML::getModel().
xmlReadDoubleChild()
void prXML::xmlReadDoubleChild (xmlDocPtr & doc, xmlNodePtr node, double & res) static protected
Reads the next child of a XML tree node of type double.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the double variable that will contain the reading as output
Returns
Nothing
Definition at line 75 of file prXML.cpp.
References doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), and prStereoModelXML::readSystem().
xmlReadIntChild()
void prXML::xmlReadIntChild (xmlDocPtr & doc, xmlNodePtr & node, int & res) static protected
Reads the next child of a XML tree node of type int.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the int variable that will contain the reading as output
Returns
Nothing
Definition at line 61 of file prXML.cpp.
References doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prStereoModelXML::readNbCams(), and prStereoModelXML::readSystem().
xmlWriteToFile()
void prXML::xmlWriteToFile ()
Effectively write the XML tree to a file.
Returns
the converted string
Definition at line 43 of file prXML.cpp.
References doc, and file.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and prStereoModelXML::operator<<().
Member Data Documentation
doc
xmlDocPtr prXML::doc protected
Smart pointer to a XML document
Definition at line 28 of file prXML.h.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), prStereoModelXML::readSystem(), xmlEndAccessFile(), xmlOpenToParse(), xmlOpenToWrite(), xmlReadCharChild(), xmlReadDoubleChild(), xmlReadIntChild(), and xmlWriteToFile().
file
std::string prXML::file protected
XML filename
Definition at line 29 of file prXML.h.
Referenced by getPath(), setPath(), xmlOpenToParse(), xmlOpenToWrite(), and xmlWriteToFile().
node
xmlNodePtr prXML::node protected
Smart pointer to a XML tree node
Definition at line 27 of file prXML.h.
Referenced by prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), prStereoModelXML::readSystem(), prCameraModelXML::writeModel(), prStereoModelXML::writeSystem(), xmlOpenToParse(), and xmlOpenToWrite().
The documentation for this class was generated from the following files:
libPeR_base/modules/io/include/per/io/prXML.h
libPeR_base/modules/io/src/prXML.cpp