PER: prPointFeature Class Reference
prPointFeature Class Reference
#include <prPointFeature.h>
Public Member Functions
prPointFeature ()
virtual ~prPointFeature () override=default
double get_u () const
double get_v () const
void set_u (const double _u)
void set_v (const double _v)
void set_X (const double X_)
void set_Y (const double Y_)
void set_Z (const double Z_)
void set_W (const double W_)
void set_oX (const double X_)
void set_oY (const double Y_)
void set_oZ (const double Z_)
void set_oW (const double W_)
double get_X () const
double get_Y () const
double get_Z () const
double get_W () const
double get_oX () const
double get_oY () const
double get_oZ () const
double get_oW () const
void set_x (const double x_)
void set_y (const double y_)
void set_w (const double w_)
double get_x () const
double get_y () const
double get_w () const
void setWorldCoordinates (const double oX, const double oY, const double oZ)
int setWorldCoordinates (const prCartesian3DPointVec &_wX)
void getWorldCoordinates (double &oX, double &oY, double &oZ)
void getWorldCoordinates (prCartesian3DPointVec &_xW)
prCartesian3DPointVec getWorldCoordinates (void)
void changeFrame (const vpHomogeneousMatrix &sMw, prCartesian3DPointVec &_sX)
void changeFrame (const vpHomogeneousMatrix &sMw)
void getImageMetric (double &x, double &y, double &w) const
void setImageMetric (const double x, const double y, const double w)
void getPixUV (double &u, double &v) const
void setPixUV (const double u, const double v)
void setObjectPixUV (const double oX, const double oY, const double oZ, const double u, const double v)
prPointFeature & operator= (const prPointFeature &Point)
double * toDouble (unsigned int place=0)
Public Attributes
prCartesian3DPointVec wX
prCartesian3DPointVec sX
prCartesian3DPointVec ix
prCartesian2DPointVec x
prCartesian2DPointVec u
Protected Attributes
double * doubleFeature
Detailed Description
Definition at line 24 of file prPointFeature.h.
Constructor & Destructor Documentation
prPointFeature()
prPointFeature::prPointFeature ()
Default constructor of a prPointFeature object.
Definition at line 4 of file prPointFeature.cpp.
~prPointFeature()
prPointFeature::~prPointFeature () override virtual default
Default destructor of a prPointFeature object.
Member Function Documentation
changeFrame() [1/2]
void prPointFeature::changeFrame (const vpHomogeneousMatrix & sMw) inline
Computes and update the coordinates of the internal 3D point expressed in the camera frame from the internal 3D point expressed in the world frame thanks to the sMw frame change.
Parameters
sMw frame change from the world to the sensor frame
Returns
Nothing
Definition at line 297 of file prPointFeature.h.
References prCartesian3DPointVec::changeFrame().
changeFrame() [2/2]
void prPointFeature::changeFrame (const vpHomogeneousMatrix & sMw, prCartesian3DPointVec & _sX)
Computes and outputs the coordinates of the 3D point in the camera frame sX from the internal 3D point expressed in the world frame thanks to the cMo frame change.
Compute the new 3D coordinates of the point in the new camera frame.
Parameters
sMw frame change from the world to the sensor frame
_sX the output 4-vector containting the 3D point coordinates in the camera frame
Returns
Nothing
Definition at line 57 of file prPointFeature.cpp.
References prCartesian3DPointVec::changeFrame(), and wX.
get_oW()
double prPointFeature::get_oW () const inline
Accessor to the W coordinate of the 3D point expressed in the sensor frame (generally set to 1, its default value for a Cartesian point)
Returns
oW
Definition at line 184 of file prPointFeature.h.
References prCartesian3DPointVec::get_W().
get_oX()
double prPointFeature::get_oX () const inline
Accessor to the X coordinate of the 3D point expressed in the world frame.
Returns
oX
Definition at line 163 of file prPointFeature.h.
References prCartesian3DPointVec::get_X().
Referenced by operator=().
get_oY()
double prPointFeature::get_oY () const inline
Accessor to the Y coordinate of the 3D point expressed in the world frame.
Returns
oY
Definition at line 170 of file prPointFeature.h.
References prCartesian3DPointVec::get_Y().
Referenced by operator=().
get_oZ()
double prPointFeature::get_oZ () const inline
Accessor to the Z coordinate of the 3D point expressed in the world frame.
Returns
oZ
Definition at line 177 of file prPointFeature.h.
References prCartesian3DPointVec::get_Z().
Referenced by operator=().
get_u()
double prPointFeature::get_u () const inline
Accessor to the horizontal coordinate u of the point in the digital image plane.
Returns
u
Definition at line 46 of file prPointFeature.h.
References prCartesian2DPointVec::get_x().
Referenced by prRegularlySampledCSImage< T >::buildFromEquiRect(), prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), prRegularlySampledCSImage< T >::buildFromTwinOmni(), prCameraModelConvert::convert(), prCameraModelConvert::convert_distortions(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), prCameraModelConvert::FCVreverseConvert(), getPixUV(), prCameraModelConvert::KBreverseConvert(), operator=(), prCameraModel::pixelMeterConversion(), prPolyCart::projectImageSphere(), prRegularlySampledCSImage< T >::toEquiRect(), prRegularlySampledCSImageDepth< TImage >::toEquiRect(), and prRegularlySampledCSImage< T >::toTwinOmni().
get_v()
double prPointFeature::get_v () const inline
Accessor to the vertical coordinate v of the point in the digital image plane.
Returns
v
Definition at line 53 of file prPointFeature.h.
References prCartesian2DPointVec::get_y().
Referenced by prRegularlySampledCSImage< T >::buildFromEquiRect(), prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), prRegularlySampledCSImage< T >::buildFromTwinOmni(), prCameraModelConvert::conversion(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), getPixUV(), operator=(), prCameraModel::pixelMeterConversion(), prPolyCart::projectImageSphere(), prRegularlySampledCSImage< T >::toEquiRect(), prRegularlySampledCSImageDepth< TImage >::toEquiRect(), and prRegularlySampledCSImage< T >::toTwinOmni().
get_W()
double prPointFeature::get_W () const inline
Accessor to the W coordinate of the 3D point expressed in the sensor frame (generally set to 1, its default value for a Cartesian point)
Returns
W
Definition at line 155 of file prPointFeature.h.
References prCartesian3DPointVec::get_W().
get_w()
double prPointFeature::get_w () const inline
Accessor to the homogeneous coordinate w in the normalized image planee (generally set to 1, its default value for a Cartesian point)
Returns
x
Definition at line 231 of file prPointFeature.h.
References prCartesian2DPointVec::get_w().
Referenced by getImageMetric().
get_X()
double prPointFeature::get_X () const inline
Accessor to the X coordinate of the 3D point expressed in the sensor frame.
Returns
X
Definition at line 134 of file prPointFeature.h.
References prCartesian3DPointVec::get_X().
Referenced by prEquirectangular::computeSensorJacobian(), prOmni::computeSensorJacobian(), operator=(), prEquirectangular::project3DImage(), prFisheyeEquidistant::project3DImage(), prFisheyeEquisolid::project3DImage(), prOmni::project3DImage(), prParaboloid::project3DImage(), prPerspective::project3DImage(), prParaboloid::project3DMiroir(), prEquirectangular::project3DSphere(), prFisheyeEquidistant::project3DSphere(), prFisheyeEquisolid::project3DSphere(), prOmni::project3DSphere(), prPerspective::project3DSphere(), and prPolyCart::project3DSphere().
get_x()
double prPointFeature::get_x () const inline
Accessor to the horizontal coordinate x in the normalized image plane.
Returns
x
Definition at line 217 of file prPointFeature.h.
References prCartesian2DPointVec::get_x().
Referenced by prOmni::computeSensorJacobian(), prPerspective::computeSensorJacobian(), prCameraModelConvert::conversion(), prCameraModelConvert::convert(), getImageMetric(), prCameraModel::meterPixelConversion(), operator=(), prParaboloid::projectImageMiroir(), prEquirectangular::projectImageSphere(), prOmni::projectImageSphere(), and prPerspective::unProject().
get_Y()
double prPointFeature::get_Y () const inline
Accessor to the Y coordinate of the 3D point expressed in the sensor frame.
Returns
Y
Definition at line 141 of file prPointFeature.h.
References prCartesian3DPointVec::get_Y().
Referenced by prEquirectangular::computeSensorJacobian(), prOmni::computeSensorJacobian(), operator=(), prEquirectangular::project3DImage(), prFisheyeEquidistant::project3DImage(), prFisheyeEquisolid::project3DImage(), prOmni::project3DImage(), prParaboloid::project3DImage(), prPerspective::project3DImage(), prParaboloid::project3DMiroir(), prEquirectangular::project3DSphere(), prFisheyeEquidistant::project3DSphere(), prFisheyeEquisolid::project3DSphere(), prOmni::project3DSphere(), prPerspective::project3DSphere(), and prPolyCart::project3DSphere().
get_y()
double prPointFeature::get_y () const inline
Accessor to the vertical coordinate y in the normalized image plane.
Returns
y
Definition at line 224 of file prPointFeature.h.
References prCartesian2DPointVec::get_y().
Referenced by prOmni::computeSensorJacobian(), prPerspective::computeSensorJacobian(), prCameraModelConvert::conversion(), getImageMetric(), prCameraModel::meterPixelConversion(), operator=(), prParaboloid::projectImageMiroir(), prEquirectangular::projectImageSphere(), prOmni::projectImageSphere(), and prPerspective::unProject().
get_Z()
double prPointFeature::get_Z () const inline
Accessor to the Z coordinate of the 3D point expressed in the sensor frame.
Returns
Z
Definition at line 148 of file prPointFeature.h.
References prCartesian3DPointVec::get_Z().
Referenced by prRegularlySampledCSImage< T >::buildFromTwinOmni(), prEquirectangular::computeSensorJacobian(), prOmni::computeSensorJacobian(), prPerspective::computeSensorJacobian(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), operator=(), prEquirectangular::project3DImage(), prFisheyeEquidistant::project3DImage(), prFisheyeEquisolid::project3DImage(), prOmni::project3DImage(), prParaboloid::project3DImage(), prPerspective::project3DImage(), prParaboloid::project3DMiroir(), prEquirectangular::project3DSphere(), prFisheyeEquidistant::project3DSphere(), prFisheyeEquisolid::project3DSphere(), prOmni::project3DSphere(), prPerspective::project3DSphere(), prPolyCart::project3DSphere(), and prRegularlySampledCSImage< T >::toTwinOmni().
getImageMetric()
void prPointFeature::getImageMetric (double & x, double & y, double & w) const
Gets the normalized image plane point coordinates.
Parameters
x the horizontal coordinate of the 2D point expressed in the normalized image plane (output)
y the vertical coordinate of the 2D point expressed in the normalized image plane (output)
w the homogeneous coordinate of the 2D point expressed in the normalized image plane, generally equal to 1 for a Cartesian point (output)
Returns
Nothing
Definition at line 62 of file prPointFeature.cpp.
References get_w(), get_x(), get_y(), and x.
getPixUV()
void prPointFeature::getPixUV (double & u, double & v) const
Gets the digital image plane point coordinates.
Parameters
u the horizontal coordinate of the 2D point expressed in the digital image plane (output)
v the vertical coordinate of the 2D point expressed in the digital image plane (output)
Returns
Nothing
Definition at line 76 of file prPointFeature.cpp.
References get_u(), and get_v().
getWorldCoordinates() [1/3]
void prPointFeature::getWorldCoordinates (double & ox, double & oy, double & oz)
Gets the world coordinates of the 3D point.
Parameters
oX the X coordinate of the 3D point expressed in the world frame (output)
oY the Y coordinate of the 3D point expressed in the world frame (output)
oZ the Z coordinate of the 3D point expressed in the world frame (output)
Returns
Nothing
Definition at line 32 of file prPointFeature.cpp.
References prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), and wX.
getWorldCoordinates() [2/3]
void prPointFeature::getWorldCoordinates (prCartesian3DPointVec & _xW)
Definition at line 43 of file prPointFeature.cpp.
References prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), prCartesian3DPointVec::setPoint(), and wX.
getWorldCoordinates() [3/3]
prCartesian3DPointVec prPointFeature::getWorldCoordinates (void)
Gets the world coordinates of the 3D point.
Returns
a 4-vector containing the X, Y, Z and W coordinates of the 3D point expressed in the world frame
Definition at line 50 of file prPointFeature.cpp.
References wX.
operator=()
prPointFeature & prPointFeature::operator= (const prPointFeature & Point)
= operator overload for copying a prPointFeature
Parameters
Point the source prPointFeature
Returns
the affected prPointFeature.
Definition at line 96 of file prPointFeature.cpp.
References get_oX(), get_oY(), get_oZ(), get_u(), get_v(), get_X(), get_x(), get_Y(), get_y(), get_Z(), set_oX(), set_oY(), set_oZ(), set_u(), set_v(), set_X(), set_x(), set_Y(), set_y(), and set_Z().
set_oW()
void prPointFeature::set_oW (const double W_) inline
Sets the W coordinate of the 3D point expressed in the world frame (generally set to 1, its default value for a Cartesian point)
Returns
Nothing
Definition at line 126 of file prPointFeature.h.
References prCartesian3DPointVec::set_W().
set_oX()
void prPointFeature::set_oX (const double X_) inline
Sets the X coordinate of the 3D point expressed in the world frame.
Returns
Nothing
Definition at line 105 of file prPointFeature.h.
References prCartesian3DPointVec::set_X().
Referenced by operator=(), and setObjectPixUV().
set_oY()
void prPointFeature::set_oY (const double Y_) inline
Sets the Y coordinate of the 3D point expressed in the world frame.
Returns
Nothing
Definition at line 112 of file prPointFeature.h.
References prCartesian3DPointVec::set_Y().
Referenced by operator=(), and setObjectPixUV().
set_oZ()
void prPointFeature::set_oZ (const double Z_) inline
Sets the Z coordinate of the 3D point expressed in the world frame.
Returns
Nothing
Definition at line 119 of file prPointFeature.h.
References prCartesian3DPointVec::set_Z().
Referenced by operator=(), and setObjectPixUV().
set_u()
void prPointFeature::set_u (const double _u) inline
Sets the horizontal coordinate u of the point in the digital image plane.
Returns
Nothing
Definition at line 61 of file prPointFeature.h.
References prCartesian2DPointVec::set_x().
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::FCVreverseConvert(), prCameraModelConvert::KBreverseConvert(), prCameraModel::meterPixelConversion(), operator=(), and setPixUV().
set_v()
void prPointFeature::set_v (const double _v) inline
Sets the vertical coordinate v of the point in the digital image plane.
Returns
Nothing
Definition at line 68 of file prPointFeature.h.
References prCartesian2DPointVec::set_y().
Referenced by prCameraModelConvert::conversion(), prCameraModel::meterPixelConversion(), operator=(), and setPixUV().
set_W()
void prPointFeature::set_W (const double W_) inline
Sets the W coordinate of the 3D point expressed in the sensor frame (generally set to 1, its default value for a Cartesian point)
Returns
Nothing
Definition at line 97 of file prPointFeature.h.
References prCartesian3DPointVec::set_W().
set_w()
void prPointFeature::set_w (const double w) inline
Sets the w coordinate of the point expressed in the normalized image plane.
Parameters
w the homogeneous coordinate in the normalized image plane (generally set to 1, its default value for a Cartesian point)
Returns
Nothing
Definition at line 209 of file prPointFeature.h.
References prCartesian2DPointVec::set_w().
Referenced by prPerspective::project3DImage(), and setImageMetric().
set_X()
void prPointFeature::set_X (const double X_) inline
Sets the X coordinate of the 3D point expressed in the sensor frame.
Returns
Nothing
Definition at line 76 of file prPointFeature.h.
References prCartesian3DPointVec::set_X().
Referenced by prCameraModelConvert::convert(), prCameraModelConvert::convert(), operator=(), prEquirectangular::unProject(), prOmni::unProject(), and prPerspective::unProject().
set_x()
void prPointFeature::set_x (const double x) inline
Sets the x coordinate of the point expressed in the normalized image plane.
Parameters
x the horizontal coordinate in the normalized image plane
Returns
Nothing
Definition at line 193 of file prPointFeature.h.
References prCartesian2DPointVec::set_x().
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), operator=(), prCameraModel::pixelMeterConversion(), prEquirectangular::project3DImage(), prFisheyeEquidistant::project3DImage(), prFisheyeEquisolid::project3DImage(), prOmni::project3DImage(), prParaboloid::project3DImage(), prPerspective::project3DImage(), and setImageMetric().
set_Y()
void prPointFeature::set_Y (const double Y_) inline
Sets the Y coordinate of the 3D point expressed in the sensor frame.
Returns
Nothing
Definition at line 83 of file prPointFeature.h.
References prCartesian3DPointVec::set_Y().
Referenced by prCameraModelConvert::convert(), prCameraModelConvert::convert(), operator=(), prEquirectangular::unProject(), prOmni::unProject(), and prPerspective::unProject().
set_y()
void prPointFeature::set_y (const double y) inline
Sets the y coordinate of the point expressed in the normalized image plane.
Parameters
y the vertical coordinate in the normalized image plane
Returns
Nothing
Definition at line 201 of file prPointFeature.h.
References prCartesian2DPointVec::set_y().
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), operator=(), prCameraModel::pixelMeterConversion(), prEquirectangular::project3DImage(), prFisheyeEquidistant::project3DImage(), prFisheyeEquisolid::project3DImage(), prOmni::project3DImage(), prParaboloid::project3DImage(), prPerspective::project3DImage(), and setImageMetric().
set_Z()
void prPointFeature::set_Z (const double Z_) inline
Sets the Z coordinate of the 3D point expressed in the sensor frame.
Returns
Nothing
Definition at line 90 of file prPointFeature.h.
References prCartesian3DPointVec::set_Z().
Referenced by prCameraModelConvert::convert(), prCameraModelConvert::convert(), operator=(), prEquirectangular::unProject(), prOmni::unProject(), and prPerspective::unProject().
setImageMetric()
void prPointFeature::setImageMetric (const double x, const double y, const double w)
Sets the normalized image plane point coordinates.
Parameters
x the horizontal coordinate of the 2D point expressed in the normalized image plane
y the vertical coordinate of the 2D point expressed in the normalized image plane
w the homogeneous coordinate of the 2D point expressed in the normalized image plane, generally equal to 1 (Cartesian point)
Returns
Nothing
Definition at line 69 of file prPointFeature.cpp.
References set_w(), set_x(), set_y(), and x.
setObjectPixUV()
void prPointFeature::setObjectPixUV (const double oX, const double oY, const double oZ, const double u, const double v)
Sets the 3D point coordinates expressed in the object frame and the digital image plane 2D point coordinates.
Parameters
oX the X coordinate of the 3D point expressed in the world frame
oY the Y coordinate of the 3D point expressed in the world frame
oZ the Z coordinate of the 3D point expressed in the world frame
u the horizontal coordinate of the 2D point expressed in the digital image plane
v the vertical coordinate of the 2D point expressed in the digital image plane
Returns
Nothing
Definition at line 88 of file prPointFeature.cpp.
References set_oX(), set_oY(), set_oZ(), setPixUV(), and u.
setPixUV()
void prPointFeature::setPixUV (const double u, const double v)
Sets the digital image plane point coordinates.
Parameters
u the horizontal coordinate of the 2D point expressed in the digital image plane
v the vertical coordinate of the 2D point expressed in the digital image plane
Returns
Nothing
Definition at line 82 of file prPointFeature.cpp.
References set_u(), set_v(), and u.
Referenced by setObjectPixUV().
setWorldCoordinates() [1/2]
void prPointFeature::setWorldCoordinates (const double ox, const double oy, const double oz)
Sets the world coordinates of the 3D point.
set the point world coordinates
Parameters
oX the X coordinate of the 3D point expressed in the world frame
oY the Y coordinate of the 3D point expressed in the world frame
oZ the Z coordinate of the 3D point expressed in the world frame
Returns
Nothing
Definition at line 11 of file prPointFeature.cpp.
References prCartesian3DPointVec::setPoint(), and wX.
setWorldCoordinates() [2/2]
int prPointFeature::setWorldCoordinates (const prCartesian3DPointVec & _wX)
Sets the world coordinates of the 3D point (the 3D point is automatically set so that W = 1)
Parameters
_wX the 4-vector containing the X, Y, Z and W coordinates of the 3D point expressed in the world frame
Returns
0 if _wX is a homogeneous point -1 if not (i.e. if it is a vector)
Definition at line 20 of file prPointFeature.cpp.
References prCartesian3DPointVec::get_W(), prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), prCartesian3DPointVec::set(), prCartesian3DPointVec::toEuclidean(), and wX.
toDouble()
double * prPointFeature::toDouble (unsigned int place = 0) virtual
conversion of the feature to an array of double
Parameters
place the place of defintion of the feature
Returns
the array (pointer kept for freeing memory) of double values
Implements prFeature.
Definition at line 112 of file prPointFeature.cpp.
Member Data Documentation
doubleFeature
double* prFeature::doubleFeature protected inherited
Definition at line 43 of file prFeature.h.
Referenced by prIntensity< Ts, Tcam >::operator=(), prPhotometricGMS< Ts >::operator=(), prPhotometricnnGMS< Ts >::operator=(), prIntensity< Ts, Tcam >::toDouble(), prPhotometricGMS< Ts >::toDouble(), prPhotometricnnGMS< Ts >::toDouble(), and prFeature::~prFeature().
ix
prCartesian3DPointVec prPointFeature::ix
world frame 3D, sensor frame 3D, intermediate projection 3D/2D points
Definition at line 26 of file prPointFeature.h.
sX
prCartesian3DPointVec prPointFeature::sX
Definition at line 26 of file prPointFeature.h.
Referenced by prRegularlySampledCSImage< T >::buildFromEquiRect(), prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), prRegularlySampledCSImage< T >::buildFromTwinOmni(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), prRegularlySampledCSImage< T >::toEquiRect(), prRegularlySampledCSImageDepth< TImage >::toEquiRect(), prVoronoiIcosahedronImageMapping< T >::toImageRotate(), prRegularlySampledCSImage< T >::toTwinOmni(), and prVoronoiIcosahedronImageMapping< T >::toTwinOmni().
u
prCartesian2DPointVec prPointFeature::u
Metric/Normalized sensor surface, acquisition sample 2D points
Definition at line 27 of file prPointFeature.h.
Referenced by setObjectPixUV(), and setPixUV().
wX
prCartesian3DPointVec prPointFeature::wX
Definition at line 26 of file prPointFeature.h.
Referenced by changeFrame(), getWorldCoordinates(), getWorldCoordinates(), getWorldCoordinates(), setWorldCoordinates(), and setWorldCoordinates().
x
prCartesian2DPointVec prPointFeature::x
Definition at line 27 of file prPointFeature.h.
Referenced by getImageMetric(), and setImageMetric().