PER: prPoseXML Class Reference
prPoseXML Class Reference
#include <prPoseXML.h>
Public Member Functions
virtual ~prPoseXML () override=default
void xmlWriteToFile ()
Protected Member Functions
void xmlOpenToParse ()
void xmlOpenToWrite ()
void xmlEndAccessFile ()
void setPath (std::string nPath)
std::string getPath ()
Static Protected Member Functions
static void xmlReadCharChild (xmlDocPtr &doc, xmlNodePtr &node, char **res)
static void xmlReadDoubleChild (xmlDocPtr &, xmlNodePtr node, double &res)
static void xmlReadIntChild (xmlDocPtr &, xmlNodePtr &node, int &res)
static std::string xmlC2S (const xmlChar *str)
Protected Attributes
xmlNodePtr node
xmlDocPtr doc
std::string file
Detailed Description
Definition at line 19 of file prPoseXML.h.
Constructor & Destructor Documentation
~prPoseXML()
virtual prPoseXML::~prPoseXML () override virtual default
Member Function Documentation
getPath()
std::string prXML::getPath () protected inherited
Gets the XML filename.
Returns
the XML filename string
Definition at line 38 of file prXML.cpp.
References prXML::file.
setPath()
void prXML::setPath (std::string nPath) protected inherited
Sets the XML filename.
Parameters
nPath the XML filename string
Returns
Nothing
Definition at line 33 of file prXML.cpp.
References prXML::file.
Referenced by prXML::prXML().
xmlC2S()
std::string prXML::xmlC2S (const xmlChar * str) static protected inherited
Converts a characters string from the xmlChar type to the std::sting type.
Parameters
str the xmlChar type characters string
Returns
the converted string
Definition at line 89 of file prXML.cpp.
References prIntensity< Ts, Tcam >::prIntensity().
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), and prStereoModelXML::readSystem().
xmlEndAccessFile()
void prXML::xmlEndAccessFile () protected inherited
Close the XML file.
Returns
Nothing
Definition at line 49 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), prStereoModelXML::operator<<(), prStereoModelXML::operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), prStereoModelXML::operator>>(), and prStereoModelXML::operator>>().
xmlOpenToParse()
void prXML::xmlOpenToParse () protected inherited
Open the XML file for reading.
Returns
Nothing
Definition at line 14 of file prXML.cpp.
References prXML::doc, prXML::file, and prXML::node.
Referenced by prStereoModelXML::operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), prStereoModelXML::operator>>(), and prStereoModelXML::operator>>().
xmlOpenToWrite()
void prXML::xmlOpenToWrite () protected inherited
Open the XML file for writing.
Returns
Nothing
Definition at line 22 of file prXML.cpp.
References prXML::doc, prXML::file, and prXML::node.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and prStereoModelXML::operator<<().
xmlReadCharChild()
void prXML::xmlReadCharChild (xmlDocPtr & doc, xmlNodePtr & node, char ** res) static protected inherited
Reads the next child of a XML tree node of type char.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res a pointer to the array of char that will contain the reading as output
Returns
Nothing
Definition at line 53 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), and prOmniXML::getModel().
xmlReadDoubleChild()
void prXML::xmlReadDoubleChild (xmlDocPtr & doc, xmlNodePtr node, double & res) static protected inherited
Reads the next child of a XML tree node of type double.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the double variable that will contain the reading as output
Returns
Nothing
Definition at line 75 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), and prStereoModelXML::readSystem().
xmlReadIntChild()
void prXML::xmlReadIntChild (xmlDocPtr & doc, xmlNodePtr & node, int & res) static protected inherited
Reads the next child of a XML tree node of type int.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the int variable that will contain the reading as output
Returns
Nothing
Definition at line 61 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prStereoModelXML::readNbCams(), and prStereoModelXML::readSystem().
xmlWriteToFile()
void prXML::xmlWriteToFile () inherited
Effectively write the XML tree to a file.
Returns
the converted string
Definition at line 43 of file prXML.cpp.
References prXML::doc, and prXML::file.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and prStereoModelXML::operator<<().
Member Data Documentation
doc
xmlDocPtr prXML::doc protected inherited
Smart pointer to a XML document
Definition at line 28 of file prXML.h.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), prStereoModelXML::readSystem(), prXML::xmlEndAccessFile(), prXML::xmlOpenToParse(), prXML::xmlOpenToWrite(), prXML::xmlReadCharChild(), prXML::xmlReadDoubleChild(), prXML::xmlReadIntChild(), and prXML::xmlWriteToFile().
file
std::string prXML::file protected inherited
XML filename
Definition at line 29 of file prXML.h.
Referenced by prXML::getPath(), prXML::setPath(), prXML::xmlOpenToParse(), prXML::xmlOpenToWrite(), and prXML::xmlWriteToFile().
node
xmlNodePtr prXML::node protected inherited
Smart pointer to a XML tree node
Definition at line 27 of file prXML.h.
Referenced by prIcosahedronSamples::loadDelaunaySamples(), prIcosahedronSamples::loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), prStereoModelXML::readSystem(), prCameraModelXML::writeModel(), prStereoModelXML::writeSystem(), prXML::xmlOpenToParse(), and prXML::xmlOpenToWrite().