PER: prCameraModelXML Class Reference
prCameraModelXML Class Reference
#include <prCameraModelXML.h>
Public Member Functions
prCameraModelXML (std::string fic)
virtual ~prCameraModelXML () override=default
void operator<< (prCameraModel *cam)
void operator>> (prCameraModel *cam)
Public Member Functions inherited from prSensorModelXML
prSensorModelXML (std::string fic)
virtual ~prSensorModelXML () override=default
Public Member Functions inherited from prXML
void xmlWriteToFile ()
virtual ~prXML () override=default
Public Member Functions inherited from prIo
virtual ~prIo ()=default
Static Public Member Functions
static xmlNodePtr putModel (prCameraModel *)
static int getModel (xmlDocPtr &doc, xmlNodePtr node, prCameraModel *cam)
static int getModelType (xmlDocPtr &doc, xmlNodePtr node_model)
Protected Member Functions
int readModel (prCameraModel *cam)
void writeModel (prCameraModel *cam)
Protected Member Functions inherited from prXML
prXML (std::string ficIn)
prXML ()
void xmlOpenToParse ()
void xmlOpenToWrite ()
void xmlEndAccessFile ()
void setPath (std::string nPath)
std::string getPath ()
Additional Inherited Members
Static Protected Member Functions inherited from prXML
static void xmlReadCharChild (xmlDocPtr &doc, xmlNodePtr &node, char **res)
static void xmlReadDoubleChild (xmlDocPtr &, xmlNodePtr node, double &res)
static void xmlReadIntChild (xmlDocPtr &, xmlNodePtr &node, int &res)
static std::string xmlC2S (const xmlChar *str)
Protected Attributes inherited from prXML
xmlNodePtr node
xmlDocPtr doc
std::string file
Detailed Description
Definition at line 48 of file prCameraModelXML.h.
Constructor & Destructor Documentation
prCameraModelXML()
prCameraModelXML::prCameraModelXML (std::string fic)
Constructor of a prCameraModelXML object.
Parameters
ficIn the XML filename string
Definition at line 3 of file prCameraModelXML.cpp.
~prCameraModelXML()
virtual prCameraModelXML::~prCameraModelXML () override virtual default
Member Function Documentation
getModel()
int prCameraModelXML::getModel (xmlDocPtr & doc, xmlNodePtr node, prCameraModel * cam) static
Gets parameters of the prX camera model cam from the XML tree node.
Parameters
doc the XML document smart pointer
node the XML node at which to read the prX camera model parameters
cam the prX camera model that holds the parameters to save
Returns
0 if runned fine
Definition at line 62 of file prCameraModelXML.cpp.
References prXML::doc, prCameraModel::init(), LABEL_XML_AU, LABEL_XML_AV, LABEL_XML_CAMERA_NAME, LABEL_XML_CAMERA_TYPE, LABEL_XML_U0, LABEL_XML_V0, prIntensity< Ts, Tcam >::prIntensity(), prXML::xmlC2S(), prXML::xmlReadCharChild(), prXML::xmlReadDoubleChild(), and prXML::xmlReadIntChild().
Referenced by readModel(), and prStereoModelXML::readSystem().
getModelType()
int prCameraModelXML::getModelType (xmlDocPtr & doc, xmlNodePtr node_model) static
Gets the camera model type to know which prX camera model to allocate.
Parameters
doc the XML document smart pointer
node the XML node that holds the parameters to read
Returns
-1 if runned bad the camera type enum int otherwise
Definition at line 142 of file prCameraModelXML.cpp.
References prXML::doc, LABEL_XML_CAMERA_TYPE, prXML::xmlC2S(), and prXML::xmlReadIntChild().
Referenced by prStereoModelXML::readSystem().
operator<<()
void prCameraModelXML::operator<< (prCameraModel * cam)
<< operator override for writing a prX camera model to a XML file
Parameters
cam the prX camera model to write
Returns
Nothing.
Definition at line 8 of file prCameraModelXML.cpp.
References writeModel(), prXML::xmlEndAccessFile(), prXML::xmlOpenToWrite(), and prXML::xmlWriteToFile().
Referenced by prEquirectangularXML::operator<<(), and prPerspectiveXML::operator<<().
operator>>()
void prCameraModelXML::operator>> (prCameraModel * cam)
>> operator override for reading a prX camera model from a XML file
Parameters
cam the prX camera model that will hold the loaded parameters
Returns
Nothing.
Definition at line 16 of file prCameraModelXML.cpp.
References readModel(), prXML::xmlEndAccessFile(), and prXML::xmlOpenToParse().
Referenced by prEquirectangularXML::operator>>(), and prPerspectiveXML::operator>>().
putModel()
xmlNodePtr prCameraModelXML::putModel (prCameraModel * cam) static
Insert the prX camera model parameters in the XML tree.
Parameters
cam the pointer to the prX camera model that holds the parameters to save
Returns
the smart pointer to the created XML node
Definition at line 23 of file prCameraModelXML.cpp.
References prCameraModel::getau(), prCameraModel::getav(), prCameraModel::getName(), prCameraModel::getType(), prCameraModel::getu0(), prCameraModel::getv0(), LABEL_XML_AU, LABEL_XML_AV, LABEL_XML_CAMERA, LABEL_XML_CAMERA_NAME, LABEL_XML_CAMERA_TYPE, LABEL_XML_U0, and LABEL_XML_V0.
Referenced by prOmniXML::putModel(), prStereoModelXML::putSystem(), and writeModel().
readModel()
int prCameraModelXML::readModel (prCameraModel * cam) protected
Reads a camera model from the XML tree and saves parameters in a prX camera model.
Parameters
cam the pointer to the last prX camera model (must be allocated before calling readModel) of the XML tree
Returns
the number of cameras in the XML tree
Definition at line 124 of file prCameraModelXML.cpp.
References prXML::doc, getModel(), LABEL_XML_CAMERA, prXML::node, and prXML::xmlC2S().
Referenced by operator>>().
writeModel()
void prCameraModelXML::writeModel (prCameraModel * cam) protected
Writes a prX camera model to the XML tree.
Parameters
cam the pointer to the prX camera model to save
Returns
Nothing
Definition at line 119 of file prCameraModelXML.cpp.
References prXML::node, and putModel().
Referenced by operator<<().
The documentation for this class was generated from the following files:
libPeR_base/modules/io/include/per/io/prCameraModelXML.h
libPeR_base/modules/io/src/prCameraModelXML.cpp