PER: prCartesian3DPointVec Class Reference
prCartesian3DPointVec Class Reference
#include <prCartesian3DPointVec.h>
Public Member Functions
prCartesian3DPointVec (const double X=0, const double Y=0, const double Z=0, const double W=1)
virtual ~prCartesian3DPointVec () override=default
void set_X (const double X)
void set_Y (const double Y)
void set_Z (const double Z)
void set_W (const double W)
double get_X () const
double get_Y () const
double get_Z () const
double get_W () const
prCartesian3DPointVec changeFrame (const vpHomogeneousMatrix &oMi)
void setPoint (const double &X, const double &Y, const double &Z)
void setVector (const double &X, const double &Y, const double &Z)
void set (const double &X, const double &Y, const double &Z, const double &W)
int toEuclidean ()
Public Member Functions inherited from pr3DPointVec
virtual ~pr3DPointVec () override=default
Public Member Functions inherited from prPointVec
virtual ~prPointVec () override=default
Public Member Functions inherited from prGeometricElement
virtual ~prGeometricElement () override=default
Public Member Functions inherited from prPhysicalElement
prPhysicalElement ()
virtual ~prPhysicalElement ()=default
prPhysicalElement & operator= (const prPhysicalElement &pe)
unsigned int size ()
Additional Inherited Members
Protected Attributes inherited from prPhysicalElement
vpColVector p
Detailed Description
Definition at line 18 of file prCartesian3DPointVec.h.
Constructor & Destructor Documentation
prCartesian3DPointVec()
prCartesian3DPointVec::prCartesian3DPointVec (const double X = 0, const double Y = 0, const double Z = 0, const double W = 1)
Constructor setting the 3D coordinates of a point (W = 1) or a vector (W = 0)
Parameters
X horizontal coordinate
Y vertical coordinate
Z depth coordinate
W homogeneous coordinate
Definition at line 3 of file prCartesian3DPointVec.cpp.
References prPhysicalElement::p, set(), and toEuclidean().
~prCartesian3DPointVec()
virtual prCartesian3DPointVec::~prCartesian3DPointVec () override virtual default
Member Function Documentation
changeFrame()
prCartesian3DPointVec prCartesian3DPointVec::changeFrame (const vpHomogeneousMatrix & oMi)
Applies the frame change from input frame Fi to output frame Fo.
Parameters
oMi frame change from the world to the sensor frame
Returns
Modifies the output prCartesian3DPointVec variable
Definition at line 11 of file prCartesian3DPointVec.cpp.
References get_W(), get_X(), get_Y(), get_Z(), set(), and toEuclidean().
Referenced by prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), prRegularlySampledCSImage< T >::buildFromTwinOmni(), prPointFeature::changeFrame(), prPointFeature::changeFrame(), prRegularlySampledCSImage< T >::changeSampleFrame(), prRegularlySampledCSImageDepth< TImage >::changeSampleFrame(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), prRegularlySampledCSImage< T >::toEquiRect(), prRegularlySampledCSImageDepth< TImage >::toEquiRect(), prVoronoiIcosahedronImageMapping< T >::toImageRotate(), prRegularlySampledCSImage< T >::toTwinOmni(), and prVoronoiIcosahedronImageMapping< T >::toTwinOmni().
get_W()
double prCartesian3DPointVec::get_W () const inline
Accessor to the W coordinate of the 3D point expressed in the sensor frame (generally set to 1, its default value for a Cartesian point)
Returns
W
Definition at line 87 of file prCartesian3DPointVec.h.
Referenced by changeFrame(), prPointFeature::get_oW(), prPointFeature::get_W(), prRegularlySampledCSImage< T >::loadSphere(), prVoronoiIcosahedronImageMapping< T >::loadSphere(), prPointFeature::setWorldCoordinates(), and toEuclidean().
get_X()
double prCartesian3DPointVec::get_X () const inline
Accessor to the X coordinate of the 3D point expressed in the sensor frame.
Returns
X
Definition at line 66 of file prCartesian3DPointVec.h.
Referenced by prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), changeFrame(), prRegularlySampledCSImageDepth< TImage >::changeSampleFrame(), prIcosahedronSamples::createNeighborMap(), prRegularlySampledCSImage< T >::get3ClosestPoints(), prPointFeature::get_oX(), prPointFeature::get_X(), prPointFeature::getWorldCoordinates(), prPointFeature::getWorldCoordinates(), prRegularlySampledCSImage< T >::loadSphere(), prVoronoiIcosahedronImageMapping< T >::loadSphere(), prRegularlySampledCSImageDepth< TImage >::prRegularlySampledCSImageDepth(), prPointFeature::setWorldCoordinates(), toEuclidean(), prVoronoiIcosahedronImageMapping< T >::toImageRotate(), prVoronoiIcosahedronImageMapping< T >::toTwinOmni(), and prRegularlySampledCSImage< T >::toVectorsAndIntensities().
get_Y()
double prCartesian3DPointVec::get_Y () const inline
Accessor to the Y coordinate of the 3D point expressed in the sensor frame.
Returns
Y
Definition at line 73 of file prCartesian3DPointVec.h.
Referenced by prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), changeFrame(), prRegularlySampledCSImageDepth< TImage >::changeSampleFrame(), prIcosahedronSamples::createNeighborMap(), prRegularlySampledCSImage< T >::get3ClosestPoints(), prPointFeature::get_oY(), prPointFeature::get_Y(), prPointFeature::getWorldCoordinates(), prPointFeature::getWorldCoordinates(), prRegularlySampledCSImage< T >::loadSphere(), prVoronoiIcosahedronImageMapping< T >::loadSphere(), prRegularlySampledCSImageDepth< TImage >::prRegularlySampledCSImageDepth(), prPointFeature::setWorldCoordinates(), toEuclidean(), prVoronoiIcosahedronImageMapping< T >::toImageRotate(), prVoronoiIcosahedronImageMapping< T >::toTwinOmni(), and prRegularlySampledCSImage< T >::toVectorsAndIntensities().
get_Z()
double prCartesian3DPointVec::get_Z () const inline
Accessor to the Z coordinate of the 3D point expressed in the sensor frame.
Returns
Z
Definition at line 80 of file prCartesian3DPointVec.h.
Referenced by prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), changeFrame(), prRegularlySampledCSImageDepth< TImage >::changeSampleFrame(), prIcosahedronSamples::createNeighborMap(), prRegularlySampledCSImage< T >::get3ClosestPoints(), prPointFeature::get_oZ(), prPointFeature::get_Z(), prPointFeature::getWorldCoordinates(), prPointFeature::getWorldCoordinates(), prRegularlySampledCSImage< T >::loadSphere(), prVoronoiIcosahedronImageMapping< T >::loadSphere(), prRegularlySampledCSImageDepth< TImage >::prRegularlySampledCSImageDepth(), prPointFeature::setWorldCoordinates(), toEuclidean(), prVoronoiIcosahedronImageMapping< T >::toImageRotate(), prVoronoiIcosahedronImageMapping< T >::toTwinOmni(), and prRegularlySampledCSImage< T >::toVectorsAndIntensities().
set()
void prCartesian3DPointVec::set (const double & X, const double & Y, const double & Z, const double & W)
Sets the 3D vector homogeneous coordinates.
Parameters
X the vector horizontal coordinate
Y the vector vertical coordinate
Z the vector depth coordinate
W the vecotr homogeneous coordinate
Returns
Nothing
Definition at line 51 of file prCartesian3DPointVec.cpp.
References prPhysicalElement::p.
Referenced by changeFrame(), prRegularlySampledCSImage< T >::loadSphere(), prVoronoiIcosahedronImageMapping< T >::loadSphere(), prCartesian3DPointVec(), prPointFeature::setWorldCoordinates(), and toEuclidean().
set_W()
void prCartesian3DPointVec::set_W (const double W) inline
Sets the W coordinate of the 3D point expressed in the sensor frame (generally set to 1, its default value for a Cartesian point)
Returns
Nothing
Definition at line 59 of file prCartesian3DPointVec.h.
Referenced by prPointFeature::set_oW(), and prPointFeature::set_W().
set_X()
void prCartesian3DPointVec::set_X (const double X) inline
Sets the X coordinate of the 3D point expressed in the sensor frame.
Returns
Nothing
Definition at line 38 of file prCartesian3DPointVec.h.
Referenced by prPointFeature::set_oX(), and prPointFeature::set_X().
set_Y()
void prCartesian3DPointVec::set_Y (const double Y) inline
Sets the Y coordinate of the 3D point expressed in the sensor frame.
Returns
Nothing
Definition at line 45 of file prCartesian3DPointVec.h.
Referenced by prPointFeature::set_oY(), and prPointFeature::set_Y().
set_Z()
void prCartesian3DPointVec::set_Z (const double Z) inline
Sets the Z coordinate of the 3D point expressed in the sensor frame.
Returns
Nothing
Definition at line 52 of file prCartesian3DPointVec.h.
Referenced by prPointFeature::set_oZ(), and prPointFeature::set_Z().
setPoint()
void prCartesian3DPointVec::setPoint (const double & X, const double & Y, const double & Z)
Sets the 3D point coordinates, forcing W to 1.
Parameters
X the point horizontal coordinate
Y the point vertical coordinate
Z the point depth coordinate
Returns
Nothing
Definition at line 26 of file prCartesian3DPointVec.cpp.
References prPhysicalElement::p.
Referenced by prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), prRegularlySampledCSImageDepth< TImage >::changeSampleFrame(), prPointFeature::getWorldCoordinates(), prRegularlySampledCSImageDepth< TImage >::prRegularlySampledCSImageDepth(), and prPointFeature::setWorldCoordinates().
setVector()
void prCartesian3DPointVec::setVector (const double & X, const double & Y, const double & Z)
Sets the 3D vector coordinates, forcing W to 0.
Parameters
X the vector horizontal coordinate
Y the vector vertical coordinate
Z the vector depth coordinate
Returns
Nothing
Definition at line 43 of file prCartesian3DPointVec.cpp.
References prPhysicalElement::p.
toEuclidean()
int prCartesian3DPointVec::toEuclidean ()
Transforms the homogeneous coordinates of the point so that its homogeneous coordinate is equal to 1 (thus, only for a point)
Returns
0 if not a vector -1 otherwise
Definition at line 59 of file prCartesian3DPointVec.cpp.
References get_W(), get_X(), get_Y(), get_Z(), and set().
Referenced by changeFrame(), prCartesian3DPointVec(), and prPointFeature::setWorldCoordinates().
The documentation for this class was generated from the following files:
libPeR_base/modules/core/include/per/core/prCartesian3DPointVec.h
libPeR_base/modules/core/src/prCartesian3DPointVec.cpp