PER: prIntensity< Ts, Tcam > Class Template Reference
prIntensity< Ts, Tcam > Class Template Reference
#include <prIntensity.h>
Public Member Functions
prIntensity ()
prIntensity (prIntensity< Ts, Tcam > const &Src)
~prIntensity ()
template<typename T , template< typename TT > class Tacquisition>
int buildFrom (Tacquisition< T > &IS_req, Ts &_s_g, bool computePoseDerivatives=false, double rho=1., unsigned long sourceIndex=0)
template<typename T , template< typename TT > class Tacquisition>
int buildFromCam (prEquirectangular *equiCam, Tacquisition< T > &IS_req, Ts &_s_g, bool computePoseDerivatives=false, double rho=1., unsigned long sourceIndex=0)
template<typename T , template< typename TT > class Tacquisition>
int buildFromCam (prStereoModel *stereoCam, Tacquisition< T > &IS_req, Ts &_s_g, bool computePoseDerivatives=false, double rho=1., unsigned long sourceIndex=0)
void computePoseDerivative (vpRowVector &derivativeVec, double rho, bool computePoseDerivatives)
template<typename T , template< typename TT > class Tacquisition>
int updateFrom (Tacquisition< T > &IS_req, bool computeFeatureDerivatives=false, unsigned long sourceIndex=0)
template<typename T >
double derivativeFilter (vpImage< T > &fr, int r, int c, int ****N)
int getPoseJacobian (vpRowVector &Ls)
prIntensity< Ts, Tcam > operator- (const prIntensity< Ts, Tcam > &f)
prIntensity< Ts, Tcam > operator* (const prIntensity< Ts, Tcam > &f)
prIntensity< Ts, Tcam > operator* (const double w)
prIntensity< Ts, Tcam > & operator+= (const prIntensity< Ts, Tcam > &f)
prIntensity< Ts, Tcam > & operator= (const prIntensity< Ts, Tcam > &f)
float getGMS () const
double * toDouble (unsigned int place=0)
Ts getS_g () const
void setSensor (Tcam *camera_)
Public Member Functions inherited from prFeature
prFeature ()
virtual ~prFeature ()
Public Attributes
unsigned int indexU
unsigned int indexV
double IXs
double IYs
double IZs
std::vector< int ***** > neighborVec
Tcam * camera
prNeighborhood neighborhood
Additional Inherited Members
Protected Attributes inherited from prFeature
double * doubleFeature
Detailed Description
template<typename Ts, class Tcam>
class prIntensity< Ts, Tcam >
Definition at line 22 of file prIntensity.h.
Constructor & Destructor Documentation
prIntensity() [1/2]
template<typename Ts , class Tcam > prIntensity< Ts, Tcam >::prIntensity< Ts > () inline
Contructor of the prIntensity<Ts> photometric sample feature type.
Definition at line 22 of file prIntensity.h.
References prIntensity< Ts, Tcam >::camera, prIntensity< Ts, Tcam >::getGMS(), and prIntensity< Ts, Tcam >::getS_g().
Referenced by prIntensity< Ts, Tcam >::buildFromCam(), prNeighborhood::buildNeighborsCartSphere(), prCameraPoseEstim< FSetT, FSetCmpT >::control(), prPosePerspectiveEstim< FSetT, FSetCmpT >::control(), prPoseSphericalEstim< FSetT, FSetCmpT >::control(), prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraPoseEstim< FSetT, FSetCmpT >::interactionAndError(), prStereoModelXML::putSystem(), prStereoModelXML::readSystem(), prPoseSphericalEstim< FSetT, FSetCmpT >::track(), prIntensity< Ts, Tcam >::updateFrom(), and prXML::xmlC2S().
prIntensity() [2/2]
template<typename Ts , class Tcam > prIntensity< Ts, Tcam >::prIntensity (prIntensity< Ts, Tcam > const & Src) inline
Definition at line 22 of file prIntensity.h.
~prIntensity()
template<typename Ts , class Tcam > prIntensity< Ts, Tcam >::~prIntensity () inline
Destructor of a prIntensity photometric sample feature object.
Definition at line 52 of file prIntensity.h.
Member Function Documentation
buildFrom()
template<typename Ts , class Tcam > template<typename T , template< typename TT > class Tacquisition> int prIntensity< Ts, Tcam >::buildFrom (Tacquisition< T > & IS_req, Ts & _s_g, bool computePoseDerivatives = false, double rho = 1., unsigned long sourceIndex = 0) inline
Computes the sample value from the set of a sample (one for each "pixel") from an equirectangular given camera, and, optionally (iff computePoseDerivatives == true), computes the photometric drivatives with respect to the 6 DOFs pose TODO: take degrees of freedom into account to save processing time TODO: find how to take properly account of the image type, if unsigned char the photometric value is put in the [0,1] interval.
Parameters
equiCam pointer to the equirectangular camera, used to project the feature on the image plane and likewise in the other direction
IS_req the input data from which to compute the Gaussian mixture sample value
_s_g the Gaussian mixture sample parameters (essentially, the location)
computePoseDerivatives boolean to let, if true, the method to compute the derivates with respect to the pose or not, if false
rho the distance of 3D point to the camera (1 by default if no 3D data is used)
sourceIndex the index of the sample to consider
Returns
0 if the computation succeeds
Parameters
stereoCam pointer to the dual fisheye camera, used to project the feature on the image plane and likewise in the other direction
IS_req the input data from which to compute the Gaussian mixture sample value
_s_g the Gaussian mixture sample parameters (essentially, the location)
computePoseDerivatives boolean to let, if true, the method to compute the derivates with respect to the pose or not, if false
rho the distance of 3D point to the camera (1 by default if no 3D data is used)
sourceIndex the index of the sample to consider
Returns
0 if the computation succeeds
Definition at line 58 of file prIntensity.h.
Referenced by prStereoModelXML::readSystem(), and prPoseSphericalEstim< FSetT, FSetCmpT >::track().
buildFromCam() [1/2]
template<typename Ts , class Tcam > template<typename T , template< typename TT > class Tacquisition> int prIntensity< Ts, Tcam >::buildFromCam (prEquirectangular * equiCam, Tacquisition< T > & IS_req, Ts & _s_g, bool computePoseDerivatives = false, double rho = 1., unsigned long sourceIndex = 0) inline
Definition at line 78 of file prIntensity.h.
References prIntensity< Ts, Tcam >::prIntensity().
buildFromCam() [2/2]
template<typename Ts , class Tcam > template<typename T , template< typename TT > class Tacquisition> int prIntensity< Ts, Tcam >::buildFromCam (prStereoModel * stereoCam, Tacquisition< T > & IS_req, Ts & _s_g, bool computePoseDerivatives = false, double rho = 1., unsigned long sourceIndex = 0) inline
Definition at line 159 of file prIntensity.h.
computePoseDerivative()
template<typename Ts , class Tcam > void prIntensity< Ts, Tcam >::computePoseDerivative (vpRowVector & derivativeVec, double rho, bool computePoseDerivatives) inline
Computes the photometric derivatives with respect to the 6 DOFs pose.
Parameters
derivativeVec the computed vector containing the derivatives of the spherical image along each direction
rho the distance of 3D point to the camera (1 by default if no 3D data is used)
computePoseDerivatives boolean to let, if true, the method to compute the derivates with respect to the pose or not, if false
Returns
0 if the computation succeeds
Definition at line 261 of file prIntensity.h.
derivativeFilter()
template<typename Ts , class Tcam > template<typename T > double prIntensity< Ts, Tcam >::derivativeFilter (vpImage< T > & fr, int r, int c, int **** N) inline
Computes the derivative of a sample based on its neighbors \TODO: Take account of the image type, if unsigned char, divide by 255, else, already in the [0,1] interval so do nothing.
Parameters
fr The considered image whose derivative will be computed
r row index where to compute the derivative
c col index where to compute the derivative
N The neighboorhood already computed that gives the indexes of the neighbors used for the derivative computation
Returns
The derivative value of the image at a given index
Definition at line 327 of file prIntensity.h.
References IMAGEPLANE_BILINEAR, and IMAGEPLANE_NEARESTNEIGH.
getGMS()
template<typename Ts , class Tcam > double prIntensity< Ts, Tcam >::getGMS () const inline
Accessor to the photometric value.
Returns
the photometric value
Definition at line 489 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator*(), prPhotometricGMS< Ts >::operator*(), prPhotometricnnGMS< Ts >::operator*(), prIntensity< Ts, Tcam >::operator+=(), prPhotometricGMS< Ts >::operator+=(), prPhotometricnnGMS< Ts >::operator+=(), prIntensity< Ts, Tcam >::operator-(), prPhotometricGMS< Ts >::operator-(), prPhotometricnnGMS< Ts >::operator-(), prIntensity< Ts, Tcam >::operator=(), prPhotometricGMS< Ts >::operator=(), prPhotometricnnGMS< Ts >::operator=(), prIntensity< Ts, Tcam >::prIntensity(), prPhotometricGMS< Ts >::prPhotometricGMS(), and prPhotometricnnGMS< Ts >::prPhotometricnnGMS().
getPoseJacobian()
template<typename Ts , class Tcam > int prIntensity< Ts, Tcam >::getPoseJacobian (vpRowVector & Ls) inline
Accessor to the pose Jacobian of the Gaussian mixture sample.
Parameters
Ls (output) the output row vector that receives the photometric Gms interaction matrix row
Returns
0 if the Jacobian could be get (if it was computed, actually) -1 if the Jacobian was not computed (no cannot be got)
Definition at line 374 of file prIntensity.h.
getS_g()
template<typename Ts , class Tcam > Ts prIntensity< Ts, Tcam >::getS_g () const inline
Accessor to the Gaussian mixture sample location type parameter TODO: move in the mother class?
Returns
the photometric location
Definition at line 518 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=(), prPhotometricGMS< Ts >::operator=(), prPhotometricnnGMS< Ts >::operator=(), prIntensity< Ts, Tcam >::prIntensity(), prPhotometricGMS< Ts >::prPhotometricGMS(), and prPhotometricnnGMS< Ts >::prPhotometricnnGMS().
operator*() [1/2]
template<typename Ts , class Tcam > prIntensity< Ts > prIntensity< Ts, Tcam >::operator* (const double w) inline
operator override to multiply a photometric value with a scalar TODO : check line fOut.s_g = s_g * w;
Parameters
w the scalar to multiply with the photometric
Returns
the prIntensity<Ts> object resulting from the product with a scalar computation
Definition at line 424 of file prIntensity.h.
operator*() [2/2]
template<typename Ts , class Tcam > prIntensity< Ts, Tcam > prIntensity< Ts, Tcam >::operator* (const prIntensity< Ts, Tcam > & f) inline
Definition at line 408 of file prIntensity.h.
References prIntensity< Ts, Tcam >::getGMS().
operator+=()
template<typename Ts , class Tcam > prIntensity< Ts > & prIntensity< Ts, Tcam >::operator+= (const prIntensity< Ts, Tcam > & f) inline
+= operator override to add two photometric values, updating the current one TODO : check line s_g += f.s_g;
Parameters
f the photometric to add to the current
Returns
the prIntensity<Ts> self reference object
Definition at line 440 of file prIntensity.h.
References prIntensity< Ts, Tcam >::getGMS().
operator-()
template<typename Ts , class Tcam > prIntensity< Ts > prIntensity< Ts, Tcam >::operator- (const prIntensity< Ts, Tcam > & f) inline
operator override to substract two photometric photometric values TODO : check line fOut.s_g = s_g - f.s_g;
Parameters
f the photometric to substract from the current
Returns
the prIntensity<Ts> object resulting from the difference computation
Definition at line 391 of file prIntensity.h.
References prIntensity< Ts, Tcam >::getGMS().
operator=()
template<typename Ts , class Tcam > prIntensity< Ts > & prIntensity< Ts, Tcam >::operator= (const prIntensity< Ts, Tcam > & f) inline
= operator override to copy photometric object \TODO: make a clean memory copy of the neighbors to avoid computing them again
Parameters
f the photometric to copy to the current
Returns
the prIntensity<Ts> self reference object
Definition at line 456 of file prIntensity.h.
References prIntensity< Ts, Tcam >::camera, prFeature::doubleFeature, prIntensity< Ts, Tcam >::getGMS(), prIntensity< Ts, Tcam >::getS_g(), prIntensity< Ts, Tcam >::indexU, prIntensity< Ts, Tcam >::indexV, prIntensity< Ts, Tcam >::IXs, prIntensity< Ts, Tcam >::IYs, and prIntensity< Ts, Tcam >::IZs.
setSensor()
template<typename Ts , class Tcam > void prIntensity< Ts, Tcam >::setSensor (Tcam * camera_) inline
Definition at line 523 of file prIntensity.h.
toDouble()
template<typename Ts , class Tcam > double * prIntensity< Ts, Tcam >::toDouble (unsigned int place = 0) inline virtual
implementation of the toDouble method of the mother class converting the photometric feature type to a common double value TODO: move in the mother class?
Parameters
place ?
Returns
the pointer to the double type vlaue of the photometric
Implements prFeature.
Reimplemented in prPhotometricGMS< Ts >, and prPhotometricnnGMS< Ts >.
Definition at line 501 of file prIntensity.h.
References prFeature::doubleFeature.
Referenced by prCameraPoseEstim< FSetT, FSetCmpT >::control(), prPosePerspectiveEstim< FSetT, FSetCmpT >::control(), prPoseSphericalEstim< FSetT, FSetCmpT >::control(), prCameraPoseEstim< FSetT, FSetCmpT >::interactionAndError(), and prPoseSphericalEstim< FSetT, FSetCmpT >::track().
updateFrom()
template<typename Ts , class Tcam > template<typename T , template< typename TT > class Tacquisition> int prIntensity< Ts, Tcam >::updateFrom (Tacquisition< T > & IS_req, bool computeFeatureDerivatives = false, unsigned long sourceIndex = 0) inline
Definition at line 304 of file prIntensity.h.
References prIntensity< Ts, Tcam >::prIntensity().
Member Data Documentation
camera
template<typename Ts , class Tcam > Tcam* prIntensity< Ts, Tcam >::camera
Definition at line 531 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=(), and prIntensity< Ts, Tcam >::prIntensity().
indexU
template<typename Ts , class Tcam > unsigned int prIntensity< Ts, Tcam >::indexU
Definition at line 528 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
indexV
template<typename Ts , class Tcam > unsigned int prIntensity< Ts, Tcam >::indexV
Definition at line 528 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
IXs
template<typename Ts , class Tcam > double prIntensity< Ts, Tcam >::IXs
Definition at line 529 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
IYs
template<typename Ts , class Tcam > double prIntensity< Ts, Tcam >::IYs
Definition at line 529 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
IZs
template<typename Ts , class Tcam > double prIntensity< Ts, Tcam >::IZs
Definition at line 529 of file prIntensity.h.
Referenced by prIntensity< Ts, Tcam >::operator=().
neighborhood
template<typename Ts , class Tcam > prNeighborhood prIntensity< Ts, Tcam >::neighborhood
Definition at line 532 of file prIntensity.h.
neighborVec
template<typename Ts , class Tcam > std::vector<int *****> prIntensity< Ts, Tcam >::neighborVec
Definition at line 530 of file prIntensity.h.
The documentation for this class was generated from the following file:
libPeR_base/modules/features/include/per/features/prIntensity.h