PER: prFisheyeEquidistant Class Reference
prFisheyeEquidistant Class Reference
#include <prFisheyeEquidistant.h>
Public Member Functions
prFisheyeEquidistant (double au=0, double av=0, double u0=0, double v0=0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0)
virtual ~prFisheyeEquidistant () override=default
void init (double au, double av, double u0, double v0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0)
void project3DImage (prPointFeature &P)
bool unProject (prPointFeature &P, double &Depth)
void project3DSphere (prPointFeature &P, double &Xs, double &Ys, double &Zs)
virtual bool projectImageSphere (prPointFeature &P, double &Xs, double &Ys, double &Zs)
prFisheyeEquidistant & operator= (const prFisheyeEquidistant &cam)
void computeSensorJacobian (prPointFeature &P, vpMatrix &LuX)
void init (double au=0, double av=0, double u0=0, double v0=0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0, double k6=0, double k7=0, double k8=0)
void init (const prCameraModel &c)
void meterPixelConversion (prPointFeature &P)
void pixelMeterConversion (prPointFeature &P)
CameraModelType getType ()
std::string getName () const
double getau () const
double getav () const
double getu0 () const
double getv0 () const
double getk1 () const
double getk2 () const
double getk3 () const
double getk4 () const
double getk5 () const
double getk6 () const
double getk7 () const
double getk8 () const
double getik1 () const
double getik2 () const
double getik3 () const
double getik4 () const
double getik5 () const
double getik6 () const
double getik7 () const
double getik8 () const
int getNbActiveParameters () const
int getNbActiveDistorsionParameters () const
vpMatrix getK () const
void setDistorsions (bool d)
void setType (CameraModelType m)
void setName (std::string n)
void setPixelRatio (double au, double av)
void setPrincipalPoint (double u0, double v0)
void setDistorsionParameters (double k1=0, double k2=0, double k3=0, double k4=0, double k5=0, double k6=0, double k7=0, double k8=0)
void setUndistorsionParameters (double ik1=0, double ik2=0, double ik3=0, double ik4=0, double ik5=0, double ik6=0, double ik7=0, double ik8=0)
void setActiveDistorsionParameters (bool k1=true, bool k2=true, bool k3=true, bool k4=true, bool k5=true, bool k6=true, bool k7=true, bool k8=true)
virtual std::ostream & operator<< (std::ostream &os)
Public Attributes
double au
double av
double u0
double v0
double inv_av
double inv_au
CameraModelType type
std::string name
bool distorsions
double k [8]
bool activek [8]
double ik [8]
int nbActiveParametersBase
int nbActiveParameters
Detailed Description
Definition at line 18 of file prFisheyeEquidistant.h.
Constructor & Destructor Documentation
prFisheyeEquidistant()
prFisheyeEquidistant::prFisheyeEquidistant (double au = 0, double av = 0, double u0 = 0, double v0 = 0, double k1 = 0, double k2 = 0, double k3 = 0, double k4 = 0, double k5 = 0)
Contructor of the prFisheyeEquidistant camera model initializing intrinsic parameters.
Parameters
au the horizontal scale factor from the normalized image plane to the digital image (\alpha_u)
av the vertical scale factor from the normalized image plane to the digital image (\alpha_v)
u0 the horizontal coordinate of the principal point (u_0)
v0 the vertical coordinate of the principal point (v_0)
k1 the second order radial distorsion parameter (k_1)
k2 the fourth order radial distorsion parameter (k_2)
k3 the sixth order radial distorsion parameter (k_3)
k4 the first tangential distorsion parameter (k_4)
k5 the second tangential distorsion parameter (k_5)
Definition at line 3 of file prFisheyeEquidistant.cpp.
References prCameraModel::name, and prCameraModel::type.
~prFisheyeEquidistant()
prFisheyeEquidistant::~prFisheyeEquidistant () override virtual default
Destructor of a prFisheyeEquidistant object.
Member Function Documentation
computeSensorJacobian()
void prFisheyeEquidistant::computeSensorJacobian (prPointFeature & P, vpMatrix & LuX) virtual
computes the Jacobian of the sensor digital image point coordinates with respect to the 3D coordinates in the camera frame
Parameters
P the point for which computing the Jacobian
LuX the output Jacobian Matrix
Returns
Nothing
Reimplemented from prCameraModel.
Definition at line 72 of file prFisheyeEquidistant.cpp.
getau()
double prCameraModel::getau () const inline inherited
Accessor to the au (\alpha_u) parameter of the current sensor model.
Returns
au
Definition at line 181 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert(), prCameraModelConvert::convert(), prCameraModelConvert::convert(), prCameraModel::operator<<(), and prCameraModelXML::putModel().
getav()
double prCameraModel::getav () const inline inherited
Accessor to the av (\alpha_v) parameter of the current sensor model.
Returns
av
Definition at line 188 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModel::operator<<(), and prCameraModelXML::putModel().
getik1()
double prCameraModel::getik1 () const inline inherited
Accessor to the ik1 (k_1') radial undistorsion parameter of the current sensor model.
Returns
ik1
Definition at line 267 of file prCameraModel.h.
Referenced by prCameraModel::operator<<().
getik2()
double prCameraModel::getik2 () const inline inherited
Accessor to the ik2 (k_2') radial undistorsion parameter of the current sensor model.
Returns
ik2
Definition at line 274 of file prCameraModel.h.
Referenced by prCameraModel::operator<<().
getik3()
double prCameraModel::getik3 () const inline inherited
Accessor to the ik3 (k_3') radial undistorsion parameter of the current sensor model.
Returns
ik3
Definition at line 281 of file prCameraModel.h.
Referenced by prCameraModel::operator<<().
getik4()
double prCameraModel::getik4 () const inline inherited
Accessor to the ik4 (k_4') tangential undistorsion parameter of the current sensor model.
Returns
ik4
Definition at line 288 of file prCameraModel.h.
Referenced by prCameraModel::operator<<().
getik5()
double prCameraModel::getik5 () const inline inherited
Accessor to the ik5 (k_5') tangential undistorsion parameter of the current sensor model.
Returns
ik5
Definition at line 295 of file prCameraModel.h.
Referenced by prCameraModel::operator<<().
getik6()
double prCameraModel::getik6 () const inline inherited
Accessor to the ik6 (k_6') rational radial undistorsion parameter of the current sensor model.
Returns
ik6
Definition at line 302 of file prCameraModel.h.
Referenced by prCameraModel::operator<<().
getik7()
double prCameraModel::getik7 () const inline inherited
Accessor to the ik7 (k_7') rational radial undistorsion parameter of the current sensor model.
Returns
ik7
Definition at line 309 of file prCameraModel.h.
Referenced by prCameraModel::operator<<().
getik8()
double prCameraModel::getik8 () const inline inherited
Accessor to the ik8 (ik_8) rational radial undistorsion parameter of the current sensor model.
Returns
ik8
Definition at line 316 of file prCameraModel.h.
Referenced by prCameraModel::operator<<().
getK()
vpMatrix prCameraModel::getK () const inherited
Gets the K_3x3 affine transformation matrix containing intrinsic parameters au, av, u0 and v0.
Returns
K_3x3
Definition at line 353 of file prCameraModel.cpp.
References prCameraModel::au, prCameraModel::av, prCameraModel::u0, and prCameraModel::v0.
getk1()
double prCameraModel::getk1 () const inline inherited
Accessor to the k1 (k_1) radial distorsion parameter of the current sensor model.
Returns
k1
Definition at line 210 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModel::operator<<().
getk2()
double prCameraModel::getk2 () const inline inherited
Accessor to the k2 (k_2) radial distorsion parameter of the current sensor model.
Returns
k2
Definition at line 217 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModel::operator<<().
getk3()
double prCameraModel::getk3 () const inline inherited
Accessor to the k3 (k_3) radial distorsion parameter of the current sensor model.
Returns
k3
Definition at line 224 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModel::operator<<().
getk4()
double prCameraModel::getk4 () const inline inherited
Accessor to the k4 (k_4) tangential distorsion parameter of the current sensor model.
Returns
k4
Definition at line 231 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModel::operator<<().
getk5()
double prCameraModel::getk5 () const inline inherited
Accessor to the k5 (k_5) tangential distorsion parameter of the current sensor model.
Returns
k5
Definition at line 238 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModel::operator<<().
getk6()
double prCameraModel::getk6 () const inline inherited
Accessor to the k6 (k_6) rational radial distorsion parameter of the current sensor model.
Returns
k6
Definition at line 245 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModel::operator<<().
getk7()
double prCameraModel::getk7 () const inline inherited
Accessor to the k7 (k_7) rational radial distorsion parameter of the current sensor model.
Returns
k7
Definition at line 252 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModel::operator<<().
getk8()
double prCameraModel::getk8 () const inline inherited
Accessor to the k8 (k_8) rational radial distorsion parameter of the current sensor model.
Returns
k8
Definition at line 259 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModel::operator<<().
getName()
std::string prCameraModel::getName () const inline inherited
Accessor to the name of the current sensor model.
Returns
The sensor type name
Definition at line 174 of file prCameraModel.h.
Referenced by prCameraModelXML::putModel().
getNbActiveDistorsionParameters()
int prCameraModel::getNbActiveDistorsionParameters () const inline inherited
Gets the number of considered distorsion parameters.
Returns
The number of active distorsion parameters
Definition at line 331 of file prCameraModel.h.
getNbActiveParameters()
int prCameraModel::getNbActiveParameters () const inline inherited
Gets the total number of considered instrinsic parameters (including distorsion parameters)
Returns
The number of active parameters
Definition at line 324 of file prCameraModel.h.
getType()
CameraModelType prCameraModel::getType () inline inherited
Accessor to the type of the current sensor model.
Returns
The sensor model type
Definition at line 167 of file prCameraModel.h.
Referenced by prCameraModelXML::putModel().
getu0()
double prCameraModel::getu0 () const inline inherited
Accessor to the u0 (u_0) parameter of the current sensor model.
Returns
u0
Definition at line 195 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert(), prCameraModelConvert::convert(), prCameraModelConvert::convert(), prCameraModelConvert::convert(), prCameraModelConvert::FCVreverseConvert(), prCameraModel::operator<<(), and prCameraModelXML::putModel().
getv0()
double prCameraModel::getv0 () const inline inherited
Accessor to the v0 (v_0) parameter of the current sensor model.
Returns
v0
Definition at line 202 of file prCameraModel.h.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert(), prCameraModelConvert::convert(), prCameraModelConvert::convert(), prCameraModelConvert::convert(), prCameraModel::operator<<(), and prCameraModelXML::putModel().
init() [1/3]
void prCameraModel::init (const prCameraModel & c) inherited
Initialize the intrinsic parameters from another prCameraModel object.
Parameters
c the input prCameraModel object from which intrinsic parameters are going to be copied
Returns
Nothing
Definition at line 96 of file prCameraModel.cpp.
References prCameraModel::name.
init() [2/3]
void prFisheyeEquidistant::init (double au, double av, double u0, double v0, double k1 = 0, double k2 = 0, double k3 = 0, double k4 = 0, double k5 = 0)
Initializing intrinsic parameters.
Parameters
au the horizontal scale factor from the normalized image plane to the digital image (\alpha_u)
av the vertical scale factor from the normalized image plane to the digital image (\alpha_v)
u0 the horizontal coordinate of the principal point (u_0)
v0 the vertical coordinate of the principal point (v_0)
k1 the second order radial distorsion parameter (k_1)
k2 the fourth order radial distorsion parameter (k_2)
k3 the sixth order radial distorsion parameter (k_3)
k4 the first tangential distorsion parameter (k_4)
k5 the second tangential distorsion parameter (k_5)
Returns
Nothing
Definition at line 9 of file prFisheyeEquidistant.cpp.
References prCameraModel::init(), prCameraModel::name, and prCameraModel::type.
init() [3/3]
void prCameraModel::init (double au = 0, double av = 0, double u0 = 0, double v0 = 0, double k1 = 0, double k2 = 0, double k3 = 0, double k4 = 0, double k5 = 0, double k6 = 0, double k7 = 0, double k8 = 0) inherited
Definition at line 75 of file prCameraModel.cpp.
References prCameraModel::au, prCameraModel::av, prCameraModel::inv_au, prCameraModel::inv_av, prCameraModel::k, prCameraModel::name, prCameraModel::u0, and prCameraModel::v0.
Referenced by prCameraModelXML::getModel(), prParaboloid::init(), prEquirectangular::init(), init(), prFisheyeEquisolid::init(), prOmni::init(), prPolyCart::init(), and prCameraModel::prCameraModel().
meterPixelConversion()
void prCameraModel::meterPixelConversion (prPointFeature & P) inherited
Convert a 2D point from the normalized image plane to the digital image plane.
Parameters
P the point to convert
Returns
Nothing
Definition at line 102 of file prCameraModel.cpp.
References prCameraModel::activek, prCameraModel::au, prCameraModel::av, prCameraModel::distorsions, prPointFeature::get_x(), prPointFeature::get_y(), prCameraModel::k, prPointFeature::set_u(), prPointFeature::set_v(), prCameraModel::u0, and prCameraModel::v0.
Referenced by prRegularlySampledCSImage< T >::buildFromEquiRect(), prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect(), prNeighborhood::buildNeighborsCartSphere(), prCameraModelConvert::conversion(), prCameraModelConvert::convert(), prCameraModelConvert::convert_distortions(), prVoronoiIcosahedronImageMapping< T >::createImageCellsMap(), prRegularlySampledCSImage< T >::toEquiRect(), and prRegularlySampledCSImageDepth< TImage >::toEquiRect().
operator<<()
std::ostream & prCameraModel::operator<< (std::ostream & os) virtual inherited
<< operator overload for writing the prCameraModel sensor model parameters to a stream
Parameters
os the stream in which to write
Returns
the updated stream.
Reimplemented in prPerspective.
Definition at line 305 of file prCameraModel.cpp.
References prCameraModel::activek, prCameraModel::distorsions, prCameraModel::getau(), prCameraModel::getav(), prCameraModel::getik1(), prCameraModel::getik2(), prCameraModel::getik3(), prCameraModel::getik4(), prCameraModel::getik5(), prCameraModel::getik6(), prCameraModel::getik7(), prCameraModel::getik8(), prCameraModel::getk1(), prCameraModel::getk2(), prCameraModel::getk3(), prCameraModel::getk4(), prCameraModel::getk5(), prCameraModel::getk6(), prCameraModel::getk7(), prCameraModel::getk8(), prCameraModel::getu0(), and prCameraModel::getv0().
Referenced by prPerspective::operator<<().
operator=()
prFisheyeEquidistant & prFisheyeEquidistant::operator= (const prFisheyeEquidistant & cam)
= operator overload for copying a prFisheyeEquidistant camera model
Parameters
cam the source prFisheyeEquidistant
Returns
the affected prFisheyeEquidistant.
Definition at line 65 of file prFisheyeEquidistant.cpp.
References prCameraModel::operator=().
pixelMeterConversion()
void prCameraModel::pixelMeterConversion (prPointFeature & P) inherited
Convert a 2D point from the digital image plane to the normalized image plane.
Parameters
P the point to convert
Returns
Nothing
!!!!! Attention : temporaire !!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Definition at line 153 of file prCameraModel.cpp.
References prCameraModel::activek, prCameraModel::distorsions, prPointFeature::get_u(), prPointFeature::get_v(), prCameraModel::ik, prCameraModel::inv_au, prCameraModel::inv_av, prPointFeature::set_x(), prPointFeature::set_y(), prCameraModel::u0, and prCameraModel::v0.
Referenced by prNeighborhood::buildNeighborsCartSphere().
project3DImage()
void prFisheyeEquidistant::project3DImage (prPointFeature & P) virtual
Project a 3D point expressed in the equidistant fisheye camera frame to the normalized image plane.
Parameters
P the point to project
Returns
Nothing
Implements prCameraModel.
Definition at line 18 of file prFisheyeEquidistant.cpp.
References prPointFeature::get_X(), prPointFeature::get_Y(), prPointFeature::get_Z(), prPointFeature::set_x(), and prPointFeature::set_y().
project3DSphere()
void prFisheyeEquidistant::project3DSphere (prPointFeature & P, double & Xs, double & Ys, double & Zs)
Project a 3D point expressed in the equidistant fisheye camera frame to the unit sphere centered at the camera origin.
Parameters
P the point to project
Xs the Cartesian X coordinate of the projected point on the unit sphere
Ys the Cartesian Y coordinate of the projected point on the unit sphere
Zs the Cartesian Z coordinate of the projected point on the unit sphere
Returns
Nothing
Definition at line 35 of file prFisheyeEquidistant.cpp.
References prPointFeature::get_X(), prPointFeature::get_Y(), and prPointFeature::get_Z().
projectImageSphere()
bool prFisheyeEquidistant::projectImageSphere (prPointFeature & P, double & Xs, double & Ys, double & Zs) virtual
Inverse projection from the normalized image plane to the unit sphere centered at the camera origin.
Parameters
P the point to backproject
Xs the Cartesian X coordinate of the projected point on the unit sphere
Ys the Cartesian Y coordinate of the projected point on the unit sphere
Zs the Cartesian Z coordinate of the projected point on the unit sphere
Returns
Nothing
Implements prCameraModel.
Definition at line 50 of file prFisheyeEquidistant.cpp.
setActiveDistorsionParameters()
void prCameraModel::setActiveDistorsionParameters (bool k1 = true, bool k2 = true, bool k3 = true, bool k4 = true, bool k5 = true, bool k6 = true, bool k7 = true, bool k8 = true) inherited
Sets which distorsion/undistorsion parameters are considered in the sensor model.
Parameters
k1 true: k1 and ik1 are considered false: k1 and ik1 are not considered
k2 true: k2 and ik2 are considered false: k2 and ik2 are not considered
k3 true: k3 and ik3 are considered false: k3 and ik3 are not considered
k4 true: k4 and ik4 are considered false: k4 and ik4 are not considered
k5 true: k5 and ik5 are considered false: k5 and ik5 are not considered
k6 true: k6 and ik6 are considered false: k6 and ik6 are not considered
k7 true: k7 and ik7 are considered false: k7 and ik7 are not considered
k8 true: k8 and ik8 are considered false: k8 and ik8 are not considered
Returns
Nothing
Definition at line 260 of file prCameraModel.cpp.
References prCameraModel::activek, prCameraModel::distorsions, prCameraModel::nbActiveParameters, and prCameraModel::nbActiveParametersBase.
setDistorsionParameters()
void prCameraModel::setDistorsionParameters (double k1 = 0, double k2 = 0, double k3 = 0, double k4 = 0, double k5 = 0, double k6 = 0, double k7 = 0, double k8 = 0) inherited
Sets the five distorsion parameters (from the normalized image plane to the distorted normalized image plane)
Parameters
k1 the second order radial distorsion parameter (k_1)
k2 the fourth order radial distorsion parameter (k_2)
k3 the sixth order radial distorsion parameter (k_3)
k4 the first tangential distorsion parameter (k_4)
k5 the second tangential distorsion parameter (k_5)
k6 the second order rational radial distorsion parameter (k_6)
k7 the fourth order rational radial distorsion parameter (k_7)
k8 the sixth order rational radial distorsion parameter (k_8)
Returns
Nothing
Definition at line 236 of file prCameraModel.cpp.
References prCameraModel::k.
Referenced by prCameraModelConvert::conversion(), prCameraModelConvert::convert_distortions(), and prCameraModelConvert::FCVreverseConvert().
setDistorsions()
void prCameraModel::setDistorsions (bool d) inline inherited
Activates or cancels the consideration of distorsion parameters.
Parameters
d true: distorsions are considered false : distorsions are not considered
Returns
Nothing
Definition at line 349 of file prCameraModel.h.
setName()
void prCameraModel::setName (std::string n) inline inherited
Sets the sensor model type name.
Parameters
n sensor model type name
Returns
Nothing
Definition at line 365 of file prCameraModel.h.
setPixelRatio()
void prCameraModel::setPixelRatio (double au, double av) inherited
Sets the scaling factors au and av (from the normalized image plane to the digital one)
Parameters
au the horizontal scale factor from the normalized image plane to the digital image (\alpha_u)
av the vertical scale factor from the normalized image plane to the digital image (\alpha_v)
Returns
Nothing
Definition at line 227 of file prCameraModel.cpp.
References prCameraModel::au, prCameraModel::av, prCameraModel::inv_au, and prCameraModel::inv_av.
Referenced by prCameraModelConvert::FCVreverseConvert().
setPrincipalPoint()
void prCameraModel::setPrincipalPoint (double u0, double v0) inherited
Sets the principal point coordinates u0 and v0.
Parameters
u0 the horizontal coordinate of the principal point (u_0)
v0 the vertical coordinate of the principal point (v_0)
Returns
Nothing
Definition at line 221 of file prCameraModel.cpp.
References prCameraModel::u0, and prCameraModel::v0.
setType()
void prCameraModel::setType (CameraModelType m) inline inherited
Sets the sensor model type.
Parameters
m sensor model type
Returns
Nothing
Definition at line 357 of file prCameraModel.h.
setUndistorsionParameters()
void prCameraModel::setUndistorsionParameters (double ik1 = 0, double ik2 = 0, double ik3 = 0, double ik4 = 0, double ik5 = 0, double ik6 = 0, double ik7 = 0, double ik8 = 0) inherited
Sets the five undistorsion parameters (from the distorted normalized image plane to the normalized image plane)
Parameters
ik1 the second order radial undistorsion parameter (k_1')
ik2 the fourth order radial undistorsion parameter (k_2')
ik3 the sixth order radial undistorsion parameter (k_3')
ik4 the first tangential undistorsion parameter (k_4')
ik5 the second tangential undistorsion parameter (k_5')
ik6 the second order rational radial undistorsion parameter (k_6')
ik7 the fourth order rational radial undistorsion parameter (k_7')
ik8 the sixth order rational radial undistorsion parameter (k_8')
Returns
Nothing
Definition at line 248 of file prCameraModel.cpp.
References prCameraModel::ik.
unProject()
bool prFisheyeEquidistant::unProject (prPointFeature & P, double & Depth) virtual
Compute the 3D point expressed in the sensor frame from the normalized image plane and the depth (must be implemented in a specified sensor model)
Parameters
P the point to unproject
Depth the Depth used to unproject the P (/rho here...)
Returns
true if unprojection could be done
Implements prCameraModel.
Definition at line 28 of file prFisheyeEquidistant.cpp.
Member Data Documentation
activek
bool prCameraModel::activek[8] inherited
Which distorsion parameter is considered by the camera model?
Definition at line 53 of file prCameraModel.h.
Referenced by prCameraModel::meterPixelConversion(), prCameraModel::operator<<(), prCameraModel::operator=(), prCameraModel::pixelMeterConversion(), prCameraModel::prCameraModel(), and prCameraModel::setActiveDistorsionParameters().
au
double prCameraModel::au inherited
Definition at line 42 of file prCameraModel.h.
Referenced by prCameraModel::computeSensorJacobian(), prCameraModel::getK(), prParaboloid::init(), prCameraModel::init(), prCameraModel::meterPixelConversion(), prCameraModel::operator=(), prPolyCart::projectImageSphere(), and prCameraModel::setPixelRatio().
av
double prCameraModel::av inherited
Definition at line 42 of file prCameraModel.h.
Referenced by prCameraModel::computeSensorJacobian(), prCameraModel::getK(), prParaboloid::init(), prCameraModel::init(), prCameraModel::meterPixelConversion(), prCameraModel::operator=(), and prCameraModel::setPixelRatio().
distorsions
bool prCameraModel::distorsions inherited
Are distorsions set?
Definition at line 46 of file prCameraModel.h.
Referenced by prCameraModel::meterPixelConversion(), prCameraModel::operator<<(), prCameraModel::operator=(), prCameraModel::pixelMeterConversion(), prCameraModel::prCameraModel(), and prCameraModel::setActiveDistorsionParameters().
ik
double prCameraModel::ik[8] inherited
Undistorsion parameters : k[0-2] : radial undistorsions k[3-4] : tangential undistorsions k[5-7] : rational radial undistortions
Definition at line 55 of file prCameraModel.h.
Referenced by prCameraModel::operator=(), prCameraModel::pixelMeterConversion(), prCameraModel::prCameraModel(), and prCameraModel::setUndistorsionParameters().
inv_au
double prCameraModel::inv_au inherited
Minimal set of intrinsic parameters (the ones of K_3x3)
Definition at line 42 of file prCameraModel.h.
Referenced by prCameraModel::init(), prCameraModel::operator=(), prCameraModel::pixelMeterConversion(), and prCameraModel::setPixelRatio().
inv_av
double prCameraModel::inv_av inherited
Definition at line 42 of file prCameraModel.h.
Referenced by prCameraModel::init(), prCameraModel::operator=(), prCameraModel::pixelMeterConversion(), and prCameraModel::setPixelRatio().
k
double prCameraModel::k[8] inherited
Distorsion parameters :
k[0-2] : radial distorsions (equivalent to OpenCV 4.8 k1, k2, k3 radial distortion parameters) k[3-4] : tangential distorsions (equivalent to OpenCV 4.8 p1, p2 tangential distortion parameters) k[5-7] : rational radial distortions (equivalent to OpenCV 4.8 k4, k5, k6 rational radial distortion parameters)
Definition at line 48 of file prCameraModel.h.
Referenced by prCameraModel::init(), prCameraModel::meterPixelConversion(), prCameraModel::operator=(), prCameraModel::prCameraModel(), and prCameraModel::setDistorsionParameters().
name
std::string prCameraModel::name inherited
Name of the camera model
Definition at line 45 of file prCameraModel.h.
Referenced by prCameraModel::init(), prParaboloid::init(), prEquirectangular::init(), init(), prFisheyeEquisolid::init(), prOmni::init(), prCameraModel::init(), prPolyCart::init(), prEquirectangular::prEquirectangular(), prFisheyeEquidistant(), prFisheyeEquisolid::prFisheyeEquisolid(), prOmni::prOmni(), prParaboloid::prParaboloid(), prPerspective::prPerspective(), and prPolyCart::prPolyCart().
nbActiveParameters
int prCameraModel::nbActiveParameters inherited
Total number of active intrinsic parameters (including distorsions)
Definition at line 62 of file prCameraModel.h.
Referenced by prCameraModel::operator=(), prCameraModel::prCameraModel(), prOmni::prOmni(), prPolyCart::prPolyCart(), and prCameraModel::setActiveDistorsionParameters().
nbActiveParametersBase
int prCameraModel::nbActiveParametersBase inherited
Number of active intrinsic parameters excluding distorsions
Definition at line 61 of file prCameraModel.h.
Referenced by prCameraModel::operator=(), prCameraModel::prCameraModel(), prOmni::prOmni(), prPolyCart::prPolyCart(), and prCameraModel::setActiveDistorsionParameters().
type
CameraModelType prCameraModel::type inherited
Type of the camera model among Omni, Persp, Fisheye, ...
Definition at line 44 of file prCameraModel.h.
Referenced by prParaboloid::init(), prEquirectangular::init(), init(), prFisheyeEquisolid::init(), prOmni::init(), prPolyCart::init(), prEquirectangular::prEquirectangular(), prFisheyeEquidistant(), prFisheyeEquisolid::prFisheyeEquisolid(), prOmni::prOmni(), prParaboloid::prParaboloid(), prPerspective::prPerspective(), and prPolyCart::prPolyCart().
u0
double prCameraModel::u0 inherited
Definition at line 42 of file prCameraModel.h.
Referenced by prNeighborhood::buildNeighborsCartSphere(), prCameraModel::getK(), prParaboloid::init(), prCameraModel::init(), prCameraModel::meterPixelConversion(), prCameraModel::operator=(), prCameraModel::pixelMeterConversion(), prPolyCart::projectImageSphere(), and prCameraModel::setPrincipalPoint().
v0
double prCameraModel::v0 inherited
Definition at line 42 of file prCameraModel.h.
Referenced by prNeighborhood::buildNeighborsCartSphere(), prCameraModel::getK(), prParaboloid::init(), prCameraModel::init(), prCameraModel::meterPixelConversion(), prCameraModel::operator=(), prCameraModel::pixelMeterConversion(), prPolyCart::projectImageSphere(), and prCameraModel::setPrincipalPoint().