PER: prCameraPoseEstim< FSetT, FSetCmpT > Class Template Reference
prCameraPoseEstim< FSetT, FSetCmpT > Class Template Reference
#include <prCameraPoseEstim.h>
Public Member Functions
prCameraPoseEstim ()
virtual ~prCameraPoseEstim () override
void setdof (bool tX=true, bool tY=true, bool tZ=true, bool rX=true, bool rY=true, bool rZ=true)
void buildFrom (FSetT &FeatureSet_)
void startSaveIterations (char *fileName)
void stopSaveIterations ()
double track (FSetT &FeatureSetd, vpPoseVector &r_optim, bool robust=false)
void initControl (float lambda_=1.f, float cst_Depth=1.f, bool current_=true)
void initPointFeatures ()
void computeScenePointJacobian (prPointFeature &P, vpMatrix &LX)
void setSensor (prSensorModel *sensor)
void computePoseJacobian (FSetT &FeatureSetc)
void composeFeaturesPoseJacobians (vpMatrix &LfRaw, vpMatrix &Lug, vpMatrix &LsRaw)
double interactionAndError (FSetT &FeatureSetc, vpMatrix &Lc, vpColVector &errc, bool robust=false)
double control (FSetT &FeatureSetc, vpColVector &v, bool robust=false)
double getCond (bool robust=false)
Detailed Description
template<class FSetT, class FSetCmpT>
class prCameraPoseEstim< FSetT, FSetCmpT >
Definition at line 27 of file prCameraPoseEstim.h.
Constructor & Destructor Documentation
prCameraPoseEstim()
template<class FSetT , class FSetCmpT > prCameraPoseEstim< FSetT, FSetCmpT >::prCameraPoseEstim () inline
Contructor of the prCameraPoseEstim.
Definition at line 34 of file prCameraPoseEstim.h.
~prCameraPoseEstim()
template<class FSetT , class FSetCmpT > prCameraPoseEstim< FSetT, FSetCmpT >::~prCameraPoseEstim () inline override virtual
Destructor of a prCameraPoseEstim object.
Definition at line 43 of file prCameraPoseEstim.h.
Member Function Documentation
buildFrom()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::buildFrom (FSetT & FeatureSet_) inline
Build the features set of reference for the pose estimator.
Parameters
I_ the source image
Returns
Nothing
Definition at line 76 of file prCameraPoseEstim.h.
composeFeaturesPoseJacobians()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::composeFeaturesPoseJacobians (vpMatrix & LfRaw, vpMatrix & Lug, vpMatrix & LsRaw) inline
computes the Jacobian of the variable sampling the acquisition model with respect to the sensor pose
Parameters
LfRaw features Jacobian of size nb features \times nb dimensions of the sampler elements
Lug sampler's Jacobian of size nb dimensions of the sampler elements * nb features \time nb degrees of freedom
LsRaw output Jacobian matrix resulting of per feature composition of LfRaw and Lug
Definition at line 307 of file prCameraPoseEstim.h.
computePoseJacobian()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::computePoseJacobian (FSetT & FeatureSetc) inline
computes the Jacobian of the variable sampling the acquisition model with respect to the sensor pose
Parameters
FeatureSetc the current feature set
!! specific
!! specific
!! specific
!! specific
!! needs to depend on the acquisition model sampler space
Definition at line 235 of file prCameraPoseEstim.h.
computeScenePointJacobian()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::computeScenePointJacobian (prPointFeature & P, vpMatrix & LX) inline
Compute the Jacobian of a 3D point with repsect to the sensor pose.
Parameters
P the point feature
LX the output interaction matrix of a 3D point (size: 3x6)
Definition at line 192 of file prCameraPoseEstim.h.
control()
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::control (FSetT & FeatureSetc, vpColVector & v, bool robust = false) inline
Compute the pose increment to move FeatureSetc toward FeatureSet.
Parameters
FeatureSetc the current feature set
v the 6-vector that contains pose increment values
Returns
the residual at convergence or -1 if control not initialized
Definition at line 494 of file prCameraPoseEstim.h.
References prIntensity< Ts, Tcam >::prIntensity(), and prIntensity< Ts, Tcam >::toDouble().
getCond()
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::getCond (bool robust = false) inline
Compute the condition number of the interaction matrix.
Parameters
robust to consider the raw of the robustified interaction matrix
Returns
the condition number
Definition at line 634 of file prCameraPoseEstim.h.
initControl()
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::initControl (float lambda_ = 1.f, float cst_Depth = 1.f, bool current_ = true) inline
Compute the pose increment to move FeatureSetc toward FeatureSet.
Parameters
FeatureSetc the current feature set
v the 6-vector that contains pose increment values
Returns
the residual at convergence
Definition at line 129 of file prCameraPoseEstim.h.
initPointFeatures()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::initPointFeatures () inline
e Initialize the table of feature points (digital image plane and normalized image plane) associated to the sampler of the feature set
Definition at line 165 of file prCameraPoseEstim.h.
interactionAndError()
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::interactionAndError (FSetT & FeatureSetc, vpMatrix & Lc, vpColVector & errc, bool robust = false) inline
Compute the interaction matrix and error vector of FeatureSetc.
Parameters
FeatureSetc the current feature set
Lc the matrix that contains the interaction matrix
errc the column vector that contains the error vector
Returns
the residual or -1 if control not initialized
Definition at line 350 of file prCameraPoseEstim.h.
References prIntensity< Ts, Tcam >::prIntensity(), and prIntensity< Ts, Tcam >::toDouble().
setdof()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::setdof (bool tX = true, bool tY = true, bool tZ = true, bool rX = true, bool rY = true, bool rZ = true) inline
Definition at line 60 of file prCameraPoseEstim.h.
setSensor()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::setSensor (prSensorModel * sensor) inline
sets the camera sensor model
Parameters
sensor the camera model to consider
Definition at line 225 of file prCameraPoseEstim.h.
startSaveIterations()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::startSaveIterations (char * fileName) inline
Opens the file in which estimation iterations will be saved.
Parameters
fileName the filename
Returns
Nothing
Definition at line 87 of file prCameraPoseEstim.h.
stopSaveIterations()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::stopSaveIterations () inline
Closes the file in which estimation iterations are saved.
Returns
Nothing
Definition at line 99 of file prCameraPoseEstim.h.
track()
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::track (FSetT & FeatureSetd, vpPoseVector & r_optim, bool robust = false) inline
Update the pose of FeatureSet so that it matches FeatureSetd.
Parameters
FeatureSetd the input data toward which degrees of freedom will have an impact on FeatureSet
r the 6-vector that contains pose elements values
Returns
the residual error at convergence
Definition at line 112 of file prCameraPoseEstim.h.