PER: prIcosahedronSamples Class Reference
prIcosahedronSamples Class Reference
#include <per/prIcosahedronSamples.h>
Public Member Functions
prIcosahedronSamples (std::string coordsPath=PER_SI_DIR)
int loadDelaunaySamples (unsigned int subdivLevels)
int loadVoronoiSamples (unsigned int subdivLevels)
void createNeighborMap (double limitDist)
prIcosahedronSamples & operator= (const prIcosahedronSamples &icoS)
void xmlWriteToFile ()
Public Attributes
double dist
int nbVertices
unsigned int subdivLevels
std::string coordsPath
prCartesian3DPointVec * samplesCoords
unsigned int maxSubdivLevels
std::map< unsigned int, std::vector< unsigned int > > neighMap
std::map< unsigned int, std::vector< prCartesian3DPointVec > > samplesVoronoiMap
Protected Member Functions
void xmlOpenToParse ()
void xmlOpenToWrite ()
void xmlEndAccessFile ()
void setPath (std::string nPath)
std::string getPath ()
Static Protected Member Functions
static void xmlReadCharChild (xmlDocPtr &doc, xmlNodePtr &node, char **res)
static void xmlReadDoubleChild (xmlDocPtr &, xmlNodePtr node, double &res)
static void xmlReadIntChild (xmlDocPtr &, xmlNodePtr &node, int &res)
static std::string xmlC2S (const xmlChar *str)
Protected Attributes
xmlNodePtr node
xmlDocPtr doc
std::string file
Detailed Description
Class for reading and loading samples coordinates coming from a subdivided icosahedron.
Definition at line 33 of file prIcosahedronSamples.h.
Constructor & Destructor Documentation
prIcosahedronSamples()
prIcosahedronSamples::prIcosahedronSamples (std::string coordsPath = PER_SI_DIR)
Constructor of the icosahedron samples class. Set the path to .xml files containing the coordinates of the icosahedron samples.
Definition at line 3 of file prIcosahedronSamples.cpp.
References coordsPath, and maxSubdivLevels.
Member Function Documentation
createNeighborMap()
void prIcosahedronSamples::createNeighborMap (double limitDist)
Definition at line 208 of file prIcosahedronSamples.cpp.
References dist, prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), nbVertices, neighMap, and samplesCoords.
getPath()
std::string prXML::getPath () protected inherited
Gets the XML filename.
Returns
the XML filename string
Definition at line 38 of file prXML.cpp.
References prXML::file.
loadDelaunaySamples()
int prIcosahedronSamples::loadDelaunaySamples (unsigned int subdivLevels)
Allocates and fill the array of points coordinates of the Delaunay graph of the Icosahedron as well as the array of "pixels" (not set in that function since needs data)
Returns
0 if the spherical points coordinates are well loaded
Definition at line 9 of file prIcosahedronSamples.cpp.
References coordsPath, prXML::doc, nbVertices, prXML::node, samplesCoords, subdivLevels, prXML::xmlC2S(), prXML::xmlReadDoubleChild(), and prXML::xmlReadIntChild().
Referenced by prRegularlySampledCSImage< T >::loadSphere().
loadVoronoiSamples()
int prIcosahedronSamples::loadVoronoiSamples (unsigned int subdivLevels)
Allocate and fill in the array containing the 3D coordinates of the Voronoi cells of the Icosahedron.
Returns
0 if the spherical points coordinates are well loaded
Definition at line 79 of file prIcosahedronSamples.cpp.
References coordsPath, prXML::doc, nbVertices, prXML::node, samplesCoords, samplesVoronoiMap, subdivLevels, prXML::xmlC2S(), prXML::xmlReadDoubleChild(), and prXML::xmlReadIntChild().
Referenced by prVoronoiIcosahedronImageMapping< T >::loadSphere().
operator=()
prIcosahedronSamples & prIcosahedronSamples::operator= (const prIcosahedronSamples & icoS) inline
Definition at line 66 of file prIcosahedronSamples.h.
References coordsPath, dist, nbVertices, neighMap, and subdivLevels.
setPath()
void prXML::setPath (std::string nPath) protected inherited
Sets the XML filename.
Parameters
nPath the XML filename string
Returns
Nothing
Definition at line 33 of file prXML.cpp.
References prXML::file.
Referenced by prXML::prXML().
xmlC2S()
std::string prXML::xmlC2S (const xmlChar * str) static protected inherited
Converts a characters string from the xmlChar type to the std::sting type.
Parameters
str the xmlChar type characters string
Returns
the converted string
Definition at line 89 of file prXML.cpp.
References prIntensity< Ts, Tcam >::prIntensity().
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), loadDelaunaySamples(), loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), and prStereoModelXML::readSystem().
xmlEndAccessFile()
void prXML::xmlEndAccessFile () protected inherited
Close the XML file.
Returns
Nothing
Definition at line 49 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), prStereoModelXML::operator<<(), prStereoModelXML::operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), prStereoModelXML::operator>>(), and prStereoModelXML::operator>>().
xmlOpenToParse()
void prXML::xmlOpenToParse () protected inherited
Open the XML file for reading.
Returns
Nothing
Definition at line 14 of file prXML.cpp.
References prXML::doc, prXML::file, and prXML::node.
Referenced by prStereoModelXML::operator>>(), prCameraModelXML::operator>>(), prOmniXML::operator>>(), prStereoModelXML::operator>>(), and prStereoModelXML::operator>>().
xmlOpenToWrite()
void prXML::xmlOpenToWrite () protected inherited
Open the XML file for writing.
Returns
Nothing
Definition at line 22 of file prXML.cpp.
References prXML::doc, prXML::file, and prXML::node.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and prStereoModelXML::operator<<().
xmlReadCharChild()
void prXML::xmlReadCharChild (xmlDocPtr & doc, xmlNodePtr & node, char ** res) static protected inherited
Reads the next child of a XML tree node of type char.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res a pointer to the array of char that will contain the reading as output
Returns
Nothing
Definition at line 53 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), and prOmniXML::getModel().
xmlReadDoubleChild()
void prXML::xmlReadDoubleChild (xmlDocPtr & doc, xmlNodePtr node, double & res) static protected inherited
Reads the next child of a XML tree node of type double.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the double variable that will contain the reading as output
Returns
Nothing
Definition at line 75 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), loadDelaunaySamples(), loadVoronoiSamples(), and prStereoModelXML::readSystem().
xmlReadIntChild()
void prXML::xmlReadIntChild (xmlDocPtr & doc, xmlNodePtr & node, int & res) static protected inherited
Reads the next child of a XML tree node of type int.
Parameters
doc the XML document smart pointer
node the XML node smart pointer
res the int variable that will contain the reading as output
Returns
Nothing
Definition at line 61 of file prXML.cpp.
References prXML::doc.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), loadDelaunaySamples(), loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prStereoModelXML::readNbCams(), and prStereoModelXML::readSystem().
xmlWriteToFile()
void prXML::xmlWriteToFile () inherited
Effectively write the XML tree to a file.
Returns
the converted string
Definition at line 43 of file prXML.cpp.
References prXML::doc, and prXML::file.
Referenced by prCameraModelXML::operator<<(), prOmniXML::operator<<(), and prStereoModelXML::operator<<().
Member Data Documentation
coordsPath
std::string prIcosahedronSamples::coordsPath
Definition at line 79 of file prIcosahedronSamples.h.
Referenced by loadDelaunaySamples(), loadVoronoiSamples(), operator=(), and prIcosahedronSamples().
dist
double prIcosahedronSamples::dist
Definition at line 76 of file prIcosahedronSamples.h.
Referenced by createNeighborMap(), and operator=().
doc
xmlDocPtr prXML::doc protected inherited
Smart pointer to a XML document
Definition at line 28 of file prXML.h.
Referenced by prCameraModelXML::getModel(), prOmniXML::getModel(), prCameraModelXML::getModelType(), loadDelaunaySamples(), loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), prStereoModelXML::readSystem(), prXML::xmlEndAccessFile(), prXML::xmlOpenToParse(), prXML::xmlOpenToWrite(), prXML::xmlReadCharChild(), prXML::xmlReadDoubleChild(), prXML::xmlReadIntChild(), and prXML::xmlWriteToFile().
file
std::string prXML::file protected inherited
XML filename
Definition at line 29 of file prXML.h.
Referenced by prXML::getPath(), prXML::setPath(), prXML::xmlOpenToParse(), prXML::xmlOpenToWrite(), and prXML::xmlWriteToFile().
maxSubdivLevels
unsigned int prIcosahedronSamples::maxSubdivLevels
Definition at line 81 of file prIcosahedronSamples.h.
Referenced by prRegularlySampledCSImage< T >::loadSphere(), prVoronoiIcosahedronImageMapping< T >::loadSphere(), and prIcosahedronSamples().
nbVertices
int prIcosahedronSamples::nbVertices
Definition at line 77 of file prIcosahedronSamples.h.
Referenced by createNeighborMap(), loadDelaunaySamples(), prRegularlySampledCSImage< T >::loadSphere(), prVoronoiIcosahedronImageMapping< T >::loadSphere(), loadVoronoiSamples(), and operator=().
neighMap
std::map<unsigned int, std::vector<unsigned int> > prIcosahedronSamples::neighMap
Definition at line 82 of file prIcosahedronSamples.h.
Referenced by createNeighborMap(), and operator=().
node
xmlNodePtr prXML::node protected inherited
Smart pointer to a XML tree node
Definition at line 27 of file prXML.h.
Referenced by loadDelaunaySamples(), loadVoronoiSamples(), prStereoModelXML::readCameraTypes(), prCameraModelXML::readModel(), prStereoModelXML::readNbCams(), prStereoModelXML::readSystem(), prCameraModelXML::writeModel(), prStereoModelXML::writeSystem(), prXML::xmlOpenToParse(), and prXML::xmlOpenToWrite().
samplesCoords
prCartesian3DPointVec* prIcosahedronSamples::samplesCoords
Definition at line 80 of file prIcosahedronSamples.h.
Referenced by createNeighborMap(), loadDelaunaySamples(), prRegularlySampledCSImage< T >::loadSphere(), prVoronoiIcosahedronImageMapping< T >::loadSphere(), and loadVoronoiSamples().
samplesVoronoiMap
std::map<unsigned int, std::vector<prCartesian3DPointVec> > prIcosahedronSamples::samplesVoronoiMap
Definition at line 83 of file prIcosahedronSamples.h.
Referenced by prVoronoiIcosahedronImageMapping< T >::loadSphere(), and loadVoronoiSamples().
subdivLevels
unsigned int prIcosahedronSamples::subdivLevels
Definition at line 78 of file prIcosahedronSamples.h.
Referenced by loadDelaunaySamples(), loadVoronoiSamples(), and operator=().