PER: prVoronoiIcosahedronImageMapping< T > Class Template Reference
prVoronoiIcosahedronImageMapping< T > Class Template Reference
#include <prVoronoiIcosahedronImageMapping.h>
Public Member Functions
prVoronoiIcosahedronImageMapping (unsigned int _subdivLevels=3)
int loadSphere ()
~prVoronoiIcosahedronImageMapping ()
int createImageCellsMap (prStereoModel &stereoCam)
int createImageCellsMap (prEquirectangular &equiCam)
int buildFromTwinOmni (vpImage< T > &I, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int buildFromTwinOmni (cv::Mat &I, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int toTwinOmni (vpImage< T > &I_r, vpPoseVector &r, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int toImage (vpImage< T > &I_r, vpImage< unsigned char > *Mask=NULL)
int toImage (cv::Mat &I_r, vpImage< unsigned char > *Mask=NULL)
int toImageF (cv::Mat &I_r, vpImage< unsigned char > *Mask=NULL)
int toImageRotate (cv::Mat &I_r, vpPoseVector &r)
int buildFromEquiRect (vpImage< T > &I, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
int buildFromEquiRect (cv::Mat I, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
Public Member Functions inherited from prRegularlySampledCSImage< T >
prRegularlySampledCSImage (unsigned int _subdivLevels=3)
virtual ~prRegularlySampledCSImage () override
int loadSphere ()
int buildFromTwinOmni (vpImage< T > &I, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int toTwinOmni (vpImage< T > &I_r, vpPoseVector &r, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int toVectorsAndIntensities (std::vector< std::vector< double > > &vecint)
int buildFromEquiRect (vpImage< T > &I, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
int toEquiRect (vpImage< T > &I_r, vpPoseVector &r, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
std::vector< unsigned int > get3ClosestPoints (prCartesian3DPointVec pt)
int getRawSample (unsigned long i, prCartesian3DPointVec &pXS, T &val)
int getSample (unsigned long i, prCartesian3DPointVec &pXS, float &val)
prRegularlySampledCSImage< T > & operator= (const prRegularlySampledCSImage< T > &RSCSI)
unsigned int getSampleDim ()
int changeSampleFrame (unsigned long &ns, vpHomogeneousMatrix &dMc, prCartesian3DPointVec &XS, double &rho)
int getSampleRho (unsigned long &ns, double &rho)
vpImage< T > getSampledImage ()
prRegularlySampledCSImage (unsigned int _subdivLevels=3)
virtual ~prRegularlySampledCSImage () override
int loadSphere ()
int buildFromTwinOmni (vpImage< T > &I, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int toTwinOmni (vpImage< T > &I_r, vpPoseVector &r, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int buildFromEquiRect (vpImage< T > &I, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
int toEquiRect (vpImage< T > &I_r, vpPoseVector &r, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
int getRawSample (unsigned long i, prCartesian3DPointVec &pXS, T &val)
int getSample (unsigned long i, prCartesian3DPointVec &pXS, float &val)
prRegularlySampledCSImage< T > & operator= (const prRegularlySampledCSImage< T > &RSCSI)
unsigned int getSampleDim ()
int changeSampleFrame (unsigned long &ns, vpHomogeneousMatrix &dMc, prCartesian3DPointVec &XS, double &rho)
int getSampleRho (unsigned long &ns, double &rho)
vpImage< T > getSampledImage ()
Public Member Functions inherited from prAcquisitionModel< T >
prAcquisitionModel ()
virtual ~prAcquisitionModel ()
void setInterpType (prInterpType inttyp_)
unsigned long getNbSamples ()
int toAbsZN ()
Public Attributes
std::map< unsigned int, std::vector< prCartesian3DPointVec > > voroSamples
std::vector< Eigen::ArrayXXd > verticeHexaVec
Eigen::ArrayXXd centerCoords
std::vector< Eigen::MatrixXd > vecVoroContours
std::vector< std::vector< Eigen::MatrixXd > > vecTotVoroContours
double sumTotColors
bool isCellMapInit
int imWidth
int imHeight
Public Attributes inherited from prRegularlySampledCSImage< T >
unsigned int subdivLevels
vpImage< T > I_req
vpImage< unsigned char > MaskS
float * bitmapfUpdated
Public Attributes inherited from prAcquisitionModel< T >
prInterpType inttyp
prGeometricElement * ge
unsigned long nbSamples
T * bitmap
float * bitmapf
bool isBitmapfSet
Detailed Description
template<typename T>
class prVoronoiIcosahedronImageMapping< T >
Definition at line 39 of file prVoronoiIcosahedronImageMapping.h.
Constructor & Destructor Documentation
prVoronoiIcosahedronImageMapping()
template<typename T > prVoronoiIcosahedronImageMapping< T >::prVoronoiIcosahedronImageMapping (unsigned int _subdivLevels = 3) inline
Definition at line 41 of file prVoronoiIcosahedronImageMapping.h.
~prVoronoiIcosahedronImageMapping()
template<typename T > prVoronoiIcosahedronImageMapping< T >::~prVoronoiIcosahedronImageMapping () inline
Definition at line 76 of file prVoronoiIcosahedronImageMapping.h.
Member Function Documentation
buildFromEquiRect() [1/2]
template<typename T > int prVoronoiIcosahedronImageMapping< T >::buildFromEquiRect (cv::Mat I, prEquirectangular & equiCam, vpImage< unsigned char > * Mask = NULL) inline
Definition at line 820 of file prVoronoiIcosahedronImageMapping.h.
buildFromEquiRect() [2/2]
template<typename T > int prVoronoiIcosahedronImageMapping< T >::buildFromEquiRect (vpImage< T > & I, prEquirectangular & equiCam, vpImage< unsigned char > * Mask = NULL) inline
Definition at line 767 of file prVoronoiIcosahedronImageMapping.h.
buildFromTwinOmni() [1/2]
template<typename T > int prVoronoiIcosahedronImageMapping< T >::buildFromTwinOmni (cv::Mat & I, prStereoModel & stereoCam, vpImage< unsigned char > * Mask = NULL) inline
Definition at line 468 of file prVoronoiIcosahedronImageMapping.h.
buildFromTwinOmni() [2/2]
template<typename T > int prVoronoiIcosahedronImageMapping< T >::buildFromTwinOmni (vpImage< T > & I, prStereoModel & stereoCam, vpImage< unsigned char > * Mask = NULL) inline
Definition at line 409 of file prVoronoiIcosahedronImageMapping.h.
createImageCellsMap() [1/2]
template<typename T > int prVoronoiIcosahedronImageMapping< T >::createImageCellsMap (prEquirectangular & equiCam) inline
Definition at line 206 of file prVoronoiIcosahedronImageMapping.h.
References prPointFeature::get_u(), prPointFeature::get_v(), prCameraModel::meterPixelConversion(), prEquirectangular::project3DImage(), and prPointFeature::sX.
createImageCellsMap() [2/2]
template<typename T > int prVoronoiIcosahedronImageMapping< T >::createImageCellsMap (prStereoModel & stereoCam) inline
Definition at line 78 of file prVoronoiIcosahedronImageMapping.h.
References prCartesian3DPointVec::changeFrame(), prPointFeature::get_u(), prPointFeature::get_v(), prPointFeature::get_Z(), prStereoModel::sen, prStereoModel::sjMr, and prPointFeature::sX.
loadSphere()
template<typename T > int prVoronoiIcosahedronImageMapping< T >::loadSphere () inline
Definition at line 47 of file prVoronoiIcosahedronImageMapping.h.
References prCartesian3DPointVec::get_W(), prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), prIcosahedronSamples::loadVoronoiSamples(), prIcosahedronSamples::maxSubdivLevels, prIcosahedronSamples::nbVertices, prIcosahedronSamples::samplesCoords, prIcosahedronSamples::samplesVoronoiMap, and prCartesian3DPointVec::set().
toImage() [1/2]
template<typename T > int prVoronoiIcosahedronImageMapping< T >::toImage (cv::Mat & I_r, vpImage< unsigned char > * Mask = NULL) inline
Definition at line 641 of file prVoronoiIcosahedronImageMapping.h.
toImage() [2/2]
template<typename T > int prVoronoiIcosahedronImageMapping< T >::toImage (vpImage< T > & I_r, vpImage< unsigned char > * Mask = NULL) inline
Definition at line 620 of file prVoronoiIcosahedronImageMapping.h.
toImageF()
template<typename T > int prVoronoiIcosahedronImageMapping< T >::toImageF (cv::Mat & I_r, vpImage< unsigned char > * Mask = NULL) inline
Definition at line 667 of file prVoronoiIcosahedronImageMapping.h.
toImageRotate()
template<typename T > int prVoronoiIcosahedronImageMapping< T >::toImageRotate (cv::Mat & I_r, vpPoseVector & r) inline
Definition at line 688 of file prVoronoiIcosahedronImageMapping.h.
References prCartesian3DPointVec::changeFrame(), prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), and prPointFeature::sX.
toTwinOmni()
template<typename T > int prVoronoiIcosahedronImageMapping< T >::toTwinOmni (vpImage< T > & I_r, vpPoseVector & r, prStereoModel & stereoCam, vpImage< unsigned char > * Mask = NULL) inline
Definition at line 534 of file prVoronoiIcosahedronImageMapping.h.
References prCartesian3DPointVec::changeFrame(), prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), prStereoModel::sjMr, and prPointFeature::sX.
Member Data Documentation
centerCoords
template<typename T > Eigen::ArrayXXd prVoronoiIcosahedronImageMapping< T >::centerCoords
Definition at line 875 of file prVoronoiIcosahedronImageMapping.h.
imHeight
template<typename T > int prVoronoiIcosahedronImageMapping< T >::imHeight
Definition at line 880 of file prVoronoiIcosahedronImageMapping.h.
imWidth
template<typename T > int prVoronoiIcosahedronImageMapping< T >::imWidth
Definition at line 880 of file prVoronoiIcosahedronImageMapping.h.
isCellMapInit
template<typename T > bool prVoronoiIcosahedronImageMapping< T >::isCellMapInit
Definition at line 879 of file prVoronoiIcosahedronImageMapping.h.
sumTotColors
template<typename T > double prVoronoiIcosahedronImageMapping< T >::sumTotColors
Definition at line 878 of file prVoronoiIcosahedronImageMapping.h.
vecTotVoroContours
template<typename T > std::vector<std::vector<Eigen::MatrixXd> > prVoronoiIcosahedronImageMapping< T >::vecTotVoroContours
Definition at line 877 of file prVoronoiIcosahedronImageMapping.h.
vecVoroContours
template<typename T > std::vector<Eigen::MatrixXd> prVoronoiIcosahedronImageMapping< T >::vecVoroContours
Definition at line 876 of file prVoronoiIcosahedronImageMapping.h.
verticeHexaVec
template<typename T > std::vector<Eigen::ArrayXXd> prVoronoiIcosahedronImageMapping< T >::verticeHexaVec
Definition at line 874 of file prVoronoiIcosahedronImageMapping.h.
voroSamples
template<typename T > std::map<unsigned int, std::vector<prCartesian3DPointVec> > prVoronoiIcosahedronImageMapping< T >::voroSamples
Definition at line 873 of file prVoronoiIcosahedronImageMapping.h.
The documentation for this class was generated from the following file:
libPeR_base/modules/acquisition_representation/include/per/acquisition_representation/prVoronoiIcosahedronImageMapping.h