PER: prPolyCart Class Reference
prPolyCart Class Reference
#include <per/prPolyCart.h>
Public Member Functions
prPolyCart (double au=0, double u0=0, double v0=0, double *a=NULL, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0)
virtual ~prPolyCart () override=default
void init (double au=0, double u0=0, double v0=0, double *a=NULL, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0)
double geta0 ()
double geta1 ()
double geta2 ()
double geta3 ()
double geta4 ()
void project3DImage (prPointFeature &P)
bool unProject (prPointFeature &P, double &Depth)
void project3DSphere (prPointFeature &P, double &Xs, double &Ys, double &Zs)
virtual bool projectImageSphere (prPointFeature &P, double &Xs, double &Ys, double &Zs)
prPolyCart & operator= (const prPolyCart &cam)
void computeSensorJacobian (prPointFeature &P, vpMatrix &LuX)
Public Member Functions inherited from prCameraModel
prCameraModel (double au=0, double av=0, double u0=0, double v0=0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0, double k6=0, double k7=0, double k8=0)
virtual ~prCameraModel () override=default
void init (double au=0, double av=0, double u0=0, double v0=0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0, double k6=0, double k7=0, double k8=0)
void init (const prCameraModel &c)
void meterPixelConversion (prPointFeature &P)
void pixelMeterConversion (prPointFeature &P)
CameraModelType getType ()
std::string getName () const
double getau () const
double getav () const
double getu0 () const
double getv0 () const
double getk1 () const
double getk2 () const
double getk3 () const
double getk4 () const
double getk5 () const
double getk6 () const
double getk7 () const
double getk8 () const
double getik1 () const
double getik2 () const
double getik3 () const
double getik4 () const
double getik5 () const
double getik6 () const
double getik7 () const
double getik8 () const
int getNbActiveParameters () const
int getNbActiveDistorsionParameters () const
vpMatrix getK () const
void setDistorsions (bool d)
void setType (CameraModelType m)
void setName (std::string n)
void setPixelRatio (double au, double av)
void setPrincipalPoint (double u0, double v0)
void setDistorsionParameters (double k1=0, double k2=0, double k3=0, double k4=0, double k5=0, double k6=0, double k7=0, double k8=0)
void setUndistorsionParameters (double ik1=0, double ik2=0, double ik3=0, double ik4=0, double ik5=0, double ik6=0, double ik7=0, double ik8=0)
void setActiveDistorsionParameters (bool k1=true, bool k2=true, bool k3=true, bool k4=true, bool k5=true, bool k6=true, bool k7=true, bool k8=true)
virtual prCameraModel & operator= (const prCameraModel &cam)
virtual std::ostream & operator<< (std::ostream &os)
Public Member Functions inherited from prSensorModel
virtual ~prSensorModel ()=default
Static Public Member Functions
template<typename T >
static void projectImageSphere (T &u, T &v, T *intrinsics, T &Xs, T &Ys, T &Zs)
Public Attributes
double a [5]
Public Attributes inherited from prCameraModel
double au
double av
double u0
double v0
double inv_av
double inv_au
CameraModelType type
std::string name
bool distorsions
double k [8]
bool activek [8]
double ik [8]
int nbActiveParametersBase
int nbActiveParameters
Detailed Description
Class for dealing with the projection functions of a camera modeled with the polynomial Cartesian model of Scaramuzza.
Definition at line 18 of file prPolyCart.h.
Constructor & Destructor Documentation
prPolyCart()
prPolyCart::prPolyCart (double au = 0, double u0 = 0, double v0 = 0, double * a = NULL, double k1 = 0, double k2 = 0, double k3 = 0, double k4 = 0, double k5 = 0)
Contructor of the prPolyCart camera model initializing intrinsic parameters.
Parameters
au the scale factor for both horizontal and vertical image directions from the normalized image plane to the digital image (\alpha_v = \alpha_u)
u0 the horizontal coordinate of the principal point (u_0)
v0 the vertical coordinate of the principal point (v_0)
a coefficients of the Taylor expansion of the distorsions (a = [a0, a1, a2, a3, a4]) // a1 = 0 always to allow derivation (cf. MCPTAM article)
k1 the second order radial distorsion parameter (k_1)
k2 the fourth order radial distorsion parameter (k_2)
k3 the sixth order radial distorsion parameter (k_3)
k4 the first tangential distorsion parameter (k_4)
k5 the second tangential distorsion parameter (k_5)
Definition at line 3 of file prPolyCart.cpp.
References a, prCameraModel::name, prCameraModel::nbActiveParameters, prCameraModel::nbActiveParametersBase, PolyCart, and prCameraModel::type.
~prPolyCart()
prPolyCart::~prPolyCart () override virtual default
Destructor of a prPolyCart object.
Member Function Documentation
computeSensorJacobian()
void prPolyCart::computeSensorJacobian (prPointFeature & P, vpMatrix & LuX) virtual
computes the Jacobian of the sensor digital image point coordinates with respect to the 3D coordinates in the camera frame
Parameters
P the point for which computing the Jacobian
LuX the output Jacobian Matrix
Returns
Nothing
Reimplemented from prCameraModel.
Definition at line 105 of file prPolyCart.cpp.
geta0()
double prPolyCart::geta0 () inline
Accessor to the a0 (a_0) parameter of the prPolyCart sensor model.
Returns
a0
Definition at line 66 of file prPolyCart.h.
Referenced by prCameraModelConvert::FCVreverseConvert(), prCameraModelConvert::KBreverseConvert(), and main().
geta1()
double prPolyCart::geta1 () inline
Accessor to the a1 (a_1) parameter of the prPolyCart sensor model.
Returns
a1
Definition at line 73 of file prPolyCart.h.
Referenced by main().
geta2()
double prPolyCart::geta2 () inline
Accessor to the a2 (a_2) parameter of the prPolyCart sensor model.
Returns
a2
Definition at line 80 of file prPolyCart.h.
Referenced by prCameraModelConvert::FCVreverseConvert(), prCameraModelConvert::KBreverseConvert(), and main().
geta3()
double prPolyCart::geta3 () inline
Accessor to the a3 (a_3) parameter of the prPolyCart sensor model.
Returns
a3
Definition at line 87 of file prPolyCart.h.
Referenced by prCameraModelConvert::FCVreverseConvert(), prCameraModelConvert::KBreverseConvert(), and main().
geta4()
double prPolyCart::geta4 () inline
Accessor to the a4 (a_4) parameter of the prPolyCart sensor model.
Returns
a4
Definition at line 94 of file prPolyCart.h.
Referenced by prCameraModelConvert::FCVreverseConvert(), prCameraModelConvert::KBreverseConvert(), and main().
init()
void prPolyCart::init (double au = 0, double u0 = 0, double v0 = 0, double * a = NULL, double k1 = 0, double k2 = 0, double k3 = 0, double k4 = 0, double k5 = 0)
Initializing intrinsic parameters.
Parameters
au the scale factor for both horizontal and vertical image directions from the normalized image plane to the digital image (\alpha_v = \alpha_u)
u0 the horizontal coordinate of the principal point (u_0)
v0 the vertical coordinate of the principal point (v_0)
a coefficients of the Taylor expansion of the distorsions (a = [a0, a1, a2, a3, a4])
k1 the second order radial distorsion parameter (k_1)
k2 the fourth order radial distorsion parameter (k_2)
k3 the sixth order radial distorsion parameter (k_3)
k4 the first tangential distorsion parameter (k_4)
k5 the second tangential distorsion parameter (k_5)
Returns
Nothing
Definition at line 24 of file prPolyCart.cpp.
References a, prCameraModel::init(), prCameraModel::name, PolyCart, and prCameraModel::type.
Referenced by prCameraModelConvert::convert(), and main().
operator=()
prPolyCart & prPolyCart::operator= (const prPolyCart & cam)
= operator overload for copying a prPolyCart camera model
Parameters
cam the source prPolyCart
Returns
the affected prPolyCart.
Definition at line 95 of file prPolyCart.cpp.
References a, and prCameraModel::operator=().
project3DImage()
void prPolyCart::project3DImage (prPointFeature & P) virtual
Project a 3D point expressed in the camera frame to the normalized image plane.
Parameters
P the point to project
Returns
Nothing
Implements prCameraModel.
Definition at line 58 of file prPolyCart.cpp.
project3DSphere()
void prPolyCart::project3DSphere (prPointFeature & P, double & Xs, double & Ys, double & Zs)
Project a 3D point expressed in the camera frame to the unit sphere centered at the camera optical center.
Parameters
P the point to project
Xs the Cartesian X coordinate of the projected point on the unit sphere
Ys the Cartesian Y coordinate of the projected point on the unit sphere
Zs the Cartesian Z coordinate of the projected point on the unit sphere
Returns
Nothing
Definition at line 43 of file prPolyCart.cpp.
References prPointFeature::get_X(), prPointFeature::get_Y(), and prPointFeature::get_Z().
projectImageSphere() [1/2]
bool prPolyCart::projectImageSphere (prPointFeature & P, double & Xs, double & Ys, double & Zs) virtual
Inverse projection from the normalized image plane to the unit sphere centered at the camera optical center.
Parameters
P the point to backproject
Xs the Cartesian X coordinate of the projected point on the unit sphere
Ys the Cartesian Y coordinate of the projected point on the unit sphere
Zs the Cartesian Z coordinate of the projected point on the unit sphere
Returns
true
Implements prCameraModel.
Definition at line 77 of file prPolyCart.cpp.
References a, prCameraModel::au, prPointFeature::get_u(), prPointFeature::get_v(), prCameraModel::u0, and prCameraModel::v0.
projectImageSphere() [2/2]
template<typename T > static void prPolyCart::projectImageSphere (T & u, T & v, T * intrinsics, T & Xs, T & Ys, T & Zs) inline static
Definition at line 147 of file prPolyCart.h.
unProject()
bool prPolyCart::unProject (prPointFeature & P, double & Depth) virtual
Compute the 3D point expressed in the sensor frame from the normalized image plane and the depth (must be implemented in a specified sensor model)
Parameters
P the point to unproject
Depth the Depth used to unproject the P (/rho here...)
Returns
true if unprojection could be done
Implements prCameraModel.
Definition at line 70 of file prPolyCart.cpp.
Member Data Documentation
a
double prPolyCart::a[5]
Polynomial Cartesian model parameters: coefficients of the Taylor expansion of the distorsions
Definition at line 20 of file prPolyCart.h.
Referenced by init(), operator=(), projectImageSphere(), and prPolyCart().
The documentation for this class was generated from the following files:
libPeR_base/modules/core/include/per/core/prPolyCart.h
libPeR_base/modules/core/src/prPolyCart.cpp