PER: prPosePerspectiveEstim< FSetT, FSetCmpT > Class Template Reference
prPosePerspectiveEstim< FSetT, FSetCmpT > Class Template Reference
#include <prPosePerspectiveEstim.h>
Public Member Functions
prPosePerspectiveEstim ()
virtual ~prPosePerspectiveEstim () override
void setdof (bool tX=true, bool tY=true, bool tZ=true, bool rX=true, bool rY=true, bool rZ=true)
void buildFrom (FSetT &FeatureSet_)
void startSaveIterations (char *fileName)
void stopSaveIterations ()
double track (FSetT &FeatureSetd, vpPoseVector &r_optim, bool robust=false)
void initControl (float lambda_=1.f, float cst_Z=1.f, bool current_=true)
void initPointFeatures ()
void computePointJacobian (prPointFeature &P, vpMatrix &Ls, double au=1.0, double av=1.0, double *Z=nullptr)
void setSensor (prSensorModel *sensor)
void computePoseJacobian (FSetT &FeatureSetc)
void composeFeaturesPoseJacobians (vpMatrix &LfRaw, vpMatrix &Lug, vpMatrix &LsRaw)
double control (FSetT &FeatureSetc, vpColVector &v, bool robust=false)
double getCond (bool robust=false)
void computeScenePointJacobian (prPointFeature &P, vpMatrix &LX)
double interactionAndError (FSetT &FeatureSetc, vpMatrix &Lc, vpColVector &errc, bool robust=false)
Detailed Description
template<class FSetT, class FSetCmpT>
class prPosePerspectiveEstim< FSetT, FSetCmpT >
Definition at line 31 of file prPosePerspectiveEstim.h.
Constructor & Destructor Documentation
prPosePerspectiveEstim()
template<class FSetT , class FSetCmpT > prPosePerspectiveEstim< FSetT, FSetCmpT >::prPosePerspectiveEstim () inline
Contructor of the prPosePerspectiveEstim.
Definition at line 39 of file prPosePerspectiveEstim.h.
~prPosePerspectiveEstim()
template<class FSetT , class FSetCmpT > prPosePerspectiveEstim< FSetT, FSetCmpT >::~prPosePerspectiveEstim () inline override virtual
Destructor of a prPosePerspectiveEstim object.
Definition at line 48 of file prPosePerspectiveEstim.h.
Member Function Documentation
buildFrom()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::buildFrom (FSetT & FeatureSet_) inline
Build the features set of reference for the pose estimator.
Parameters
I_ the source image
Returns
Nothing
Definition at line 81 of file prPosePerspectiveEstim.h.
composeFeaturesPoseJacobians()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::composeFeaturesPoseJacobians (vpMatrix & LfRaw, vpMatrix & Lug, vpMatrix & LsRaw) inline
Definition at line 480 of file prPosePerspectiveEstim.h.
computePointJacobian()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::computePointJacobian (prPointFeature & P, vpMatrix & Ls, double au = 1.0, double av = 1.0, double * Z = nullptr) inline
Definition at line 405 of file prPosePerspectiveEstim.h.
computePoseJacobian()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::computePoseJacobian (FSetT & FeatureSetc) inline
Definition at line 436 of file prPosePerspectiveEstim.h.
computeScenePointJacobian()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::computeScenePointJacobian (prPointFeature & P, vpMatrix & LX) inline inherited
Compute the Jacobian of a 3D point with repsect to the sensor pose.
Parameters
P the point feature
LX the output interaction matrix of a 3D point (size: 3x6)
Definition at line 192 of file prCameraPoseEstim.h.
control()
template<class FSetT , class FSetCmpT > double prPosePerspectiveEstim< FSetT, FSetCmpT >::control (FSetT & FeatureSetc, vpColVector & v, bool robust = false) inline
Compute the pose increment to move FeatureSetc toward FeatureSet.
Parameters
FeatureSetc the current feature set
v the 6-vector that contains pose increment values
Returns
the residual at convergence or -1 if control not initialized
Definition at line 536 of file prPosePerspectiveEstim.h.
References prIntensity< Ts, Tcam >::prIntensity(), and prIntensity< Ts, Tcam >::toDouble().
getCond()
template<class FSetT , class FSetCmpT > double prPosePerspectiveEstim< FSetT, FSetCmpT >::getCond (bool robust = false) inline
Definition at line 675 of file prPosePerspectiveEstim.h.
initControl()
template<class FSetT , class FSetCmpT > double prPosePerspectiveEstim< FSetT, FSetCmpT >::initControl (float lambda_ = 1.f, float cst_Z = 1.f, bool current_ = true) inline
Compute the pose increment to move FeatureSetc toward FeatureSet.
Parameters
FeatureSetc the current feature set
v the 6-vector that contains pose increment values
Returns
the residual at convergence
Definition at line 344 of file prPosePerspectiveEstim.h.
initPointFeatures()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::initPointFeatures () inline
Definition at line 384 of file prPosePerspectiveEstim.h.
interactionAndError()
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::interactionAndError (FSetT & FeatureSetc, vpMatrix & Lc, vpColVector & errc, bool robust = false) inline inherited
Compute the interaction matrix and error vector of FeatureSetc.
Parameters
FeatureSetc the current feature set
Lc the matrix that contains the interaction matrix
errc the column vector that contains the error vector
Returns
the residual or -1 if control not initialized
Definition at line 350 of file prCameraPoseEstim.h.
References prIntensity< Ts, Tcam >::prIntensity(), and prIntensity< Ts, Tcam >::toDouble().
setdof()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::setdof (bool tX = true, bool tY = true, bool tZ = true, bool rX = true, bool rY = true, bool rZ = true) inline
Definition at line 65 of file prPosePerspectiveEstim.h.
setSensor()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::setSensor (prSensorModel * sensor) inline
Definition at line 431 of file prPosePerspectiveEstim.h.
startSaveIterations()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::startSaveIterations (char * fileName) inline
Opens the file in which estimation iterations will be saved.
Parameters
fileName the filename
Returns
Nothing
Definition at line 92 of file prPosePerspectiveEstim.h.
stopSaveIterations()
template<class FSetT , class FSetCmpT > void prPosePerspectiveEstim< FSetT, FSetCmpT >::stopSaveIterations () inline
Closes the file in which estimation iterations are saved.
Returns
Nothing
Definition at line 104 of file prPosePerspectiveEstim.h.
track()
template<class FSetT , class FSetCmpT > double prPosePerspectiveEstim< FSetT, FSetCmpT >::track (FSetT & FeatureSetd, vpPoseVector & r_optim, bool robust = false) inline
Update the pose of FeatureSet so that it matches FeatureSetd.
Parameters
FeatureSetd the input image toward which degrees of freedom will have an impact on FeatureSet
r the 6-vector that contains pose elements values
Returns
the residual error at convergence
Definition at line 117 of file prPosePerspectiveEstim.h.