PER: prRegularlySampledCSImageDepth< TImage > Class Template Reference
prRegularlySampledCSImageDepth< TImage > Class Template Reference
#include <prRegularlySampledCSImageDepth.h>
Public Member Functions
prRegularlySampledCSImageDepth (unsigned int _subdivLevels=3)
virtual ~prRegularlySampledCSImageDepth () override
int buildFromEquiRect (vpImage< TImage > &I, vpImage< TDepth > &depthmap, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL, vpHomogeneousMatrix *cMi=NULL)
int toEquiRect (vpImage< TImage > &I_r, vpPoseVector &r, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
int getRawSample (unsigned long i, prCartesian3DPointVec &pXS, TImage &val)
int getSample (unsigned long i, prCartesian3DPointVec &pXS, float &val)
prRegularlySampledCSImageDepth< TImage > & operator= (const prRegularlySampledCSImageDepth< TImage > &RSCSID)
unsigned int getSampleDim ()
int changeSampleFrame (unsigned long &ns, vpHomogeneousMatrix &dMc, prCartesian3DPointVec &XS, double &rho)
int getSampleRho (unsigned long &ns, double &rho)
int loadSphere ()
int loadSphere ()
int buildFromTwinOmni (vpImage< TImage > &I, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int buildFromTwinOmni (vpImage< TImage > &I, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int toTwinOmni (vpImage< TImage > &I_r, vpPoseVector &r, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int toTwinOmni (vpImage< TImage > &I_r, vpPoseVector &r, prStereoModel &stereoCam, vpImage< unsigned char > *Mask=NULL)
int toVectorsAndIntensities (std::vector< std::vector< double > > &vecint)
int buildFromEquiRect (vpImage< TImage > &I, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
int toEquiRect (vpImage< TImage > &I_r, vpPoseVector &r, prEquirectangular &equiCam, vpImage< unsigned char > *Mask=NULL)
std::vector< unsigned int > get3ClosestPoints (prCartesian3DPointVec pt)
int getRawSample (unsigned long i, prCartesian3DPointVec &pXS, TImage &val)
vpImage< TImage > getSampledImage ()
vpImage< TImage > getSampledImage ()
void setInterpType (prInterpType inttyp_)
unsigned long getNbSamples ()
int toAbsZN ()
Public Attributes
TDepth * bitmapDepth
prGeometricElement * ge3DSpace
bool isGe3DSpaceSet
unsigned int subdivLevels
vpImage< TImage > I_req
vpImage< unsigned char > MaskS
float * bitmapfUpdated
prInterpType inttyp
prGeometricElement * ge
unsigned long nbSamples
T * bitmap
float * bitmapf
bool isBitmapfSet
Detailed Description
template<typename TImage>
class prRegularlySampledCSImageDepth< TImage >
Definition at line 31 of file prRegularlySampledCSImageDepth.h.
Constructor & Destructor Documentation
prRegularlySampledCSImageDepth()
template<typename TImage > prRegularlySampledCSImageDepth< TImage >::prRegularlySampledCSImageDepth (unsigned int _subdivLevels = 3) inline
Constructor of a prRegularlySampledCSImageDepth object (CS stands for Cartesian Spherical) : initializes the number of subdivision level of the sphere, i.e. the resolution of the spherical image / depth map, and loads the spherical points.
Definition at line 39 of file prRegularlySampledCSImageDepth.h.
References prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), and prCartesian3DPointVec::setPoint().
~prRegularlySampledCSImageDepth()
template<typename TImage > prRegularlySampledCSImageDepth< TImage >::~prRegularlySampledCSImageDepth () inline override virtual
Destructor of the prRegularlySampledCSImageDepth object : frees memory of depthmap values (the rest is done by the parent class).
Definition at line 70 of file prRegularlySampledCSImageDepth.h.
Member Function Documentation
buildFromEquiRect() [1/2]
int prRegularlySampledCSImage< TImage >::buildFromEquiRect (vpImage< TImage > & I, prEquirectangular & equiCam, vpImage< unsigned char > * Mask = NULL) inline inherited
Builds the pixels map of the spherical image from the acquired equirectangular image data TODO: to generalize for other sensor types than the equirectangular by merging with buildFromTwinOmni.
spherical image from the acquired equirectangular image data TODO: to generalize for other sensor types than the equirectangular by merging with buildFromTwinOmni
Parameters
I the input image of which pixels are of type T
equiCam the dual omni camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Parameters
I the input image of which pixels are of type T
equiCam the dual omni camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Definition at line 387 of file prRegularlySampledCSImage.h.
buildFromEquiRect() [2/2]
template<typename TImage > int prRegularlySampledCSImageDepth< TImage >::buildFromEquiRect (vpImage< TImage > & I, vpImage< TDepth > & depthmap, prEquirectangular & equiCam, vpImage< unsigned char > * Mask = NULL, vpHomogeneousMatrix * cMi = NULL) inline
Builds the pixels map of the spherical image from the acquired equirectangular image data TODO: to generalize for other sensor types than the equirectangular by merging with buildFromTwinOmni.
Parameters
I the input image of which pixels are of type T
depthmap the input image of which pixels are of type float (move to template to allow double or else?)
equiCam the dual omni camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered)
cMi the pointer to a transformation matrix from frame F_i (usually initial) to frame F_c (usually current) (if NULL, no transformation is considered)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Definition at line 100 of file prRegularlySampledCSImageDepth.h.
References prCartesian3DPointVec::changeFrame(), prPointFeature::get_u(), prPointFeature::get_v(), prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), prCameraModel::meterPixelConversion(), prEquirectangular::project3DImage(), prEquirectangular::project3DSphere(), prCartesian3DPointVec::setPoint(), and prPointFeature::sX.
buildFromTwinOmni() [1/2]
int prRegularlySampledCSImage< TImage >::buildFromTwinOmni (vpImage< TImage > & I, prStereoModel & stereoCam, vpImage< unsigned char > * Mask = NULL) inline inherited
Builds the pixels map of the spherical image from the acquired dual omni image data TODO: to generalize for other sensor types than the dual omni.
spherical image from the acquired dual omni image data TODO: to generalize for other sensor types than the dual omni
Parameters
I the input image of which pixels are of type T
stereoCam the dual omni camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Parameters
I the input image of which pixels are of type T
stereoCam the dual omni camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Definition at line 159 of file prRegularlySampledCSImage.h.
buildFromTwinOmni() [2/2]
int prRegularlySampledCSImage< TImage >::buildFromTwinOmni (vpImage< TImage > & I, prStereoModel & stereoCam, vpImage< unsigned char > * Mask = NULL) inline inherited
Definition at line 104 of file prRegularlySampledCSImage.h.
changeSampleFrame()
template<typename TImage > int prRegularlySampledCSImageDepth< TImage >::changeSampleFrame (unsigned long & ns, vpHomogeneousMatrix & dMc, prCartesian3DPointVec & XS, double & rho) inline
implementation of the changeSampleFrame method to update both the sample location and the depth
Parameters
ns
dMc
XS
rho
Returns
0
Definition at line 458 of file prRegularlySampledCSImageDepth.h.
References prCartesian3DPointVec::changeFrame(), prCartesian3DPointVec::get_X(), prCartesian3DPointVec::get_Y(), prCartesian3DPointVec::get_Z(), and prCartesian3DPointVec::setPoint().
get3ClosestPoints()
std::vector< unsigned int > prRegularlySampledCSImage< TImage >::get3ClosestPoints (prCartesian3DPointVec pt) inline inherited
Definition at line 556 of file prRegularlySampledCSImage.h.
getNbSamples()
template<typename T > unsigned long prAcquisitionModel< T >::getNbSamples () inline inherited
Accessor to the number of spherical samples in the spherical image.
Returns
the number of samples
Definition at line 74 of file prAcquisitionModel.h.
getRawSample() [1/2]
int prRegularlySampledCSImage< TImage >::getRawSample (unsigned long i, prCartesian3DPointVec & pXS, TImage & val) inline inherited
Extract the sample position and raw value at given index.
Parameters
i the index at which to extract the raw
pXS (output) the output coordinates of the sample
val (output) the output raw value at the sample coordinates
Returns
0 if the raw sample could be got -1 if the index is out of range
Definition at line 604 of file prRegularlySampledCSImage.h.
getRawSample() [2/2]
template<typename TImage > int prRegularlySampledCSImageDepth< TImage >::getRawSample (unsigned long i, prCartesian3DPointVec & pXS, TImage & val) inline
Extract the sample position and raw value at given index.
Parameters
i the index at which to extract the raw
pXS (output) the output coordinates of the sample
val (output) the output raw value at the sample coordinates
Returns
0 if the raw sample could be got -1 if the index is out of range
Definition at line 329 of file prRegularlySampledCSImageDepth.h.
getSample()
template<typename TImage > int prRegularlySampledCSImageDepth< TImage >::getSample (unsigned long i, prCartesian3DPointVec & pXS, float & val) inline
Extract the sample position and value (that might have been interpolated) at given index.
Parameters
i the index at which to extract the raw
pXS (output) the output coordinates of the sample
val (output) the output value at the sample coordinates
Returns
0 if the sample could be got -1 if the index is out of range
Definition at line 349 of file prRegularlySampledCSImageDepth.h.
getSampleDim()
template<typename TImage > unsigned int prRegularlySampledCSImageDepth< TImage >::getSampleDim () inline
accessor to the number of dimensions of a point sample TODO: make it more generic
Returns
the number of dimensions of a point sample
Definition at line 444 of file prRegularlySampledCSImageDepth.h.
getSampledImage() [1/2]
vpImage< TImage > prRegularlySampledCSImage< TImage >::getSampledImage () inline inherited
Definition at line 704 of file prRegularlySampledCSImage.h.
getSampledImage() [2/2]
vpImage< TImage > prRegularlySampledCSImage< TImage >::getSampledImage () inline inherited
Definition at line 612 of file prRegularlySampledCSImage.h.
getSampleRho()
template<typename TImage > int prRegularlySampledCSImageDepth< TImage >::getSampleRho (unsigned long & ns, double & rho) inline
accessor to the depth of a spherical point
Parameters
ns
rho
Returns
0
Definition at line 485 of file prRegularlySampledCSImageDepth.h.
loadSphere() [1/2]
int prRegularlySampledCSImage< TImage >::loadSphere () inline inherited
Allocates and fill the array of points coordinates as well as the array of "pixels" (not set in that function since needs data)
Returns
0 if the spherical points coordinates are well loaded -1 if the number of subdivision level is too high
Definition at line 118 of file prRegularlySampledCSImage.h.
loadSphere() [2/2]
int prRegularlySampledCSImage< TImage >::loadSphere () inline inherited
Definition at line 70 of file prRegularlySampledCSImage.h.
operator=()
template<typename TImage > prRegularlySampledCSImageDepth< TImage > & prRegularlySampledCSImageDepth< TImage >::operator= (const prRegularlySampledCSImageDepth< TImage > & RSCSID) inline
= operator override to copy prRegularlySampledCSImage object TODO: better deal with the memcpy when pixels are not of a basic type TODO: check if ge[j] = RSCSI.ge[j]; needs pointer casts
Parameters
RSCSID the prRegularlySampledCSImageDepth to copy to the current
Returns
the prRegularlySampledCSImage<T> self reference object
Definition at line 409 of file prRegularlySampledCSImageDepth.h.
References prAcquisitionModel< T >::bitmap, prRegularlySampledCSImageDepth< TImage >::bitmapDepth, prAcquisitionModel< T >::bitmapf, prAcquisitionModel< T >::ge, prRegularlySampledCSImageDepth< TImage >::ge3DSpace, prAcquisitionModel< T >::inttyp, prAcquisitionModel< T >::isBitmapfSet, prRegularlySampledCSImageDepth< TImage >::isGe3DSpaceSet, prAcquisitionModel< T >::nbSamples, and prRegularlySampledCSImage< T >::subdivLevels.
setInterpType()
template<typename T > void prAcquisitionModel< T >::setInterpType (prInterpType inttyp_) inline inherited
Initialize the type of interpolation to consider for pixel intensities.
Parameters
inttyp_ the interpolation type
Returns
Nothing
Definition at line 64 of file prAcquisitionModel.h.
toAbsZN()
template<typename T > int prAcquisitionModel< T >::toAbsZN () inline inherited
Transform the pixel intensities so that they are zero-mean, normalized, absoluted and normalized again so that their sum is equal to one.
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Definition at line 85 of file prAcquisitionModel.h.
toEquiRect() [1/2]
int prRegularlySampledCSImage< TImage >::toEquiRect (vpImage< TImage > & I_r, vpPoseVector & r, prEquirectangular & equiCam, vpImage< unsigned char > * Mask = NULL) inline inherited
Projects the spherical image to an equirectangular image (mainly for visualization purpose) TODO: to generalize for other sensor types than the equirectangular by merging with toTwinOmni.
image to an equirectangular image (mainly for visualization purpose) TODO: to generalize for other sensor types than the equirectangular by merging with toTwinOmni
Parameters
I_r (output) the output image of which pixels are of type T
r the pose vector of the frame change to apply to the spherical image before projection in the dual omni image plane
equiCam the equirectangular camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered ; if not NULL, masked pixels are not changed)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Parameters
I_r (output) the output image of which pixels are of type T
r the pose vector of the frame change to apply to the spherical image before projection in the dual omni image plane
equiCam the equirectangular camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered ; if not NULL, masked pixels are not changed)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Definition at line 510 of file prRegularlySampledCSImage.h.
toEquiRect() [2/2]
template<typename TImage > int prRegularlySampledCSImageDepth< TImage >::toEquiRect (vpImage< TImage > & I_r, vpPoseVector & r, prEquirectangular & equiCam, vpImage< unsigned char > * Mask = NULL) inline
Projects the spherical image to an equirectangular image (mainly for visualization purpose) TODO: to generalize for other sensor types than the equirectangular by merging with toTwinOmni.
Parameters
I_r (output) the output image of which pixels are of type T
r the pose vector of the frame change to apply to the spherical image before projection in the dual omni image plane
equiCam the equirectangular camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered ; if not NULL, masked pixels are not changed)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Definition at line 268 of file prRegularlySampledCSImageDepth.h.
References prCartesian3DPointVec::changeFrame(), prPointFeature::get_u(), prPointFeature::get_v(), prCameraModel::meterPixelConversion(), prEquirectangular::project3DImage(), and prPointFeature::sX.
toTwinOmni() [1/2]
int prRegularlySampledCSImage< TImage >::toTwinOmni (vpImage< TImage > & I_r, vpPoseVector & r, prStereoModel & stereoCam, vpImage< unsigned char > * Mask = NULL) inline inherited
Projects the spherical image to a dual omni image (mainly for visualization purpose) TODO: to generalize for other sensor types than the dual omni.
spherical image to a dual omni image (mainly for visualization purpose) TODO: to generalize for other sensor types than the dual omni
Parameters
I_r (output) the output image of which pixels are of type T
r the pose vector of the frame change to apply to the spherical image before projection in the dual omni image plane
stereoCam the dual omni camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered ; if not NULL, masked pixels are not changed)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Parameters
I_r (output) the output image of which pixels are of type T
r the pose vector of the frame change to apply to the spherical image before projection in the dual omni image plane
stereoCam the dual omni camera intrinsic and extrinsic parameters
Mask the pointer to a Mask image in order to ignore some pixels (if NULL, every pixel of the input image is considered ; if not NULL, masked pixels are not changed)
Returns
0 if the spherical image is well built -1 if there is no spherical image points loaded
Definition at line 294 of file prRegularlySampledCSImage.h.
toTwinOmni() [2/2]
int prRegularlySampledCSImage< TImage >::toTwinOmni (vpImage< TImage > & I_r, vpPoseVector & r, prStereoModel & stereoCam, vpImage< unsigned char > * Mask = NULL) inline inherited
Definition at line 246 of file prRegularlySampledCSImage.h.
toVectorsAndIntensities()
int prRegularlySampledCSImage< TImage >::toVectorsAndIntensities (std::vector< std::vector< double > > & vecint) inline inherited
Definition at line 349 of file prRegularlySampledCSImage.h.
Member Data Documentation
bitmap
template<typename T > T* prAcquisitionModel< T >::bitmap inherited
linear array of pixels of the spherical image
Definition at line 166 of file prAcquisitionModel.h.
Referenced by prRegularlySampledCPImage< T >::operator=(), prRegularlySampledCSImage< T >::operator=(), and prRegularlySampledCSImageDepth< TImage >::operator=().
bitmapDepth
template<typename TImage > TDepth* prRegularlySampledCSImageDepth< TImage >::bitmapDepth
linear array of pixels of the spherical depthmap
Definition at line 501 of file prRegularlySampledCSImageDepth.h.
Referenced by prRegularlySampledCSImageDepth< TImage >::operator=().
bitmapf
template<typename T > float* prAcquisitionModel< T >::bitmapf inherited
linear array of interpolated pixels of the sperical image
Definition at line 167 of file prAcquisitionModel.h.
Referenced by prRegularlySampledCPImage< T >::operator=(), prRegularlySampledCSImage< T >::operator=(), and prRegularlySampledCSImageDepth< TImage >::operator=().
bitmapfUpdated
float* prRegularlySampledCSImage< TImage >::bitmapfUpdated inherited
Definition at line 721 of file prRegularlySampledCSImage.h.
ge
template<typename T > prGeometricElement* prAcquisitionModel< T >::ge inherited
array of signal sampling elements (usually points)
Definition at line 163 of file prAcquisitionModel.h.
Referenced by prRegularlySampledCPImage< T >::operator=(), prRegularlySampledCSImage< T >::operator=(), and prRegularlySampledCSImageDepth< TImage >::operator=().
ge3DSpace
template<typename TImage > prGeometricElement* prRegularlySampledCSImageDepth< TImage >::ge3DSpace
array of 3D points observed
Definition at line 503 of file prRegularlySampledCSImageDepth.h.
Referenced by prRegularlySampledCSImageDepth< TImage >::operator=().
I_req
vpImage< TImage > prRegularlySampledCSImage< TImage >::I_req inherited
Definition at line 708 of file prRegularlySampledCSImage.h.
inttyp
template<typename T > prInterpType prAcquisitionModel< T >::inttyp inherited
interpolation type
Definition at line 161 of file prAcquisitionModel.h.
Referenced by prRegularlySampledCPImage< T >::operator=(), prRegularlySampledCSImage< T >::operator=(), and prRegularlySampledCSImageDepth< TImage >::operator=().
isBitmapfSet
template<typename T > bool prAcquisitionModel< T >::isBitmapfSet inherited
boolean to know if the bitmap of interpolated pixels is allocated and filled
Definition at line 168 of file prAcquisitionModel.h.
Referenced by prRegularlySampledCPImage< T >::operator=(), prRegularlySampledCSImage< T >::operator=(), and prRegularlySampledCSImageDepth< TImage >::operator=().
isGe3DSpaceSet
template<typename TImage > bool prRegularlySampledCSImageDepth< TImage >::isGe3DSpaceSet
Definition at line 504 of file prRegularlySampledCSImageDepth.h.
Referenced by prRegularlySampledCSImageDepth< TImage >::operator=().
MaskS
vpImage< unsigned char > prRegularlySampledCSImage< TImage >::MaskS inherited
Definition at line 709 of file prRegularlySampledCSImage.h.
nbSamples
template<typename T > unsigned long prAcquisitionModel< T >::nbSamples inherited
number of sample points on the sphere
Definition at line 165 of file prAcquisitionModel.h.
Referenced by prRegularlySampledCPImage< T >::operator=(), prRegularlySampledCSImage< T >::operator=(), and prRegularlySampledCSImageDepth< TImage >::operator=().
subdivLevels
unsigned int prRegularlySampledCSImage< TImage >::subdivLevels inherited
number of subdivision levels of the sphere
Definition at line 707 of file prRegularlySampledCSImage.h.