PER: prPoseSphericalEstim< FSetT, FSetCmpT > Class Template Reference
prPoseSphericalEstim< FSetT, FSetCmpT > Class Template Reference
#include <prPoseSphericalEstim.h>
Public Member Functions
prPoseSphericalEstim (double seuilResidu_=1e-9)
virtual ~prPoseSphericalEstim () override
void setdof (bool tX=true, bool tY=true, bool tZ=true, bool rX=true, bool rY=true, bool rZ=true)
void buildFrom (FSetT &FeatureSet_)
void startSaveIterations (char *fileName)
void stopSaveIterations ()
double track (FSetT &FeatureSetd, vpPoseVector &r_optim, double lambda=1.0, bool robust=false)
void initControl (float lambda_=1.f, bool current_=true)
double control (FSetT &FeatureSetc, vpColVector &v, bool robust=false)
double track (FSetT &FeatureSetd, vpPoseVector &r_optim, bool robust=false)
void initControl (float lambda_=1.f, float cst_Depth=1.f, bool current_=true)
void initPointFeatures ()
void computeScenePointJacobian (prPointFeature &P, vpMatrix &LX)
void setSensor (prSensorModel *sensor)
void computePoseJacobian (FSetT &FeatureSetc)
void composeFeaturesPoseJacobians (vpMatrix &LfRaw, vpMatrix &Lug, vpMatrix &LsRaw)
double interactionAndError (FSetT &FeatureSetc, vpMatrix &Lc, vpColVector &errc, bool robust=false)
double getCond (bool robust=false)
Detailed Description
template<typename FSetT, typename FSetCmpT>
class prPoseSphericalEstim< FSetT, FSetCmpT >
Definition at line 32 of file prPoseSphericalEstim.h.
Constructor & Destructor Documentation
prPoseSphericalEstim()
template<typename FSetT , typename FSetCmpT > prPoseSphericalEstim< FSetT, FSetCmpT >::prPoseSphericalEstim (double seuilResidu_ = 1e-9) inline
Contructor of the prPoseSphericalEstim.
Definition at line 40 of file prPoseSphericalEstim.h.
~prPoseSphericalEstim()
template<typename FSetT , typename FSetCmpT > prPoseSphericalEstim< FSetT, FSetCmpT >::~prPoseSphericalEstim () inline override virtual
Destructor of a prPoseSphericalEstim object.
Definition at line 49 of file prPoseSphericalEstim.h.
Member Function Documentation
buildFrom()
template<typename FSetT , typename FSetCmpT > void prPoseSphericalEstim< FSetT, FSetCmpT >::buildFrom (FSetT & FeatureSet_) inline
Build the features set of reference for the pose estimator.
Parameters
I_ the source image
Returns
Nothing
Definition at line 82 of file prPoseSphericalEstim.h.
composeFeaturesPoseJacobians()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::composeFeaturesPoseJacobians (vpMatrix & LfRaw, vpMatrix & Lug, vpMatrix & LsRaw) inline inherited
computes the Jacobian of the variable sampling the acquisition model with respect to the sensor pose
Parameters
LfRaw features Jacobian of size nb features \times nb dimensions of the sampler elements
Lug sampler's Jacobian of size nb dimensions of the sampler elements * nb features \time nb degrees of freedom
LsRaw output Jacobian matrix resulting of per feature composition of LfRaw and Lug
Definition at line 307 of file prCameraPoseEstim.h.
computePoseJacobian()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::computePoseJacobian (FSetT & FeatureSetc) inline inherited
computes the Jacobian of the variable sampling the acquisition model with respect to the sensor pose
Parameters
FeatureSetc the current feature set
!! specific
!! specific
!! specific
!! specific
!! needs to depend on the acquisition model sampler space
Definition at line 235 of file prCameraPoseEstim.h.
computeScenePointJacobian()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::computeScenePointJacobian (prPointFeature & P, vpMatrix & LX) inline inherited
Compute the Jacobian of a 3D point with repsect to the sensor pose.
Parameters
P the point feature
LX the output interaction matrix of a 3D point (size: 3x6)
Definition at line 192 of file prCameraPoseEstim.h.
control()
template<typename FSetT , typename FSetCmpT > double prPoseSphericalEstim< FSetT, FSetCmpT >::control (FSetT & FeatureSetc, vpColVector & v, bool robust = false) inline
Compute the pose increment to move FeatureSetc toward FeatureSet.
Parameters
FeatureSetc the current feature set
v the 6-vector that contains pose increment values
Returns
the residual at convergence or -1 if control not initialized
Definition at line 400 of file prPoseSphericalEstim.h.
References prIntensity< Ts, Tcam >::prIntensity(), and prIntensity< Ts, Tcam >::toDouble().
getCond()
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::getCond (bool robust = false) inline inherited
Compute the condition number of the interaction matrix.
Parameters
robust to consider the raw of the robustified interaction matrix
Returns
the condition number
Definition at line 634 of file prCameraPoseEstim.h.
initControl() [1/2]
template<typename FSetT , typename FSetCmpT > double prPoseSphericalEstim< FSetT, FSetCmpT >::initControl (float lambda_ = 1.f, bool current_ = true) inline
Initialize the matrices and the control law parameters (gain, ...)
Parameters
lambda_ gain
current_ boolean to set current (true) or desired (false) interaction matrix
Definition at line 349 of file prPoseSphericalEstim.h.
initControl() [2/2]
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::initControl (float lambda_ = 1.f, float cst_Depth = 1.f, bool current_ = true) inline inherited
Compute the pose increment to move FeatureSetc toward FeatureSet.
Parameters
FeatureSetc the current feature set
v the 6-vector that contains pose increment values
Returns
the residual at convergence
Definition at line 129 of file prCameraPoseEstim.h.
initPointFeatures()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::initPointFeatures () inline inherited
e Initialize the table of feature points (digital image plane and normalized image plane) associated to the sampler of the feature set
Definition at line 165 of file prCameraPoseEstim.h.
interactionAndError()
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::interactionAndError (FSetT & FeatureSetc, vpMatrix & Lc, vpColVector & errc, bool robust = false) inline inherited
Compute the interaction matrix and error vector of FeatureSetc.
Parameters
FeatureSetc the current feature set
Lc the matrix that contains the interaction matrix
errc the column vector that contains the error vector
Returns
the residual or -1 if control not initialized
Definition at line 350 of file prCameraPoseEstim.h.
References prIntensity< Ts, Tcam >::prIntensity(), and prIntensity< Ts, Tcam >::toDouble().
setdof()
template<typename FSetT , typename FSetCmpT > void prPoseSphericalEstim< FSetT, FSetCmpT >::setdof (bool tX = true, bool tY = true, bool tZ = true, bool rX = true, bool rY = true, bool rZ = true) inline
Definition at line 66 of file prPoseSphericalEstim.h.
setSensor()
template<class FSetT , class FSetCmpT > void prCameraPoseEstim< FSetT, FSetCmpT >::setSensor (prSensorModel * sensor) inline inherited
sets the camera sensor model
Parameters
sensor the camera model to consider
Definition at line 225 of file prCameraPoseEstim.h.
startSaveIterations()
template<typename FSetT , typename FSetCmpT > void prPoseSphericalEstim< FSetT, FSetCmpT >::startSaveIterations (char * fileName) inline
Opens the file in which estimation iterations will be saved.
Parameters
fileName the filename
Returns
Nothing
Definition at line 93 of file prPoseSphericalEstim.h.
stopSaveIterations()
template<typename FSetT , typename FSetCmpT > void prPoseSphericalEstim< FSetT, FSetCmpT >::stopSaveIterations () inline
Closes the file in which estimation iterations are saved.
Returns
Nothing
Definition at line 105 of file prPoseSphericalEstim.h.
track() [1/2]
template<class FSetT , class FSetCmpT > double prCameraPoseEstim< FSetT, FSetCmpT >::track (FSetT & FeatureSetd, vpPoseVector & r_optim, bool robust = false) inline inherited
Update the pose of FeatureSet so that it matches FeatureSetd.
Parameters
FeatureSetd the input data toward which degrees of freedom will have an impact on FeatureSet
r the 6-vector that contains pose elements values
Returns
the residual error at convergence
Definition at line 112 of file prCameraPoseEstim.h.
track() [2/2]
template<typename FSetT , typename FSetCmpT > double prPoseSphericalEstim< FSetT, FSetCmpT >::track (FSetT & FeatureSetd, vpPoseVector & r_optim, double lambda = 1.0, bool robust = false) inline
Update the pose of Id so that it matches I.
Parameters
Id the input image on which degrees of freedom will have an impact
r the 6-vector that contains pose elements values
Returns
the features comparator at convergence
Definition at line 121 of file prPoseSphericalEstim.h.
References prIntensity< Ts, Tcam >::buildFrom(), prIntensity< Ts, Tcam >::prIntensity(), and prIntensity< Ts, Tcam >::toDouble().