PER: prCartesian2DPointVec Class Reference
prCartesian2DPointVec Class Reference
#include <prCartesian2DPointVec.h>
Public Member Functions
prCartesian2DPointVec ()
virtual ~prCartesian2DPointVec () override=default
void set_x (const double x)
void set_y (const double y)
void set_w (const double w)
double get_x () const
double get_y () const
double get_w () const
unsigned int size ()
prCartesian2DPointVec changeFrame (const vpHomogeneousMatrix &oMi)
void setPoint (const double &x, const double &y)
void setVector (const double &x, const double &y)
void set (const double &x, const double &y, const double &w)
int toEuclidean ()
vpColVector operator- (const prCartesian2DPointVec &f)
Public Member Functions inherited from pr2DPointVec
virtual ~pr2DPointVec () override=default
Public Member Functions inherited from prPointVec
virtual ~prPointVec () override=default
Public Member Functions inherited from prGeometricElement
virtual ~prGeometricElement () override=default
Public Member Functions inherited from prPhysicalElement
prPhysicalElement ()
virtual ~prPhysicalElement ()=default
prPhysicalElement & operator= (const prPhysicalElement &pe)
unsigned int size ()
Additional Inherited Members
Protected Attributes inherited from prPhysicalElement
vpColVector p
Detailed Description
Definition at line 18 of file prCartesian2DPointVec.h.
Constructor & Destructor Documentation
prCartesian2DPointVec()
prCartesian2DPointVec::prCartesian2DPointVec ()
Definition at line 3 of file prCartesian2DPointVec.cpp.
References prPhysicalElement::p.
~prCartesian2DPointVec()
virtual prCartesian2DPointVec::~prCartesian2DPointVec () override virtual default
Member Function Documentation
changeFrame()
prCartesian2DPointVec prCartesian2DPointVec::changeFrame (const vpHomogeneousMatrix & oMi)
Applies the frame change from input frame Fi to output frame Fo.
Parameters
oMi frame change from the world to the sensor frame
Returns
Modifies the output prCartesian2DPointVec variable
Definition at line 8 of file prCartesian2DPointVec.cpp.
References get_w(), get_x(), get_y(), set(), and toEuclidean().
Referenced by prRegularlySampledCPImage< T >::changeSampleFrame().
get_w()
double prCartesian2DPointVec::get_w () const inline
Accessor to the homogeneous coordinate w in the normalized image planee (generally set to 1, its default value for a Cartesian point)
Returns
x
Definition at line 70 of file prCartesian2DPointVec.h.
Referenced by changeFrame(), prPointFeature::get_w(), and toEuclidean().
get_x()
double prCartesian2DPointVec::get_x () const inline
Accessor to the horizontal coordinate x in the normalized image plane.
Returns
x
Definition at line 56 of file prCartesian2DPointVec.h.
Referenced by prRegularlySampledCPImage< T >::buildFrom(), changeFrame(), prPointFeature::get_u(), prPointFeature::get_x(), toEuclidean(), and prRegularlySampledCPImage< T >::toImage().
get_y()
double prCartesian2DPointVec::get_y () const inline
Accessor to the vertical coordinate y in the normalized image plane.
Returns
y
Definition at line 63 of file prCartesian2DPointVec.h.
Referenced by prRegularlySampledCPImage< T >::buildFrom(), changeFrame(), prPointFeature::get_v(), prPointFeature::get_y(), toEuclidean(), and prRegularlySampledCPImage< T >::toImage().
operator-()
vpColVector & prCartesian2DPointVec::operator- (const prCartesian2DPointVec & f) inline
operator override to substract two 2D points or vectors *this and f are supposed Euclidean valid for points only
Parameters
f the 2D coordinates to substract from the current
Returns
the prPhotometricnnGMS<Ts> object resulting from the difference computation
Definition at line 134 of file prCartesian2DPointVec.h.
References prPhysicalElement::p.
set()
void prCartesian2DPointVec::set (const double & x, const double & y, const double & w)
Sets the 2D vector homogeneous coordinates.
Parameters
x the vector horizontal coordinate
y the vecotr vertical coordinate
w the vecotr homogeneous coordinate
Returns
Nothing
Definition at line 36 of file prCartesian2DPointVec.cpp.
References prPhysicalElement::p.
Referenced by changeFrame(), and toEuclidean().
set_w()
void prCartesian2DPointVec::set_w (const double w) inline
Sets the w coordinate of the point expressed in the normalized image plane.
Parameters
w the homogeneous coordinate in the normalized image plane (generally set to 1, its default value for a Cartesian point)
Returns
Nothing
Definition at line 48 of file prCartesian2DPointVec.h.
Referenced by prPointFeature::set_w().
set_x()
void prCartesian2DPointVec::set_x (const double x) inline
Sets the x coordinate of the point expressed in the normalized image plane.
Parameters
x the horizontal coordinate in the normalized image plane
Returns
Nothing
Definition at line 32 of file prCartesian2DPointVec.h.
Referenced by prPointFeature::set_u(), and prPointFeature::set_x().
set_y()
void prCartesian2DPointVec::set_y (const double y) inline
Sets the y coordinate of the point expressed in the normalized image plane.
Parameters
y the vertical coordinate in the normalized image plane
Returns
Nothing
Definition at line 40 of file prCartesian2DPointVec.h.
Referenced by prPointFeature::set_v(), and prPointFeature::set_y().
setPoint()
void prCartesian2DPointVec::setPoint (const double & x, const double & y)
Sets the 2D point coordinates, forcing w to 1.
Parameters
x the point horizontal coordinate
y the point vertical coordinate
Returns
Nothing
Definition at line 22 of file prCartesian2DPointVec.cpp.
References prPhysicalElement::p.
Referenced by prRegularlySampledCPImage< T >::initializeGrid().
setVector()
void prCartesian2DPointVec::setVector (const double & x, const double & y)
Sets the 2D vector coordinates, forcing w to 0.
Parameters
x the vector horizontal coordinate
y the vector vertical coordinate
Returns
Nothing
Definition at line 29 of file prCartesian2DPointVec.cpp.
References prPhysicalElement::p.
size()
unsigned int prCartesian2DPointVec::size () inline
Get the number of coordinates of the 2D point.
Returns
the number of coordinates
Definition at line 77 of file prCartesian2DPointVec.h.
toEuclidean()
int prCartesian2DPointVec::toEuclidean ()
Transforms the homogeneous coordinates of the point so that its homogeneous coordinate is equal to 1 (thus, only for a point)
Returns
0 if not a vector -1 otherwise
Definition at line 43 of file prCartesian2DPointVec.cpp.
References get_w(), get_x(), get_y(), and set().
Referenced by changeFrame().
The documentation for this class was generated from the following files:
libPeR_base/modules/core/include/per/core/prCartesian2DPointVec.h
libPeR_base/modules/core/src/prCartesian2DPointVec.cpp