PER: prFisheyeEquisolid Class Reference
prFisheyeEquisolid Class Reference
#include <prFisheyeEquisolid.h>
Public Member Functions
prFisheyeEquisolid (double au=0, double av=0, double u0=0, double v0=0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0)
virtual ~prFisheyeEquisolid () override=default
void init (double au, double av, double u0, double v0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0)
void project3DImage (prPointFeature &P)
bool unProject (prPointFeature &P, double &Depth)
void project3DSphere (prPointFeature &P, double &Xs, double &Ys, double &Zs)
virtual bool projectImageSphere (prPointFeature &P, double &Xs, double &Ys, double &Zs)
prFisheyeEquisolid & operator= (const prFisheyeEquisolid &cam)
void computeSensorJacobian (prPointFeature &P, vpMatrix &LuX)
Public Member Functions inherited from prCameraModel
prCameraModel (double au=0, double av=0, double u0=0, double v0=0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0, double k6=0, double k7=0, double k8=0)
virtual ~prCameraModel () override=default
void init (double au=0, double av=0, double u0=0, double v0=0, double k1=0, double k2=0, double k3=0, double k4=0, double k5=0, double k6=0, double k7=0, double k8=0)
void init (const prCameraModel &c)
void meterPixelConversion (prPointFeature &P)
void pixelMeterConversion (prPointFeature &P)
CameraModelType getType ()
std::string getName () const
double getau () const
double getav () const
double getu0 () const
double getv0 () const
double getk1 () const
double getk2 () const
double getk3 () const
double getk4 () const
double getk5 () const
double getk6 () const
double getk7 () const
double getk8 () const
double getik1 () const
double getik2 () const
double getik3 () const
double getik4 () const
double getik5 () const
double getik6 () const
double getik7 () const
double getik8 () const
int getNbActiveParameters () const
int getNbActiveDistorsionParameters () const
vpMatrix getK () const
void setDistorsions (bool d)
void setType (CameraModelType m)
void setName (std::string n)
void setPixelRatio (double au, double av)
void setPrincipalPoint (double u0, double v0)
void setDistorsionParameters (double k1=0, double k2=0, double k3=0, double k4=0, double k5=0, double k6=0, double k7=0, double k8=0)
void setUndistorsionParameters (double ik1=0, double ik2=0, double ik3=0, double ik4=0, double ik5=0, double ik6=0, double ik7=0, double ik8=0)
void setActiveDistorsionParameters (bool k1=true, bool k2=true, bool k3=true, bool k4=true, bool k5=true, bool k6=true, bool k7=true, bool k8=true)
virtual prCameraModel & operator= (const prCameraModel &cam)
virtual std::ostream & operator<< (std::ostream &os)
Public Member Functions inherited from prSensorModel
virtual ~prSensorModel ()=default
Additional Inherited Members
Public Attributes inherited from prCameraModel
double au
double av
double u0
double v0
double inv_av
double inv_au
CameraModelType type
std::string name
bool distorsions
double k [8]
bool activek [8]
double ik [8]
int nbActiveParametersBase
int nbActiveParameters
Detailed Description
Definition at line 18 of file prFisheyeEquisolid.h.
Constructor & Destructor Documentation
prFisheyeEquisolid()
prFisheyeEquisolid::prFisheyeEquisolid (double au = 0, double av = 0, double u0 = 0, double v0 = 0, double k1 = 0, double k2 = 0, double k3 = 0, double k4 = 0, double k5 = 0)
Contructor of the prFisheyeEquisolid camera model initializing intrinsic parameters.
Parameters
au the horizontal scale factor from the normalized image plane to the digital image (\alpha_u)
av the vertical scale factor from the normalized image plane to the digital image (\alpha_v)
u0 the horizontal coordinate of the principal point (u_0)
v0 the vertical coordinate of the principal point (v_0)
k1 the second order radial distorsion parameter (k_1)
k2 the fourth order radial distorsion parameter (k_2)
k3 the sixth order radial distorsion parameter (k_3)
k4 the first tangential distorsion parameter (k_4)
k5 the second tangential distorsion parameter (k_5)
Definition at line 3 of file prFisheyeEquisolid.cpp.
References FisheyeEquisolid, prCameraModel::name, and prCameraModel::type.
~prFisheyeEquisolid()
prFisheyeEquisolid::~prFisheyeEquisolid () override virtual default
Destructor of a prFisheyeEquisolid object.
Member Function Documentation
computeSensorJacobian()
void prFisheyeEquisolid::computeSensorJacobian (prPointFeature & P, vpMatrix & LuX) virtual
computes the Jacobian of the sensor digital image point coordinates with respect to the 3D coordinates in the camera frame
Parameters
P the point for which computing the Jacobian
LuX the output Jacobian Matrix
Returns
Nothing
Reimplemented from prCameraModel.
Definition at line 73 of file prFisheyeEquisolid.cpp.
init()
void prFisheyeEquisolid::init (double au, double av, double u0, double v0, double k1 = 0, double k2 = 0, double k3 = 0, double k4 = 0, double k5 = 0)
Initializing intrinsic parameters.
Parameters
au the horizontal scale factor from the normalized image plane to the digital image (\alpha_u)
av the vertical scale factor from the normalized image plane to the digital image (\alpha_v)
u0 the horizontal coordinate of the principal point (u_0)
v0 the vertical coordinate of the principal point (v_0)
k1 the second order radial distorsion parameter (k_1)
k2 the fourth order radial distorsion parameter (k_2)
k3 the sixth order radial distorsion parameter (k_3)
k4 the first tangential distorsion parameter (k_4)
k5 the second tangential distorsion parameter (k_5)
Returns
Nothing
Definition at line 9 of file prFisheyeEquisolid.cpp.
References FisheyeEquisolid, prCameraModel::init(), prCameraModel::name, and prCameraModel::type.
operator=()
prFisheyeEquisolid & prFisheyeEquisolid::operator= (const prFisheyeEquisolid & cam)
= operator overload for copying a prFisheyeEquisolid camera model
Parameters
cam the source prFisheyeEquisolid
Returns
the affected prFisheyeEquisolid.
Definition at line 66 of file prFisheyeEquisolid.cpp.
References prCameraModel::operator=().
project3DImage()
void prFisheyeEquisolid::project3DImage (prPointFeature & P) virtual
Project a 3D point expressed in the equisolid fisheye camera frame to the normalized image plane.
Parameters
P the point to project
Returns
Nothing
Implements prCameraModel.
Definition at line 18 of file prFisheyeEquisolid.cpp.
References prPointFeature::get_X(), prPointFeature::get_Y(), prPointFeature::get_Z(), prPointFeature::set_x(), and prPointFeature::set_y().
project3DSphere()
void prFisheyeEquisolid::project3DSphere (prPointFeature & P, double & Xs, double & Ys, double & Zs)
Project a 3D point expressed in the equisolid fisheye camera frame to the unit sphere centered at the camera origin.
Parameters
P the point to project
Xs the Cartesian X coordinate of the projected point on the unit sphere
Ys the Cartesian Y coordinate of the projected point on the unit sphere
Zs the Cartesian Z coordinate of the projected point on the unit sphere
Returns
Nothing
Definition at line 36 of file prFisheyeEquisolid.cpp.
References prPointFeature::get_X(), prPointFeature::get_Y(), and prPointFeature::get_Z().
projectImageSphere()
bool prFisheyeEquisolid::projectImageSphere (prPointFeature & P, double & Xs, double & Ys, double & Zs) virtual
Inverse projection from the normalized image plane to the unit sphere centered at the camera origin.
Parameters
P the point to backproject
Xs the Cartesian X coordinate of the projected point on the unit sphere
Ys the Cartesian Y coordinate of the projected point on the unit sphere
Zs the Cartesian Z coordinate of the projected point on the unit sphere
Returns
Nothing
Implements prCameraModel.
Definition at line 51 of file prFisheyeEquisolid.cpp.
unProject()
bool prFisheyeEquisolid::unProject (prPointFeature & P, double & Depth) virtual
Compute the 3D point expressed in the sensor frame from the normalized image plane and the depth (must be implemented in a specified sensor model)
Parameters
P the point to unproject
Depth the Depth used to unproject the P (/rho here...)
Returns
true if unprojection could be done
Implements prCameraModel.
Definition at line 29 of file prFisheyeEquisolid.cpp.
The documentation for this class was generated from the following files:
libPeR_base/modules/core/include/per/core/prFisheyeEquisolid.h
libPeR_base/modules/core/src/prFisheyeEquisolid.cpp