PER: prCameraModelConvert Class Reference
prCameraModelConvert Class Reference
#include <prCameraModelConvert.h>
Public Member Functions
virtual ~prCameraModelConvert ()=default
Static Public Member Functions
static double convert (prFisheyeEquidistant &fecam, prOmni &ocam, double theoreticalFOV=180, vpMatrix *abs_err=NULL)
static double convert (prOmni &ocam, prPolyCart &pccam, double theoreticalFOV=180, vpMatrix *abs_err=NULL)
static double convert_distortions (prCameraModel *incam, prCameraModel *outcam, double theoreticalFOV=90, vpMatrix *abs_err=NULL)
static double convert (prCameraModel *pcam, prOmni *ocam, double theoreticalFOV=180, vpMatrix *abs_err=NULL)
static double conversion (prCameraModel *inputcam, prCameraModel *outputcam, double theoreticalFOV=120, vpMatrix *abs_err=NULL)
static double converted (prPolyCart *inputcam, prCameraModel *outputcam, double theoreticalFOV=120, vpMatrix *abs_err=NULL)
static double FCVreverseConvert (prPolyCart *inputcam, prCameraModel *outputcam, double theoreticalFOV=120, vpMatrix *abs_err=NULL, double image_size=NULL)
static double KBreverseConvert (prPolyCart *inputcam, prCameraModel *outputcam, double theoreticalFOV=120, vpMatrix *abs_err=NULL)
static double convert (prFisheyeEquisolid &fescam, prOmni &ocam, double theoreticalFOV=180, vpMatrix *abs_err=NULL)
Detailed Description
Definition at line 21 of file prCameraModelConvert.h.
Constructor & Destructor Documentation
~prCameraModelConvert()
virtual prCameraModelConvert::~prCameraModelConvert () virtual default
Member Function Documentation
conversion()
double prCameraModelConvert::conversion (prCameraModel * inputcam, prCameraModel * outputcam, double theoreticalFOV = 120, vpMatrix * abs_err = NULL) static
Converter of distorsion parameters to a smaller number of distorsion parameters: Rational-polynomial model to Fisheye OpenCV model TODO: add an enum for other cases of conversion as method parameter.
Parameters
inputcam the input camera model
outputcam the output camera model
theoreticalFOV (optional) theoretical FOV [degrees] (as close to the reality for a better approximation). Default 180 degrees.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the Rational-polynomial model with a Fisheye OpenCV one.
Returns
the average residual (digital image plane) of the conversion that is an approximation
Definition at line 411 of file prCameraModelConvert.cpp.
References prPointFeature::get_v(), prPointFeature::get_x(), prPointFeature::get_y(), prCameraModel::getau(), prCameraModel::getav(), prCameraModel::getk1(), prCameraModel::getk2(), prCameraModel::getk3(), prCameraModel::getk4(), prCameraModel::getk5(), prCameraModel::getk6(), prCameraModel::getk7(), prCameraModel::getk8(), prCameraModel::getu0(), prCameraModel::getv0(), prCameraModel::meterPixelConversion(), prPointFeature::set_u(), prPointFeature::set_v(), prPointFeature::set_x(), prPointFeature::set_y(), and prCameraModel::setDistorsionParameters().
Referenced by main().
convert() [1/4]
double prCameraModelConvert::convert (prCameraModel * pcam, prOmni * ocam, double theoreticalFOV = 180, vpMatrix * abs_err = NULL) static
Definition at line 334 of file prCameraModelConvert.cpp.
References prPointFeature::get_u(), prCameraModel::getu0(), prCameraModel::getv0(), prOmni::init(), prCameraModel::meterPixelConversion(), prOmni::project3DImage(), prCameraModel::project3DImage(), prPointFeature::set_X(), prPointFeature::set_Y(), and prPointFeature::set_Z().
convert() [2/4]
double prCameraModelConvert::convert (prFisheyeEquidistant & fecam, prOmni & ocam, double theoreticalFOV = 180, vpMatrix * abs_err = NULL) static
Converter of a prFisheyeEquidistant camera model to a prOmni camera model TODO: generalize to au different to av (currently, only the horizontal parameters are considered to output au=av)
Parameters
fecam the input fisheye equidistant camera model
ocam the output omni camera model
theoreticalFOV (optional) theoretical FOV [degrees] (as close to the reality for a better approximation). Default 180 degrees.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the fisheye equidistant model with a Omni one.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the fisheye equidistant model with a Omni one.
Returns
the average residual (digital image plane) of the conversion that is an approximation
Definition at line 195 of file prCameraModelConvert.cpp.
References prCameraModel::getau(), prCameraModel::getu0(), and prCameraModel::getv0().
Referenced by main().
convert() [3/4]
double prCameraModelConvert::convert (prFisheyeEquisolid & fescam, prOmni & ocam, double theoreticalFOV = 180, vpMatrix * abs_err = NULL) static
Converter of a prFisheyeEquisolid camera model to a prOmni camera model TODO: generalize to au different to av (currently, only the horizontal parameters are considered to output au=av)
Parameters
fescam the input fisheye equisolid camera model
ocam the output omni camera model
theoreticalFOV (optional) theoretical FOV [degrees] (as close to the reality for a better approximation). Default 180 degrees.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the fisheye equisolid model with a Omni one.
Returns
the average residual (digital image plane) of the conversion that is an approximation
Definition at line 849 of file prCameraModelConvert.cpp.
References prCameraModel::getau(), prCameraModel::getu0(), and prCameraModel::getv0().
convert() [4/4]
double prCameraModelConvert::convert (prOmni & ocam, prPolyCart & pccam, double theoreticalFOV = 180, vpMatrix * abs_err = NULL) static
Converter of a prOmni camera model to a prPolyCart camera model TODO: generalize to au different to av (currently, only the horizontal parameters are considered to output au=av)
Parameters
ocam the input omni camera model
pccam the output polycart camera model
theoreticalFOV (optional) theoretical FOV [degrees] (as close to the reality for a better approximation). Default 180 degrees.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the polycart model with a Omni one.
Returns
the average residual (digital image plane) of the conversion that is an approximation
Definition at line 86 of file prCameraModelConvert.cpp.
References prPointFeature::get_x(), prCameraModel::getau(), prCameraModel::getu0(), prCameraModel::getv0(), prOmni::getXi(), prPolyCart::init(), prOmni::project3DImage(), prPointFeature::set_X(), prPointFeature::set_Y(), and prPointFeature::set_Z().
convert_distortions()
double prCameraModelConvert::convert_distortions (prCameraModel * incam, prCameraModel * outcam, double theoreticalFOV = 90, vpMatrix * abs_err = NULL) static
Converter of distorsion parameters to a smaller number of distorsion parameters: Rational-polynomial model to Plumb-Bob model Assumes outcam is already allocated and only the distorsion parameters will be changed TODO: add an enum for other cases of conversion as method parameter.
Parameters
incam the input camera model
outcam the output camera model
theoreticalFOV (optional) theoretical FOV [degrees] (as close to the reality for a better approximation). Default 180 degrees.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the Rational-polynomial model with a Plumb-Bob one.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the Rational-polynomial model with a Plumb-Bob one.
Returns
the average residual (digital image plane) of the conversion that is an approximation
Definition at line 252 of file prCameraModelConvert.cpp.
References prPointFeature::get_u(), prCameraModel::getk1(), prCameraModel::getk2(), prCameraModel::getk3(), prCameraModel::getk4(), prCameraModel::getk5(), prCameraModel::getk6(), prCameraModel::getk7(), prCameraModel::getk8(), prCameraModel::meterPixelConversion(), prPointFeature::set_x(), prPointFeature::set_y(), and prCameraModel::setDistorsionParameters().
Referenced by main().
converted()
static prCameraModelConvert::converted (prPolyCart * inputcam, prCameraModel * outputcam, double theoreticalFOV = 120, vpMatrix * abs_err = NULL) static
Converter of a prPolyCart camera model to a Fisheye OpenCV camera model
Parameters
inputcam the input camera model
outputcam the output camera model
theoreticalFOV (optional) theoretical FOV [degrees] (as close to the reality for a better approximation). Default 180 degrees.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the Cartesian-polynomial model with a Fisheye OpenCV one.
Returns
the average residual (digital image plane) of the conversion that is an approximation
FCVreverseConvert()
double prCameraModelConvert::FCVreverseConvert (prPolyCart * inputcam, prCameraModel * outputcam, double theoreticalFOV = 120, vpMatrix * abs_err = NULL, double image_size = NULL) static
Converter of a prPolyCart camera model to a Fisheye OpenCV camera model
Parameters
inputcam the input camera model
outputcam the output camera model
image_size the size of the image of the input camera model
theoreticalFOV (optional) theoretical FOV [degrees] (as close to the reality for a better approximation). Default 180 degrees.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the Cartesian-polynomial model with a Fisheye OpenCV one.
Returns
the average residual (digital image plane) of the conversion that is an approximation
Definition at line 562 of file prCameraModelConvert.cpp.
References prPointFeature::get_u(), prPolyCart::geta0(), prPolyCart::geta2(), prPolyCart::geta3(), prPolyCart::geta4(), prCameraModel::getu0(), prPointFeature::set_u(), prCameraModel::setDistorsionParameters(), and prCameraModel::setPixelRatio().
Referenced by main().
KBreverseConvert()
double prCameraModelConvert::KBreverseConvert (prPolyCart * inputcam, prCameraModel * outputcam, double theoreticalFOV = 120, vpMatrix * abs_err = NULL) static
Converter of a prPolyCart camera model to a Kannala Brandt camera model
Parameters
inputcam the input camera model
outputcam the output camera model
theoreticalFOV (optional) theoretical FOV [degrees] (as close to the reality for a better approximation). Default 180 degrees.
abs_err (optional) matrix containing the angles considered in the conversion (column 1) and the absolute errors (column 2) made by approximating the Cartesian-polynomial model with a Kannala Brandt one.
Returns
the average residual (digital image plane) of the conversion that is an approximation
Definition at line 720 of file prCameraModelConvert.cpp.
References prPointFeature::get_u(), prPolyCart::geta0(), prPolyCart::geta2(), prPolyCart::geta3(), prPolyCart::geta4(), and prPointFeature::set_u().
The documentation for this class was generated from the following files:
libPeR_base/modules/core/include/per/core/prCameraModelConvert.h
libPeR_base/modules/core/src/prCameraModelConvert.cpp