PER: libPeR_base/example/pointPerspectiveProjection/pointPerspectiveProjection.cpp File Reference
pointPerspectiveProjection.cpp File Reference
#include <iostream>
#include <per/prPerspective.h>
#include <per/prPointFeature.h>
#include <visp/vpHomogeneousMatrix.h>
Functions
int main ()
Detailed Description
Example program of the PeR core module.
Author
Guillaume CARON
Version
0.1
Date
january 2017
Definition in file pointPerspectiveProjection.cpp.
Function Documentation
main()
int main ()
< A feature point
< Generic sensor model
< Sensor pose
Definition at line 23 of file pointPerspectiveProjection.cpp.
References prPointFeature::changeFrame(), prPointFeature::get_oX(), prPointFeature::get_oY(), prPointFeature::get_oZ(), prPointFeature::get_u(), prPointFeature::get_v(), prPointFeature::get_X(), prPointFeature::get_x(), prPointFeature::get_Y(), prPointFeature::get_y(), prPointFeature::get_Z(), and prPointFeature::setWorldCoordinates().