PER: libPeR_base/example/RationalPolynomial2FisheyeOpenCV/RationalPolynomial2FisheyeOpenCV.cpp File Reference
RationalPolynomial2FisheyeOpenCV.cpp File Reference
#include <iostream>
#include <per/prPerspective.h>
#include <per/prCameraModelConvert.h>
#include <visp/vpMatrix.h>
Functions
int main ()
Detailed Description
Example program to convert a PeR camera model to another.
Author
Eva Goichon
Version
0.1
Date
July 2024
Definition in file RationalPolynomial2FisheyeOpenCV.cpp.
Function Documentation
main()
int main ()
Definition at line 25 of file RationalPolynomial2FisheyeOpenCV.cpp.
References prCameraModelConvert::conversion(), prCameraModel::getau(), prCameraModel::getav(), prCameraModel::getk1(), prCameraModel::getk2(), prCameraModel::getk3(), prCameraModel::getk4(), prCameraModel::getName(), prCameraModel::getu0(), and prCameraModel::getv0().